### ISSUE TITLE
@polkadot/extension-dapp  throw  errors

### ISSUE THREAD

**Issue by saqing** [polkadot-js/extension#1018]
Hi,

I encountered the following problems when using this package （   "@polkadot/extension-dapp": "^0.42.7",）
`vite build `
[vite:asset-import-meta-url] EISDIR: illegal operation on a directory, read
file: D:/git-repos/biubiu-tools/node_modules/@polkadot/extension-dapp/packageInfo.js
error during build:
Error: EISDIR: illegal operation on a directory, read  

`vite dev`
Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at @polkadot_extension-dapp.js:8227:9

// node_modules/@polkadot/x-global/packageInfo.js
var import_meta = {};
var packageInfo = {
  name: "@polkadot/x-global",
  path: new URL(".", import_meta.url).pathname,
  type: "esm",
  version: "8.4.1"
};

This prevents my dapp from accessing the polkadot.js extension wallet, please help

**Comment by jacogr** [comment]
It is a vite issue in this `asset-import-meta-url` plugin. The Vite repo has an issue for this.
