### ISSUE TITLE
[HELP] Mainfest v3 : wasm-crypto I got this issue when i made a wallet ext on mainfest v3 for Chrome extension.

### ISSUE THREAD

**Issue by MingFEW** [polkadot-js/extension#1024]
I make a wallet extension to connect coin on polkadot chain. 
- It worked well on **mainfest v2** as polkadot ext 
BUT the chrome store doesn't allow mainfest V2 any more. so i have to change to mainfest v3. 
and i got this issue when i turn to v3. Do you have any idea. Please help me!!!

* wasm-crypto and polkadot utils . mainfest v3 of chrome store doesn't allow WebAssembly to connect a wasm. 

![aaaa](https://user-images.githubusercontent.com/93752329/157791909-e6b73565-6db1-415e-a647-d74f43f3cd79.jpg)

**Comment by jacogr** [comment]
There doesn't seem to be traction with the Chrome support atm, see 

- https://groups.google.com/a/chromium.org/g/chromium-extensions/c/zVaQo3jpSpw?pli=1
- https://bugs.chromium.org/p/chromium/issues/detail?id=1173354

The WASM environment is required for sr25519 (everything else, eg. hashing has fallbacks). You could try and configure the build with asm.js, here are some pointers with Webpack -

- https://github.com/polkadot-js/wasm/issues/293
- https://github.com/polkadot-js/api/issues/4610

**Comment by jacogr** [comment]
There seems to have been movement in the above Chrome issue, specifically [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1173354#c62) that points to [this PR](https://chromium.googlesource.com/chromium/src/+/7d96ed51f3496d922eb58440745cbb5cfd97a47d).

Reproducing a [test manifest](https://chromium.googlesource.com/chromium/src/+/7d96ed51f3496d922eb58440745cbb5cfd97a47d/extensions/test/data/manifest_tests/csp_dictionary_with_wasm.json) included above here -

```json
{
  "name": "test",
  "version": "0.1",
  "manifest_version": 3,
  "content_security_policy": {
    "extension_pages" : "worker-src 'self' 'wasm-unsafe-eval'; default-src 'self'"
  }
}
```

**Comment by MingFEW** [comment]
![imagessss](https://user-images.ithubusercontent.com/93752329/161929270-2da4983a-c1f5-4195-9fbd-84409e310b99.jpg)
@jacogr i got this issue when try to build.
