### ISSUE TITLE
Error: Message signing is not supported by hardware wallets Ledger StaFi Protocol

### ISSUE THREAD

**Issue by corteshvictor** [polkadot-js/extension#1025]
Greetings.

I am performing a staking from my `DOT` to `rDOT` in `StaFi Protocol` with a Ledger Nano X and the transaction was successful in step 1.

But step 2 shows me an error, I am performing the process from my ledger any idea about this error:

_**"Message signing is not supported by hardware wallets".**_

<img width="889" alt="image" src="https://user-images.githubusercontent.com/17968316/158044739-941cfdcc-09de-4894-bc69-62e1d53555ec.png">

**Comment by jacogr** [comment]
Ledger does not expose raw-message signing capabilities. It only allows signing of transaction payloads.

**Comment by corteshvictor** [comment]
@jacogr I am not clear about what you are saying, but I think the problem is still polkadot that does not let you sign.

The other networks have not presented me with this problem, when I have problems I just enable the blind signing.

I don't know much about the technical part but it is strange that this error only occurs with polkadot because with other networks I have no problems.

**Comment by jacogr** [comment]
The Ledger software (the actual software on the device) does not have a signer interface that allows for messages. So, there isn nothing the software here can do to get around it. There is no interface available on the Ledger to make this possible. (It only allows for the signing of fully-constructed transactions)

The error is correct - it is an unsupported operation on Ledger devices, technically it is unsupported an not available at all on the Ledger.
