### ISSUE TITLE
Ability to remove approval for the website

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/extension#1028]
Current extension asks you to grant approval only once per the web.
Then there is a switch which can toggle between approve/deny.
<img width="560" alt="Screenshot 2022-03-17 at 13 22 56" src="https://user-images.githubusercontent.com/22471030/158807862-22b292fc-897f-4145-925f-25c4d1a24c52.png">

I would like to have an option to delete the approval [like a trashbin button] so the app will have to ask user again.

Related https://github.com/kodadot/nft-gallery/pull/2574

**Comment by vikiival** [comment]
For example Talisman has an option to `Forget site`
<img width="692" alt="Screenshot 2022-03-17 at 13 28 26" src="https://user-images.githubusercontent.com/22471030/158808562-10545d0f-5f7e-4e43-b616-0eeff50eee24.png">

**Comment by jacogr** [comment]
PRs welcome if this is an issue for you. (Don't know what Talisman is, and this extension also doesn't try to be more than it is - it really is brea-bones).

So for a PR, what you will need -

- the UI bits
- an even on click of the trash
- (potential yay/nay box)
- a new message that removes (also to be added to the backend handlers)

The above should tie things in.

**Comment by jacogr** [comment]
EDIT2 - in your case with the test sites, can see why you are asking for it from the screenshot.

**Comment by Are10** [comment]
I was just looking if this functionality was available earlier today and found this issue. I have submitted a PR with my fix.
Please be aware that this was my first foray into Typescript and extensions, so please keep that in mind when reviewing.

I am willing to make changes to my solution if that is required. 
@jacogr Thank you for making such detailed suggestions, they helped immensely!
