### ISSUE TITLE
Injected failed in cypress process

### ISSUE THREAD

**Issue by sxlwar** [polkadot-js/extension#1031]
I am trying to build a tool to test our dapp which is interactive with the  Polkadot-extension.

I don't know why the injection is always unsuccessful during E2E testing

<img width="809" alt="image" src="https://user-images.githubusercontent.com/20088392/159132881-5c7526ca-78e3-4ba6-b1be-0182466ffde9.png">

When typing the URL manually to load the page, it can be successfully injected.

Repo here: https://github.com/darwinia-network/popress
Reproduce steps:
yarn install -----> yarn start ----> yarn test ----> select the activeExtensions.spec.ts

**Comment by Tbaut** [comment]
Cypress runs a headless browser (chrome by default) that doesn't have Polkadot.js extension installed. Cypress doesn't allow to test interactions with extensions as far as I know.
If you want to test your dapp this way, you'll need to inject manually anything that the extension is injecting, and mock anything that the extension would do.

**Comment by sxlwar** [comment]
> Cypress runs a headless browser (chrome by default) that doesn't have Polkadot.js extension installed. Cypress doesn't allow to test interactions with extensions as far as I know.
> If you want to test your dapp this way, you'll need to inject manually anything that the extension is injecting in the window object, and mock anything that the extension would do.

Yeah, the demo run in a full-head mode. Before the browser launch, it will download the Polkadot-extension and install it to the browser, and then complete the account import process by puppeteer before testing.

Strangely, if refresh the browser(whether manually or by the puppeteer), the injection will success

**Comment by sxlwar** [comment]
I might have found the reason,  the dapp under an iframe can not wake up the extension. Another word, the polkadot-extension is not injected into iframe.

https://stackblitz.com/edit/react-ts-vemjgq?file=index.tsx

In the context of the dapp
<img width="636" alt="image" src="https://user-images.githubusercontent.com/20088392/160133398-19b53c64-e1e2-454f-b495-5ef38f11e136.png">

In the top context of the browser:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/20088392/160133734-d4d5bd84-9c1e-4ff6-834f-df14d70de4ac.png">

@Tbaut @jacogr  any idea?

**Comment by jacogr** [comment]
That makes sense. It doesn’t inject into iframes.
