### ISSUE TITLE
Extension update | include staking & parachains · push notifications 

### ISSUE THREAD

**Issue by pitimini-debug** [polkadot-js/extension#1032]
I would like to make an open proposal.

Imo in the crypto world there is a communication barrier between projects and users.
The projects ussually lack their own communication channel that they control and have to resort to third parties twitter, discord, medium, telegram hoping: 1. that the user has those applications opened and 2. that the message is positioned against the competition.

However by the time polkadot and kusama have developed a browser plugin, they have build an own channel and left a door open to notify users, a door that unlike previous channels will be open for much longer (it is rare the user who is connected to its PC and does not have the browser opened) and in their own channel where they do not compete with third parties for having a better presence.

Therefore, with this proposal I'd like to put on the table the possibility of using the plugin as a channel to prescribe-notify users:
1. Those functions that provide security and generate robustness in the ecosystem (staking and parachains)
2. Can be extended to any something else, (governance, calendar events and even plain text notifications)

I think that to carry it out, a minimal redesign of the application would have to be done, there would be many ways to do it, however, in the attached document I present the one organized way i have found so it can be enlarged with more features in the future if it applies

I attach the proposal focused on those aspects that I consider a priority (staking and parachains) with a simple solution of external redirection towards those points and minimal UI redesign:
https://docs.google.com/presentation/d/1Zqbq9PLRvf87BmFxBqF16obcdB_fsy1xY3BH5aBosDk/edit#slide=id.g11dd4316011_0_130

**Comment by Nick-1979** [comment]
Hello,
Nice  google docs presentation. we already designed an app on top of polkadot js extension which has kind of similar notifications for staking (like oversubscribed, no active validators in this era, no nominations, etc. ), you could find the app here: https://addons.mozilla.org/en-US/firefox/addon/polkadot-js-plus-extension/

**Comment by jacogr** [comment]
Thank you for putting together the above, it is interesting. 

It is however way out of scope for the extension, it is only a signer and doesn’t aim to be more. It does not maintain any connections to networks.
