### ISSUE TITLE
extension will stop working on Jan 2023

### ISSUE THREAD

**Issue by Nick-1979** [polkadot-js/extension#1033]
hello,

Based on chrome announcement, extensions which use Manifest V2 will stop working on Jan 2023.

In Manifest v3, there are some major changes like migrating from "background pages to service workers" and  some CSP restrictions.
I think these changes will affect the extension as it uses "background.js" and " blob and wasm" in CSP.
Hence, It seems a kind of redesign might be needed to comply with the aforementioned changes.

I do not know if there is already anyone working to address this issues?

![image](https://user-images.githubusercontent.com/46442452/159373830-abeed79c-a40d-45a8-854b-f784167be5cb.png)

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/extension/issues/310
