### ISSUE TITLE
Support (manually set) proxied calls

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/extension#1035]
Currently, it is a PITA to use a proxy account in any UI, except if you using polkaodt.js/apps. For most parachains, this is not feasible since they have their own daap. Most of these dapps support polkadot.js/extension as a wallet option.

As it stands now, the only way to effectively submit proxy calls is to hack into the dapp that you are using to give you the call details that is trying to pass to the extension in some human readable format, and then submit it manually yourself in `polkaodt.js/apps`. 

polkaodt.js/apps itself is pretty smart in in detecting proxies. I am not suggesting that, since this requires extension to go online, I actually love the fact that this extension is 100% offline. 

Instead, to at least allow this 2-step process, I suggest allowing to user to manually wrap any call that the extension receives in a `proxy.proxy()` call, and chose which account should proxy it.

**Comment by jacogr** [comment]
You cannot really add a proxy call around the incoming tx (which is actually the full payload being received) without network connectivity - you need to have the nonce to sign the transaction payload, this would differ from the inner vs outer accounts.

**Comment by kianenigma** [comment]
Okay, and then given the assumption that the extension remains fully offline, I don't see any possibility for this. Reopen if you have some trick for it up your sleeve, otherwise it is a feature that we don't want by design.
