### ISSUE TITLE
 Cannot find module '@polkadot/util/cjs/packageInfo' from 'node_modules/@polkadot/hw-ledger/cjs/detectOther.js'

### ISSUE THREAD

**Issue by Nick-1979** [polkadot-js/extension#1044]
Hello, 

When I run a test on the latest stable v.0.42.10 I get the following error which seems some modules does not find their dependencies!
I tried on the latest beta, but some similar thing happened.
any recommendations ? thank you

 Cannot find module '@polkadot/util/cjs/packageInfo' from 'node_modules/@polkadot/hw-ledger/cjs/detectOther.js'

    Require stack:
      node_modules/@polkadot/hw-ledger/cjs/detectOther.js
      node_modules/@polkadot/hw-ledger/cjs/detectPackage.js
      node_modules/@polkadot/hw-ledger/cjs/index.js
      packages/extension-ui/src/hooks/useLedger.ts
      packages/extension-ui/src/partials/MenuAdd.tsx
      packages/extension-ui/src/partials/Header.tsx
      packages/extension-ui/src/partials/index.ts
      packages/extension-ui/src/components/AccountNamePasswordCreation.tsx
      packages/extension-ui/src/components/index.ts
       ....
      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/@polkadot/hw-ledger/cjs/detectOther.js:10:21)

**Comment by jacogr** [comment]
The stable version doesn’t have that issue. See https://github.com/polkadot-js/extension/blob/7df5a211fe9926b426c614c465608048f5e336d0/packages/extension-inject/package.json

The beta versions would unless all packages are also beta from common.

**Comment by Nick-1979** [comment]
Thank you very much for the prompt answer.

**Comment by jacogr** [comment]
The updates common, extension, up will be in stable tomorrow. (API on Sunday)
