### ISSUE TITLE
parity-signer:: password derived based account, how to use in polkadot js extension?

### ISSUE THREAD

**Issue by icanfly** [polkadot-js/extension#1048]
I used the derived path of Polkadot parity wallet (and added the derived password). Now my account is used in other Polkadot ecological chains (participating in crowdfunding on parallel), and then I got the token reward on parallel chain. However, when I wanted to transfer the token on parallel chain, I found that Polkadot JS wallet asked me to process the parity signer. At the same time, Polkadot JS wallet does not support derivation based on password path. It says "/ / / password not supported for 'derivation'. How can I make my wallet address derived based on password available to other ecological chains. 

Looking forward to your reply, I am extremely anxious.

**Comment by jacogr** [comment]
Screenshot with `///Password` via the import seed option -
![image](https://user-images.githubusercontent.com/1424473/163590012-690d128a-628c-4ed7-a471-94fca63fa090.png)

**Comment by icanfly** [comment]
yeah, I resolved this problem using blew method:

> Mnemonics, Passwords, and Imports/Exports
Using the mnemonic and password from the extension
When you create a keypair via the extension, it supplies a 12-word mnemonic seed and asks you to create a password. This password only encrypts the private key on disk so that the password is required to spend funds in polkadot-js/apps or to import the account from backup. The password does not protect the mnemonic phrase. That is, if an attacker were to acquire the mnemonic phrase, they would be able to use it to spend funds without the password.

Importing mnemonics from other key generation utilities
Some key-generation tools, e.g. [Subkey](https://www.substrate.io/kb/integrate/subkey), support hard and soft key derivation as well as passwords that encrypt the mnemonic phrase such that the mnemonic phrase itself is insufficient to spend funds.

The extension supports these advanced features. When you import an account from a seed, you can add these derivation paths or password to the end of the mnemonic in the following format:

<mnemonic phrase>//<hard>/<soft>///<password>
That is, hard-derivation paths are prefixed with //, soft paths with /, and the password with ///.

The extension will still ask you to enter a password for this account. As before, this password only encrypts the private key on disk. It is not required to be the same password as the one that encrypts the mnemonic phrase.

Accounts can also be derived from existing accounts – Derive New Account option in account's dropdown menu should be selected. After providing the password of the parent account, along with name and password of the derived account, enter derivation path in the following format:

//<hard>/<soft>
The path will be added to the mnemonic phrase of the parent account.

Link inspiration:  https://libraries.io/npm/@polkadot%2Fextension-dapp

**Comment by icanfly** [comment]
> Screenshot with `///Password` for the derivation path via the import seed option -
> 
> ![image](https://user-images.githubusercontent.com/1424473/163590012-690d128a-628c-4ed7-a471-94fca63fa090.png)

using the method you said, it says : 

/// password not supported for 'derivation'

my derived path like this format:
//\<hard\>/\<soft\>///\<password\>

**Comment by jacogr** [comment]
See the above, you are using the "derive from seed" option, not the "import seed" option. The password ia applied when you go from mnemonic -> entropy, only available on that option.

Once you have an account, and try to derive from it, you won't be able to. Hence the "import from seed" + advance + "derivation path" - as per the answer above.
