### ISSUE TITLE
Undefined error in next js 

### ISSUE THREAD

**Issue by sxlwar** [polkadot-js/extension#1050]
![image](https://user-images.githubusercontent.com/20088392/164868519-e08cfaea-d120-47a3-874e-ec693ffd3c31.png)

**Comment by jacogr** [comment]
The init checks always needs to be run in the browser, see https://github.com/polkadot-js/extension/blob/master/packages/extension-dapp/src/bundle.ts

Without the window object, it means it is not run inside the browser context.

**Comment by sxlwar** [comment]
So for the next js project that references this package,  dynamic import is the option only?

**Comment by jacogr** [comment]
I'm honestly not a Next guru, so apart from a high-level understanding "it does exist and seems cool", I don't have any more specific insights into how it operates or tips and tricks.

**Comment by sxlwar** [comment]
> I'm honestly not a Next guru, so apart from a high-level understanding "it does exist and seems cool", I don't have any more specific insights into how it operates or tips and tricks.

thanks for your reply
