### ISSUE TITLE
Settings menu and + menu do not appear on click, on master

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#1058]
On master build, the settings menu and + menu do not appear when clicking on them. This looks like some styling issues. I'm not sure what update could have caused this. I went back to the commit 415184ac "Add authorized URL removal  (#1029)" and it's working there.

Tested on Chrome and FF.

**Comment by jacogr** [comment]
Weird :( I should have picked this up since I generally run master, but behind a bit :(

**Comment by Tbaut** [comment]
I'm working on the auth flow for now but I will check it out in the next days

**Comment by jacogr** [comment]
I will check this one out, no sweat.

**Comment by jacogr** [comment]
The `useOutsideClick` seem to now screw things up. When I comment it out, it shows. So it would seem the event fires on both those and just cancels the show.

I think this is indeed React 18 related, it batches the updates.
