### ISSUE TITLE
Sign transactions on moon* chains

### ISSUE THREAD

**Issue by ekenigs** [polkadot-js/extension#1061]
I have tried to figure out what needs to be done so users can sign transactions on Moonbase, Moonriver, and Moonbeam chains from the Extension on Polkadot.js Apps. I'm a bit stuck with my investigation and need some help.

Currently, there is an error when I'm trying to send funds to another account:
<img width="835" alt="Screenshot 2022-05-10 at 10 59 39" src="https://user-images.githubusercontent.com/15612217/167693082-8fa599bd-bbb1-43e3-973d-dbfa757865ad.png">

The difference in signing transactions from Apps or Extension is that a prefix is added when Extension is signing.

https://github.com/polkadot-js/common/blob/master/packages/keyring/src/pair/index.ts#L190

```typescript
const TYPE_PREFIX = {
  ecdsa: new Uint8Array([2]),
  ed25519: new Uint8Array([0]),
  ethereum: new Uint8Array([2]), // <- this
  sr25519: new Uint8Array([1]),
};
```
```typescript
    sign: (message: HexString | string | Uint8Array, options: SignOptions = {}): Uint8Array => {
      assert(!isLocked(secretKey), 'Cannot sign with a locked key pair');

      return u8aConcat(
        options.withType
          ? TYPE_PREFIX[type]
          : SIG_TYPE_NONE,
        TYPE_SIGNATURE[type](u8aToU8a(message), { publicKey, secretKey })
      );
    },
```

The flag `options.withType` is coming from:

https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/v4/ExtrinsicPayload.ts#L36

```typescript
  constructor (registry: Registry, value?: ExtrinsicPayloadValue | Uint8Array | HexString) {
    super(registry, objectSpread(
      { method: 'Bytes' },
      registry.getSignedExtensionTypes(),
      registry.getSignedExtensionExtra()
    ), value);

    // Do detection for the type of extrinsic, in the case of MultiSignature
    // this is an enum, in the case of AnySignature, this is a Hash only
    // (which may be 64 or 65 bytes)
    this.#signOptions = {
      withType: registry.createTypeUnsafe('ExtrinsicSignature', []) instanceof Enum
    };
  }
```

What I don't understand is why when Apps is signing then `ExtrinsicSignature` is not an instance of `Enum` and when from Extension it is.

I have tried to work around it by changing the condition to:

```typescript
      return u8aConcat(
        options.withType && type !== 'ethereum'
          ? TYPE_PREFIX[type]
          : SIG_TYPE_NONE,
        TYPE_SIGNATURE[type](u8aToU8a(message), { publicKey, secretKey })
      );
```

This works but doesn't feel right.

**Comment by librelois** [comment]
From my understanding, the problem comes from the fact that the extension assumes that the runtime expects a signature of type `MultiSignature` (an enum), which is the type used by most blockchain substrate. But for moonbeam this is not the case, the signature type is not an enum, but directly `Signature = EthereumSignature`.
The polkadotjs app relies on the runtime metadata to know how to encode the signature, but this doesn't seem to be the case for the extension.

**Comment by jacogr** [comment]
Duplicate of #907 ?

**Comment by ekenigs** [comment]
Closing in favor of https://github.com/polkadot-js/extension/issues/907.
