### ISSUE TITLE
extension-dapp: add support for subscription to a specific extension

### ISSUE THREAD

**Issue by hamidra** [polkadot-js/extension#1062]
Currently, web3AccountsSubscribe subscribes to all account changes across all extensions.
Now that different wallet extensions are coming up with polkadot.js support it will be nice to have another method to let subscribe to account changes from a specific set of extensions.
for example, a method like web3ExtensionAccountsSubscribe(extensions, cb) which only subscribes to the changes from the specified extensions.

**Comment by jacogr** [comment]
Closed in #1063
