### ISSUE TITLE
Is there a public roadmap

### ISSUE THREAD

**Issue by in19farkt** [polkadot-js/extension#107]
Hello. Where could I see the roadmap for your extension?

Thank :)

**Comment by jacogr** [comment]
Everything is only managed in GitHub, so all the issues that are logged are what is being planned to be addressed atm. (Same with all other polkadot-js repos, as issues/features come up, they are logged and only tracked on here). 

The short version for the extension -

- As it stands it is deemed mostly feature-complete, i.e. the focus is on managing accounts and signing. (It is not a wallet with transfer functionality etc, there are dapps that fill this role quite nicely)
- The largest thing (enhancement-wise) outstanding . atm is the proper views and management, i.e. what sites you have given permissions to and management around that
- Most other enhancements will be on tightening up and keeping up-to-date with library changes

The other pick-ticket-item is the injection of a provider into dapps. (It will take some time and speaking to existing dapp devs, not critical at exactly this point in time)

**Comment by jacogr** [comment]
@in19farkt Anything specific that you were wondering about there? Or did the above answer your question?

**Comment by in19farkt** [comment]
@jacogr No more questions :) Thank.
