### ISSUE TITLE
Firefox Addons Release?

### ISSUE THREAD

**Issue by wilwade** [polkadot-js/extension#1071]
There are three closed issues that are all fixed in the current version of the extension, but the release https://addons.mozilla.org/en-US/firefox/addon/polkadot-js-extension/ is several months out of date. Any chance someone could trigger a release to FF Add-ons?

- https://github.com/polkadot-js/extension/issues/965
- https://github.com/polkadot-js/extension/issues/997
- https://github.com/polkadot-js/extension/issues/1013

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/extension/releases/tag/v0.44.1
