### ISSUE TITLE
No option to ignore authorization pop-ups 

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/extension#1086]
If i summon the authorization pop-up accidentally (or without intending to when dapps summon them upon loading), or I want to make a decision later after looking more into a dapp, there is no way to currently just dismiss the authorization. I have to either reject or accept it. If I just ignore the request & click outside the window, the annoying "Auth" label persists over the extension icon:

<img width="570" alt="Screenshot 2022-06-12 at 13 30 17" src="https://user-images.githubusercontent.com/13929023/173233307-6977f8ec-c16a-4d6f-a27b-136382ba5113.png">

Talisman have an "ignore for now" button. My hope for this issue it to include something similar that just dismisses the popup. Perhaps in the form of a "Decide Later" button next to "Reject".

Talisman UX for reference (bottom center of popup is the "ignore for now" button.

<img width="358" alt="Screenshot 2022-06-12 at 13 24 17" src="https://user-images.githubusercontent.com/13929023/173233253-d1ae30de-6275-46a6-903d-6bbf5d8172d1.png">

**Comment by jacogr** [comment]
This is not Talisman. If that product fits workflow better, please do stick to it - this is not a catch-all for everybody, experiences and expectations differ. This is a baseline and feature-complete signer, nothing more.

Alternatively, PRs welcome.

**Comment by rossbulat** [comment]
If i understand correctly, would this be merged if a PR was added?

**Comment by Tbaut** [comment]
This is actually addressed here https://github.com/polkadot-js/extension/pull/1068
If you select no account and click "connect" you'll effectively connect the extension, and not share any account. Or you can click "ask me later" which is equivalent to closing the popup. Reload the page and you'll see the popup again.

**Comment by rossbulat** [comment]
> This is actually addressed here #1068 (the video in the first post doesn't show this, I added this after) If you select no account and click "connect" you'll effectively connect the extension, and not share any account. Or you can click "ask me later" which is equivalent to closing the popup. Reload the page and you'll see the popup again.

I am not seeing any functionality of this nature in the authorize pop-up. The suggestion in my first post is to simply ignore / dismiss the pop-up without taking action.

**Comment by Tbaut** [comment]
Well, this is exactly what I'm talking about. The current "reject" function, has been replaced by as "ask me later." that closes the popup, remove the "auth" from the icon in the PR I mention.

**Comment by rossbulat** [comment]
Thank you for updating. I will follow your PR until it merges - quite a few big UI changes happening that may render this issue obsolete with the added functionality.
