### ISSUE TITLE
Almost everything fails with "inability to pay" on Acala when there is sufficient balance 

### ISSUE THREAD

**Issue by farleylai** [polkadot-js/extension#1087]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request (please bear the comments above in mind)
  - [ ] Other

After transferring DOT to Acala, signing the transactions for swap and liquid staking always fails with insufficient balance error:

> dex: swapWithExactSupply
1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

However, there is indeed sufficient balance in the screenshot for the swap transaction of a small amount:

![Screen Shot 2022-06-14 at 4 08 49 AM](https://user-images.githubusercontent.com/158540/173565792-f19d15d7-3b89-4b02-b36b-382676ab9e1f.png)

Another screenshot shows a similar error message when signing the transaction of liquid staking:

![Screen Shot 2022-06-14 at 4 24 42 AM](https://user-images.githubusercontent.com/158540/173566860-2654439e-87fc-409c-a2a4-0991e28ad5dc.png)

I made sure to select transaction fees by DOT.
Any ideas?

  - Environment: macOS 12.4
  - Chrome polkadot.js

**Comment by farleylai** [comment]
Strange, the transaction fee must select ACA for the transaction to fall back to charge DOT.
If selecting to pay by DOT, the transaction fails unexpectedly.

**Comment by Tbaut** [comment]
This is not related to the polkadot extension. Please get in touch with the Acala team.
