### ISSUE TITLE
Failed to unsubscribe extensions' accounts

### ISSUE THREAD

**Issue by JayJay1024** [polkadot-js/extension#1088]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request (please bear the comments above in mind)
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

```typescript
const polkadot = await window.injectedWeb3['polkadot-js'].enable("dapp mame");

  const unsub = await polkadot.accounts.subscribe((accs: any) => {
  console.log(accs.length);
});

setTimeout(() => {
  unsub();
}, 1000 * 10);
```

When unsubscribed, it is still subscribing. My environment can not use `web3AccountsSubscribe `.

  - Version: `0.43.1`

  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments available)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript
    - [ ] Other

**Comment by Tbaut** [comment]
This is a duplicate of https://github.com/polkadot-js/extension/issues/1017 and will be closed in https://github.com/polkadot-js/extension/pull/1067
