### ISSUE TITLE
Signing of transaction is not working on substrate UI

### ISSUE THREAD

**Issue by satyamakgec** [polkadot-js/extension#109]
I started playing with the polkadot.js extension in my chrome browser on my custom chain accessing through substrate UI, It gave me this error -
`t.signer.sign is not a function`. 
![Screen Shot 2019-07-29 at 4 30 59 PM](https://user-images.githubusercontent.com/14581509/62043927-4ef63780-b21f-11e9-88d1-63bc8e57dfe5.png)
It was a simple transaction to transfer the balance from an extension account to chain account. While the same transaction was easily performed by using Polkadot UI. Either the extension is not fully supportable on the substrate UI or something else.

**Comment by Tbaut** [comment]
Thanks for the issue. Did you tun this test with a substrate local node? I had this issue on a substrate node compiled a couple days ago, however things have changed since and it works well on node from yesterday (with the Firefox extension, the Chrome one is under review)

**Comment by jacogr** [comment]
The `substrate-ui` needs an update. (The extension explicitly removed the old signer interface instead of supporting both old and new, sadly the old substrate-ui deployment there does not have the latest api that caters for it.)

Will deploy a new version. (polkadot.js.org/apps is always current)

**Comment by jacogr** [comment]
Should be working on substrate-ui again, that got a bump yesterday. Tested a couple of txs to a local node.

(The above deployment has not 100% caught-up in terms of features for at least 2.x, but the polkadot-js/apps is rapidly changing for substrate 2.x support)
