### ISSUE TITLE
Error initializing polkadot-js: The source http://localhost:3001/ is not allowed to interact with this extension

### ISSUE THREAD

**Issue by kroim** [polkadot-js/extension#1095]
I closed all browsers and I opened again. 
I check this issue. https://github.com/polkadot-js/extension/issues/584
But, it's same error.
![image](https://user-images.githubusercontent.com/33049672/175367403-1c859ccb-883d-468f-9220-94f3fd29645c.png)

**Comment by jacogr** [comment]
You disallowed it, so it is expected.

In the extension: Settings (gear icon) -> Manage website access - click allow on the denied website.

**Comment by kroim** [comment]
Aha, thanks. 
That's perfect!

**Comment by kroim** [comment]
Is there a way to enable website in programmatically?

**Comment by jacogr** [comment]
Once the user has indicated that he/she is not interested, there is no way to override the intentions from the user from the dapp with code and/or continue spamming him/her with popups, i.e. click "no" ask again, and again... If they change their mind, they need to explicitly enable it.

**Comment by kroim** [comment]
I understand. thanks.
