### ISSUE TITLE
Next.Js ReferenceError: window is not defined

### ISSUE THREAD

**Issue by FedeC87p** [polkadot-js/extension#1101]
I have the same issue of https://github.com/polkadot-js/extension/issues/571

But for me the not working:

useEffect(async () => {
  const ed = await import('@polkadot/extension-dapp');
  ...
}, []);

![Error_NextJs](https://user-images.githubusercontent.com/58514549/177014674-88904c8f-0950-496d-8475-58336545861c.PNG)

![NextJs](https://user-images.githubusercontent.com/58514549/177014675-cd32f333-1e13-4e6d-af50-c3f4cca586a7.PNG)

How can I overcome this problem? Otherwise is it possible to fix it like those of Moralis did?

< MoralisProvider initializeOnMount={false} >
      < NotificationProvider >
        < Component {...pageProps} />
      </ NotificationProvider >
    < /MoralisProvider >

**Comment by jacogr** [comment]
Honestly, I have no idea. Truthfully never used or even tried Next.js - you will need to track down what that destroy is and why it occurs in the framework. 

I really have no idea how this framework manages the front-end vs back-end code, the `@polkadot/extension-dapp` was built to operate in a front-end context only, so it will need access to the browser to send/receive messages.

**Comment by FedeC87p** [comment]
Ok, in a few day I hope to have some time to investigate, I'll let you know if I find a solution.
