### ISSUE TITLE
Update extension utils with latest polkadot dependencies

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/extension#1113]
Since I updated to the latest polkadot libraries I experience these warnings :)

<img width="544" alt="Screenshot 2022-07-20 at 17 36 42" src="https://user-images.githubusercontent.com/22471030/180024514-bb657cec-849f-41f1-a8b5-8ff22ff7b09f.png">

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/extension/releases/tag/v0.44.2
