### ISSUE TITLE
Sporran wallet can't detect sometimes 

### ISSUE THREAD

**Issue by TopCodeBeast** [polkadot-js/extension#1131]
I'm using "@polkadot/extension-dapp": "^0.44.6".
I'm using Sporran(kilt) & Polkadot wallet.
Polkadot wallet is always can detect but Sporran wallet sometimes detect and sometimes not.

**Comment by jacogr** [comment]
What is Sporran wallet? Sorry, not sure how that registers, so cannot comment on their process. If everything was "flakey" it would point to an issue here.
