### ISSUE TITLE
Save prev selection for account approvals

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#1132]
Currently it is a bit of a "slog" to scroll down and select accounts of each authorization. It would be better to save the previous selection and supply that as the default.

(I think this is the only reason I have not released it to stores as of yet - it just feels a tiny bit cumbersome)

**Comment by Tbaut** [comment]
Sounds good, I'll take a look at it.

**Comment by jacogr** [comment]
Thank you.
