### ISSUE TITLE
Getting error while running yarn build

### ISSUE THREAD

**Issue by lhtYashMohan** [polkadot-js/extension#1136]
![image](https://user-images.githubusercontent.com/107236407/188112410-25de5e06-e32c-4ac3-8b12-dc6d22ceaa84.png)
This rollup command is not recognizing even i checked in node-modules this rollup file is existing
Any help would be thankful and  appreciated.

**Comment by jacogr** [comment]
Strange. Master is fine, both on CI (which does a full pull and install) and my machine - so both just check out what is there, no changes. This is the process -

- clone
- yarn install
- yarn build

If existing, maybe remove `node_modules` before step 2 above.

**Comment by lhtYashMohan** [comment]
I did the same thing but still showing same error i was trying on windows and when i tried it Linux system then it is throwing no error

**Comment by jacogr** [comment]
It is quite possible that there are some assumptions in the scripts (somewhere?) that assumed *nix environments. Sadly I only have access to Mac (my dev machines) and Linux (CI infrastructure), so Windows doesn't get tested or used in day-to-day from a dev perspective.
