### ISSUE TITLE
isWeb3Injected has wrong value on initial page load

### ISSUE THREAD

**Issue by nikitayutanov** [polkadot-js/extension#1144]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

On inital page load `isWeb3Injected` is `true` even before `web3Enable` call.
However after page reload it behaves normally - value is `false` before `web3Enable` and `true` after.

Basic code example:

```JSX
  useEffect(() => {
    console.log('ENABLE');
    web3Enable('App').then(...);
  }, []);

  useEffect(() => {
    console.log(isWeb3Injected);
    if (isWeb3Injected) web3AccountsSubscribe(...);
  }, [isWeb3Injected]);
```

* **What is the motivation for changing the behavior?**

`isWeb3Injected` should be `false` before `web3Enable` call on initial page load

* **Please tell us about your environment:**

  - Version: 105.0.5195.127
  - Environment: Google Chrome

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Code is as follow -

```js
// true when anything has been injected and is available
function web3IsInjected (): boolean {
  return Object.keys(win.injectedWeb3).length !== 0;
}

...

// have we found a properly constructed window.injectedWeb3
let isWeb3Injected = web3IsInjected();
```

This means that the keys are found on the window object, not that it has been enabled. (As soon as an extension is present and had decorated window announcing itself, it means that the `isInjected` is true)
