### ISSUE TITLE
Implement signRaw Signer interface

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#115]
It allows for signing of any data

**Comment by c410-f3r** [comment]
Any news about this feature? I am trying to implement myself but it doesn't seem so trivial

**Comment by jacogr** [comment]
Sorry, I really meant to reply earlier. (...this is what happens when you look at notifications on your phone, you miss responding on the desktop.)

Still to be done, work has not started. It needs -

- a hook in the signer interface for signRaw, https://github.com/polkadot-js/extension/blob/master/packages/extension/src/page/Signer.ts#L33
- A handler for the message to do the actual signing, https://github.com/polkadot-js/extension/blob/master/packages/extension/src/background/handlers/Extension.ts#L225
- queuing for those types of messages (or rather, just in the normal to-be-signed-queue), https://github.com/polkadot-js/extension/blob/master/packages/extension/src/background/handlers/State.ts#L28
- UI to display those differently, only the raw data, https://github.com/polkadot-js/extension/blob/master/packages/extension-ui/src/Popup/Signing/Request.tsx
