### ISSUE TITLE
ED25519 KeyPair Type support

### ISSUE THREAD

**Issue by PaTara43** [polkadot-js/extension#1150]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Current: All accounts created are of SR25519 Keypair Type https://wiki.polkadot.network/docs/learn-keys
Expected: Ability to choose Keypair type while creating the account. 

* **What is the motivation for changing the behavior?**

Current workaround - creating accounts on https://polkadot.js.org/apps/ and downloading their json backup, then importing in extension. Takes too long. Better tot be able to choose this type in the extension. This type needed to encrypt-decrypt information with account seeds.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [x] Other

**Comment by jacogr** [comment]
The extension is really meant to be simple - the amount of support that we have to deal with elsewhere since users have the ability to choose is not worth it here.
