### ISSUE TITLE
Release on Browser extension Store

### ISSUE THREAD

**Issue by sharma66mahesh** [polkadot-js/extension#1157]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
It's been quite a while since the last version of Polkadot.js was released on Browser extension store. The last release for Chrome was on July (v0.44.1). There have been many prod-releases since then, but have not been made available on the stores. I'm curious to know what's holding the team behind.

* **What is the motivation for changing the behavior?**
A lot of chains have been released since July and different chains use different address formats. It's creating confusion for users as they cannot see the wallet address in a particular format used by the chain.

**Comment by jacogr** [comment]
It has been asked recently, see https://github.com/polkadot-js/extension/issues/1148 (specifically my comment)

Getting closer, 1 must-have PR outstanding for Moonbeam support, but the current master changes are looking good code and testing wise.
