### ISSUE TITLE
The Polkadot JS extension is not signing with Ledger

### ISSUE THREAD

**Issue by eladiogalvez** [polkadot-js/extension#1164]
- [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

When try to sign a transaction to Transfer DOT to Moonbeam xcDOT the method is not supported:

<img width="564" alt="Captura de Pantalla 2022-11-01 a las 12 50 09" src="https://user-images.githubusercontent.com/22935476/199227653-101fb1b4-465b-43e6-bdbb-ef500e745dda.png">

  - Version: 0.44.1
  - Environment:
    - Google Chrome Versión 107.0.5304.87 (Build oficial) (x86_64)
    - Brave [Versión 1.45.116 Chromium: 107.0.5304.91 (Build oficial) (x86_64)]
    - macOS Monterey 12.5
    - Ledger Nano X 2.0.2  with app Polkadot (DOT) 15.9300.0.

    - [ ] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

**Comment by jacogr** [comment]
"Method not supported" is from the Ledger app itself. It means that it doesn't have support for that extrinsic.

**Comment by eladiogalvez** [comment]
I just opened an issue using option “Contact us” in the form:

https://support.polkadot.network/support/solutions/65000042295

**Comment by eladiogalvez** [comment]
Polkadot support team confirm that currently the solution is use a non ledger wallet or wait until polkadot ledger app add support, but depends on ledger disk limitations.

Also them include a link to an opened issue:

https://github.com/Zondax/ledger-polkadot/issues/157
