### ISSUE TITLE
Publish to deno.land

### ISSUE THREAD

**Issue by raoulmillais** [polkadot-js/extension#1169]
Do you have plans to also publish these packages to deno.land along with the rest of polkadotjs?  We would find that incredibly useful.  Currently `import`ing and using `@polkadot/extension-dapp` from https://esm.sh results in a "Too much recursion" error.  I'm digging into that but a "proper" deno release would be awesome.

**Comment by jacogr** [comment]
There are no such plans at all. 

`extension-dapp` is meant for browser usage only, not Node or Deno. (Same with everything in the `ui` or `apps` repos)

**Comment by raoulmillais** [comment]
Yeah makes sense.  I'm bundling with esbuild from deno but I actually got it working fiddling with the imports.
