### ISSUE TITLE
ChainId has many duplicates

### ISSUE THREAD

**Issue by zjb0807** [polkadot-js/extension#1178]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

<img width="388" alt="image" src="https://user-images.githubusercontent.com/16496415/205608845-2b16ea29-97e4-4a3d-8429-b3a3d9b37e59.png">

Each chain id should only have one option, and now there are many duplicates

* **What is the motivation for changing the behavior?**

Each chain id should only have one option

* **Please tell us about your environment:**

  - Version: 0.44.1
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by Tbaut** [comment]
This is a duplicate (of e.g https://github.com/polkadot-js/extension/issues/764), and not really a bug.
