### ISSUE TITLE
Error with @polkadot/extension-dapp - "window is not defined"

### ISSUE THREAD

**Issue by enfipy** [polkadot-js/extension#1179]
- [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

### **What is the current behavior and expected behavior?**

Currently, when you use `@polkadot/extension-dapp` with SSR - it fails on import with `window is not defined`.

Error code:
```
Code:
      47 | // just a helper (otherwise we cast all-over, so shorter and more readable)
    > 48 | const win = window; // don't clobber the existing object, but ensure non-undefined
         |             ^
      50 | win.injectedWeb3 = win.injectedWeb3 || {}; // true when anything has been injected and is available
```

Expected behavior: It should just work with import but fail on the run. It shouldn't just fail on import.

### **What is the motivation for changing the behavior?**

Can't even import the `@polkadot/extension-dapp` package while on nodejs environment. I'm using SSR from `astrojs` and it doesn't work with the current latest `@polkadot/extension-dapp`.

### **My environment:**

  - Environment: Node.js
  - Version: 16.16
  - Language: TypeScript (on any version)

**Comment by jacogr** [comment]
It is not meant to be used in any Node.js (or Deno) environment. It is purely browser-only.

**Comment by jacogr** [comment]
`import` means it is executing in a JS context. The JS engine would parse the file and perform any variable definitions or top-level global code contained in that file. In this case it means setting up the global variables that are needed between the dapp and extension injectors.

**Comment by enfipy** [comment]
@jacogr Can I create a PR and just fix it with several ifs around [these lines](https://github.com/polkadot-js/extension/blob/master/packages/extension-dapp/src/bundle.ts#L16)?

I still think that it shouldn't fail on just import as there're tons of frameworks like Nuxt/Next/SvelteKit/Astro (that can prerender Vue/React/Svelte components) and will fail on the import.
