### ISSUE TITLE
About syntax detection, jslint and tsc build config

### ISSUE THREAD

**Issue by qqqzhch** [polkadot-js/extension#1194]
About syntax  check, jslint and tsc build config
Recently, I made some changes to my wallet. After modifying the error message of jslint prompt, I started to build. I found that there was also syntax information that caused the package to fail,
I checked that it was caused by the configuration during the build of typesript

tsc --build tsconfig.build.json

I think such syntax  check should be same in development and build，Or include it in jslint instead of finding a lot of syntax errors when preparing to build

```
> tsc --build tsconfig.build.json&&polkadot-dev-run-lint

packages/extension-base/src/background/handlers/State.ts:15:1 - error TS6133: 'accountsObservable' is declared but its value is never read.

15 import { accounts as accountsObservable } from '@polkadot/ui-keyring/observable/accounts';
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/extension-base/src/background/handlers/State.ts:156:10 - error TS2564: Property 'API' has no initializer and is not definitely assigned in the constructor.

156   public API: ApiPromise;
```

  - [ ] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [x] Other

* **What is the current behavior and expected behavior?**
Syntax detection jslint should be the same when developing and building or  jslint

* **What is the motivation for changing the behavior?**
tsc --build tsconfig.build.json&&polkadot-dev-run-lint

* **Please tell us about your environment:**
node v16.13.1

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [x] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
eslint (specifically [typescript-eslint](https://typescript-eslint.io/)) doesn't have the same rules as [tsc](https://www.typescriptlang.org/). The one is a linter, the other a compiler. 

So it will always be [different](https://stackoverflow.com/questions/39831365/whats-the-difference-between-linting-and-compiling).

**Comment by qqqzhch** [comment]
```
 // eslint-disable-next-line @typescript-eslint/no-misused-promises
```
Sometimes the lint syntax check is bypassed with eslint-disable-next-line, but the tsc syntax check reports an error when it is built. 
The earlier the error is reported, the better
Now [tsc](https://www.typescriptlang.org/) syntax check is too late, it is done at build time, I think it should be put in the npm run lint, so that it can be done once before each code commit

**Comment by jacogr** [comment]
Read above. They are different things.

Where overrides are used, generally they should be removed - there are some very much edge cases where linting overrides are required.

**Comment by qqqzhch** [comment]
I am very sorry for not expressing the question clearly 
The expected typescript syntax detection is the same for dev and build.
Now it seems that build is stricter than dev.
This is my local way of handling it, and while it gets the typescript syntax detection error, But I think this may not be a very good approach
```
"lint": "tsc --build tsconfig.build.json&&polkadot-dev-run-lint"
```
