### ISSUE TITLE
Error - Window is not defined

### ISSUE THREAD

**Issue by insikdev** [polkadot-js/extension#1207]
find same issues about this error ( #1179 , #1101 ).

I can't build next.js proejct and can't refresh page in dev server, but found a solution using dynamic import.

This error is because window object is not defined in non-browser environments.

https://github.com/polkadot-js/extension/blob/895f6a7b99e925b7045681a9bbbb7f430a52440e/packages/extension-dapp/src/bundle.ts#L16

Using globlaThis instead of a window object did not cause the same error.

```
const win = globalThis as Window & InjectedWindow;
```

After the fix, the error no longer occurred in my environment. ( next.js 13.1.6 )

**Comment by jacogr** [comment]
The error is correct - the code is meant to fully execute in a browser environment, not on a server.

**Comment by yashirooooo** [comment]
> The error is correct - the code is meant to fully execute in a browser environment, not on a server.

I am running in react environment. but also reported such an error

**Comment by jacogr** [comment]
Any browser has "browser" defined.

1. Open a new browser windo
2. Open the console
3. type `console.log(window)`

The output would be similar to this -

![image](https://user-images.githubusercontent.com/1424473/217449185-f48cb45a-d690-44cb-a6c9-a485c5470258.png)

This means that if you get this error, your script is not executing in the browser context. In that case, it won't work - `@polkadot/extension-dapp` interrogates the window object to determine what is injected.
