### ISSUE TITLE
polkadot-js extension update timeline

### ISSUE THREAD

**Issue by jpangelle** [polkadot-js/extension#1208]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

We need support for signing a raw transaction with a QR wallet for authenticating users on our app at [Centrifuge](https://github.com/centrifuge/apps). It looks like the [code](https://github.com/polkadot-js/extension/pull/1155) for this fix was included in the [v0.44.7](https://github.com/polkadot-js/extension/releases/tag/v0.44.7) release, however, the Chrome [polkadot-js](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd) extension has not been updated since June 2022. When can we expect the extension to be updated?

**Comment by jacogr** [comment]
It has been on the radar for a release since the start of the year - if I do free up enough time for the release process, there will be one made.

**Comment by jacogr** [comment]
Closing, answered. (And yes, I need to _get_ to it)
