### ISSUE TITLE
the popup url was different from the website url

### ISSUE THREAD

**Issue by jasonintju** [polkadot-js/extension#1211]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
  *current behavior:* the url in the extension popup was different with the website url when AuthorizeReq or SigningReq or otherReq
  *expected behavior:* they should be same at any time, in any page

   ![image](https://user-images.githubusercontent.com/14125115/218989754-185c4495-b33d-4c13-9342-5476ad104576.png)
  
  I recorded a video(https://youtu.be/rC1kklIgiNY) to tell the details.
  - step1: load website with url http://localhost:3000/page1
  - step2: connect the wallet, the url in the popup was http://localhost:3000/page1 too, same url, it's ok
  - step3: route to page2, the website url changed to http://localhost:3000/page2
  - step4: at now, connect the wallet, the url in the popup was still http://localhost:3000/page1, **wrong url, it should be 'page2'**
  - step5: if we reload page2, and continue testing, we will find that page2 is ok, but when routed to page1, problem reproduced

  It seems that the wallet only remembered the website url when loading page, after that, the url was keep unchanged, which is incorrect. The url in the popup should be same with the website url at anytime, in any page.
  
  And I also tested https://kusama.polkassembly.io/ and https://polkadot.js.org/apps/#/accounts, they both have the same problem.

  By the way, the demo repository was here https://github.com/jasonintju/test-polkadot-ext-popup-url

* **Please tell us about your environment:**

  - Version: 0.44.8
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Closing, question answered.
