### ISSUE TITLE
Error while teleporting

### ISSUE THREAD

**Issue by Nick-1979** [polkadot-js/extension#1214]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

   When I click on teleport to sign the transaction with the extension, I see the error shown in the attached screenshot

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)
    
![Screenshot (44)](https://user-images.githubusercontent.com/46442452/220591212-ccd874bf-fb27-4a53-967d-01f9610b1726.png)

**Comment by jacogr** [comment]
the above seems to not be from the polkadot-js extension. Closing, needs to be addressed elsewhere, certainly not here which is the polkadot-js extension. 

(Could possibly be related to the V3 updates as logged in apps)
