### ISSUE TITLE
Export account

### ISSUE THREAD

**Issue by JonasPf** [polkadot-js/extension#122]
Hi,

Is there a way to export an account? I'm fine with pulling it out of a db or using an API if it is not possible via the UI.

**Comment by jacogr** [comment]
Not yet, will keep this issue open to add that functionality. You can get to that info using https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb which can inspect the `chrome.storage.local` area.

- navigate to chrome extensions
- view extension background page
- with the extension installed, to to the storage
- the `value` field for the accounts in the encrypted JOSN (i.e. can be imported into e.g. the polkadot-js/apps UI)

**Comment by JonasPf** [comment]
Any tips for Firefox? I got as far as this:

1. Opened `about:debugging`
2. Check `Enable add-on debugging`
3. Click `Debug` next to the extension
4. There seems to be a chrome thing in "Indexed DB"

**Comment by jacogr** [comment]
Closed in #166 (Will be in the 0.13 release)
