### ISSUE TITLE
Vara Network duplicates

### ISSUE THREAD

**Issue by EugenWay** [polkadot-js/extension#1239]
Hello guys.

The Vara Network.
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.vara-network.io

While we were on the testnet, we restarted the network several times and I think it was determined in Polkadot extension as new by genesis. 

Now we have launched the main chain candidate. And can we clean up the garbage networks?
The actual genis hash is 0xfe1b4c55fd4d668101126434206571a7838a8b6b93a6d1b95d607e78e6c53763

<img width="648" alt="Снимок экрана 2023-03-24 в 09 56 01" src="https://user-images.githubusercontent.com/5233530/227471958-e444bee6-9c10-4ca5-88e8-c4ec7861a97d.png">

**Comment by Tbaut** [comment]
This issue is also a duplicate :) Check this answer: https://github.com/polkadot-js/extension/issues/1127
