### ISSUE TITLE
Uncaught Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33  

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/extension#1250]
* **I'm submitting a ...**
  - [X] Bug report
  - [ ] Feature request
  - [X] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

If I go to https://app.zeitgeist.pm/, using the latest Polkadot.js Extension version 0.44.1, and using the latest Brave browser version 1.50.119 Chromium: 112.0.5615.121 (Official Build) (x86_64).

It displays the following error in the DevTools console:

<img width="869" alt="Screen Shot 2023-04-16 at 9 54 59 am" src="https://user-images.githubusercontent.com/6226175/232258951-e4586f4f-8fe7-4129-af9d-7ae9536c4e9c.png">

Clicking the error messages shows that it's related to the Polkadot.js Extension

<img width="558" alt="Screen Shot 2023-04-16 at 10 01 49 am" src="https://user-images.githubusercontent.com/6226175/232259163-be7be875-0a5b-4117-82a4-995f3dd15357.png">

<img width="539" alt="Screen Shot 2023-04-16 at 10 02 01 am" src="https://user-images.githubusercontent.com/6226175/232259164-c239b231-adec-4022-859a-5de3f6ae1555.png">

So if i try clicking "Connect" and selecting "Polkadot.js Extension" to connect my wallet it doesn't work.
In the past I have been able to connect my wallet this way without any issues. 

Note that I have authorised the website to connect to Polkadot.js Extension already:

<img width="546" alt="Screen Shot 2023-04-16 at 10 16 12 am" src="https://user-images.githubusercontent.com/6226175/232259531-228c816c-bafa-46ab-bab1-c30e2abfd0e9.png">

Additionally, if i go to https://singular.app/, using the same version of Polkadot.js Extension and Brave version.

It displays the following error in the DevTools console:

<img width="628" alt="Screen Shot 2023-04-16 at 9 48 25 am" src="https://user-images.githubusercontent.com/6226175/232258837-6cad61c3-2fc0-4bc2-8396-e0b89d4831da.png">

Clicking the error messages shows that it's related to the Polkadot.js Extension

<img width="587" alt="Screen Shot 2023-04-16 at 10 03 28 am" src="https://user-images.githubusercontent.com/6226175/232259197-1f3dec16-dcc9-4cf0-8803-c93a8bdc0978.png">
<img width="550" alt="Screen Shot 2023-04-16 at 10 03 17 am" src="https://user-images.githubusercontent.com/6226175/232259201-4ee0214f-9a33-4e3c-92a8-f713dd75a1fa.png">

Then when I click to "Connect" and choose "Select account" to choose a wallet using the Polkadot.js Extension, it then shows a modal indicating that I don't have any accounts, even though I do.
In the past I have been able to connect my wallet this way without any issues.

<img width="531" alt="Screen Shot 2023-04-16 at 9 48 39 am" src="https://user-images.githubusercontent.com/6226175/232258878-e2a969ec-152e-4dea-90cf-d53f209da8f7.png">
 
* **What is the motivation for changing the behavior?**

I'm an end-user of these Substrate-based chains. Seeing a similar error across more than one of them made report it here incase its a bug report or support request that could help more than one chain.

* **Please tell us about your environment:**

  - Version: 0.44.1
  - Environment:

    - [ ] Node.js
    - [X] Browser - Brave browser version 1.50.119 Chromium: 112.0.5615.121 (Official Build) (x86_64)
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [X] Other
          N/A

**Comment by jacogr** [comment]
Does it inject and display the accounts on the apps UI? (There are additional filters that dapps need to apply for Ethereum-like accounts - the extension only supplies the accounts, the dapp needs to filter based on chain type)

**Comment by jacogr** [comment]
Verified - it is related to the actual dapps, not the extension. Can re-create the issue on the specified dapps with Ethereum accounts.

I would suggest raising the issue there.

**Comment by ltfschoen** [comment]
> Does it inject and display the accounts on the apps UI? (There are additional filters that dapps need to apply for Ethereum-like accounts - the extension only supplies the accounts, the dapp needs to filter based on chain type)

yes for example with Zeitgeist it already shows all my balances successfully in the apps UI. however i did notice that i hadn't updated my metadata

<img width="1158" alt="Screen Shot 2023-04-16 at 5 33 17 pm" src="https://user-images.githubusercontent.com/6226175/232280794-cd332222-a941-43a4-94ae-e512adde71e2.png">

so i did that as shown below, but it still showed the same error in the Zeitgeist and RMRK dapps

![Uploading Screen Shot 2023-04-16 at 5.33.53 pm.png…]()

**Comment by jacogr** [comment]
Like I said above - it is in the account handling for the specific dapps. You need to log the issue there. (Ethereum-accounts are non-32-bytes in length, so when injected by the extension it cannot be handled there)

**Comment by Tbaut** [comment]
Note that the pjs exension also allows EVM accounts when imported through json afair. The solution is indeed on the dapp side, and is actually not related to the extension, but rather the functions such as `encodeAddress` or `decodeAddress` from `@polkadot/util-crypto` that must be wrapped into a try/catch.
