### ISSUE TITLE
Timeline for the release of the extension with message signing support for QR accounts?

### ISSUE THREAD

**Issue by ntn-x2** [polkadot-js/extension#1253]
Question in the title. I saw [this PR](https://github.com/polkadot-js/extension/pull/1155) was merged a while ago, but as of today the extension still does not allow cold wallets to sign messages, a screenshot is attached.

Thanks!

<img width="560" alt="Screenshot 2023-04-24 at 12 53 56" src="https://user-images.githubusercontent.com/6704504/234077301-1fff9fd8-62b6-44c6-83ee-b9109636783c.png">

**Comment by TarikGul** [comment]
Closing as https://github.com/polkadot-js/extension/pull/1155 is included now in the store releases
