### ISSUE TITLE
Raw signing with polkadot.js and parity signer is not possible due to outdated polkadot.js extension version in Chrome and Firefox stores

### ISSUE THREAD

**Issue by nud3l** [polkadot-js/extension#1268]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Judging from https://github.com/paritytech/parity-signer/pull/1332 and https://github.com/polkadot-js/extension/pull/1155, I was expecting that I can sign raw data using accounts in the parity signer via polkadot.js. 

However, when I try to sign raw data, I get "Raw data signing not supported for QR wallets" error:

![image](https://github.com/polkadot-js/extension/assets/14966470/b493efb8-3325-48e4-8fa5-f9bd9d6c1998)

When injecting the same account with the parity signer companion extension, I can sign raw data.

* **What is the motivation for changing the behavior?**

Polkadot.js extension and the signer companion should behave the same.

* **Please tell us about your environment:**

  - Version: 0.44.1
  - Environment:

    - [ ] Node.js
    - [x] Browser: Firefox
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by nud3l** [comment]
I'm thinking it might be related that the versions in the firefox and chrome store `0.44.1` are older than the version in which the fix #1155 is included?

**Comment by jpangelle** [comment]
FYI, this is also creating an issue for Talisman too since they use the polkadot extension logic:

> Currently Talisman inherits its signing logic directly from the polkadot.js extension.

[Source](https://github.com/TalismanSociety/talisman/issues/924#issuecomment-1635198266)

**Comment by bkchr** [comment]
@jacogr would it be possible to get a release out?

**Comment by FlorianFranzen** [comment]
@bkchr There has not been no new release in over 2 years! Could we please do something about it? (see #1291 for discussion)

**Comment by kianenigma** [comment]
any updates on this? Quite a blocker for many ppl it seems. 

In the short term, @Tbaut has told me the only way so to build a custom version of the extension. Do you have the code for that in a fork that we can use?

**Comment by Tbaut** [comment]
If you build master [following these instructions](https://github.com/polkadot-js/extension?tab=readme-ov-file#development-version), you'll be able to run the latest version of the extension and benefit from the features that have been added in the past years.

**Comment by bkchr** [comment]
We don't have access to the chrome nor firefox stores. I'm on it, but maybe we need to bite the bullet and create a new extension.

**Comment by ggwpez** [comment]
I think Talisman + Parity Signer can sign raw data.

**Comment by TarikGul** [comment]
> We don't have access to the chrome nor firefox stores. I'm on it, but maybe we need to bite the bullet and create a new extension.

I like the idea of us having a backup plan. Maybe we can decide a hard date where if we don't get access by then we can start the transition to a new release under a different extension with a migration guide.

**Comment by IkerAlus** [comment]
This should be already fixed for Chrome version and (hopefully) also solved for Firefox version in the next days

**Comment by kianenigma** [comment]
Yeah, confirming that I have the new version on chrome now ✅
