### ISSUE TITLE
Mozilla Add-On store received last release over 3 years ago

### ISSUE THREAD

**Issue by FlorianFranzen** [polkadot-js/extension#1291]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

  - Latest version to be published to the store according to release notes: [v0.48.2](https://github.com/polkadot-js/extension/releases/tag/v0.48.2)

  - Latest version on Mozilla Add-On store: [v0.41.1](https://addons.mozilla.org/en-US/firefox/addon/polkadot-js-extension/versions/)

**Comment by ltfschoen** [comment]
This is really bad. Now I know why most of the features like not being able to filter what accounts to connect to a dApp isn't available. I will use the development version in future.

**Comment by wirednkod** [comment]
cc @TarikGul

**Comment by TarikGul** [comment]
As to why there hasn't been a store release in the past this comment can shed some light https://github.com/polkadot-js/extension/issues/1283#issuecomment-1696891087. 

We do intend on releasing once we get the credentials for the store - that being said I would like to make sure the above is also in line with the release.

**Comment by Tbaut** [comment]
I think pushing a release when the credentials are available is sensible though. Waiting to add more potential features with their potential related issues will only push back the release date for no good reason IMHO. The mentioned missing features aren't available in the current version in any case.

Releasing often, with baby steps, and act upon feedback, is I think the safest. There are ppl today that have been annoyed for many years for features that do exist in master. What we are about to do with giant steps is actually dangerous in terms of support issues and user feedback. Would the release process take hours.. Why not, but it's not the case.

**Comment by FlorianFranzen** [comment]
Congratulations, Mozilla now official tracks the latest update with 3 years.

**Comment by TarikGul** [comment]
@FlorianFranzen We are finalizing our plans to get these released in the next month (we have no choice but to get it resolved this month) - depending on if we get the credentials it will either a) be released under the same extension or b) we will create a new extension - along with migrations and export/import guides. 

> Congratulations, Mozilla now official tracks the latest update with 3 years.

I understand your sentiment, but let's keep things professional and constructive.

**Comment by FlorianFranzen** [comment]
> I understand your sentiment, but let's keep things professional and constructive.

I really doubt you do as some people might consider not updating the official wallet for the only popular and privacy preserving browser unprofessional by itself. 

And this is only the peak of Parity's inability to have proper version and release management. You are creating and endless amount of unnecessary work for hundred of developers and are completely unapologetic about it. 

Not to mention that I have been asking for this issue to get the proper attention for longer then you can imagine. Now we reached the point were the with the latest runtime update you will no longer be able to sign anything in Firefox.

And if you do not take my word for it, just go through the issue tracker and see how many of the issues here all relate to the fact that the extension is outdated. This is a major issue for thousand of users!

Lastly, talking about professionalism: If Parity does not have access to the Mozilla account, who does? Was this just a supply channel attack waiting to happen?

**Comment by bkchr** [comment]
@FlorianFranzen maybe you could come over more nicely than this. You for sure know the history of the project and it was never a real parity project. We don't need to go into details here.

Nevertheless, I can tell you that there will be an update to the extension in the next two weeks.

**Comment by TarikGul** [comment]
@FlorianFranzen Update

The chrome store passed review and was released with `v0.47.5` - we published to the firefox store at the same time, and its still pending review. In the meantime we have added ways to manually install the same release to your browser via a signed `xpi` file. 

The notes are in the [`v0.47.5 release`](https://github.com/polkadot-js/extension/releases/tag/v0.47.5)

**Comment by FlorianFranzen** [comment]
@TarikGul Truely amazing, well done. After the multiple attempts I have gone through in the past, I can only imagine would it must have taken. Thank you!

**Comment by KarimJedda** [comment]
The extension will be reviewed tomorrow. Fingers crossed everything goes smoothly that way people can get it directly from the Firefox Addons store. :crossed_fingers: 

![Screenshot from 2024-06-16 14-16-20](https://github.com/polkadot-js/extension/assets/5029053/32048004-5728-4170-b982-f0c931c7904f)

**Comment by TarikGul** [comment]
I can happily say the Firefox store has finally approved our submission and has updated the extension to the most recent version! Thank you to all involved. Finally closing 🙏
