### ISSUE TITLE
Error reported when executing the Yarn build command

### ISSUE THREAD

**Issue by jackchen0120** [polkadot-js/extension#1294]
win10 system
node v18.15.0
yarn 3.2.0

Error message as shown in the figure
![image](https://github.com/polkadot-js/extension/assets/16026399/4f29fc2a-3cf2-4ba2-a12f-268fa26dc421)

**Comment by jackchen0120** [comment]
Continue executing the Yarn start command
Error message as shown in the figure
![image](https://github.com/polkadot-js/extension/assets/16026399/1e5fd561-4a3d-49bf-8a4e-7884b013cca9)

**Comment by jacogr** [comment]
For the first issue, I really don't have the setup to test on Windows. So no idea if it is working and it certainly has not been tested and cannot be - CI build is fine (Linux) as is my local (Mac) builds. Sadly have no way to reproduce above, so it would remain an issue (basically forever). 

(The root probably lies in the https://github.com/polkadot-js/dev repo where we always assume unix-like environments, there are no Windows-like support for paths and the like)

For the `yarn watch`, that seems to be dangling commands that are still there and should have been removed a while ago (when the config was removed). The linked PR removes those commands completely.

**Comment by jackchen0120** [comment]
> For the first issue, I really don't have the setup to test on Windows. So no idea if it is working and it certainly has not been tested and cannot be - CI build is fine (Linux) as is my local (Mac) builds. Sadly have no way to reproduce above, so it would remain an issue (basically forever).
> 
> (The root probably lies in the https://github.com/polkadot-js/dev repo where we always assume unix-like environments, there are no Windows-like support for paths and the like)
> 
> For the `yarn watch`, that seems to be dangling commands that are still there and should have been removed a while ago (when the config was removed). The linked PR removes those commands completely.

Thanks
