### ISSUE TITLE
Does the TAO wallet work with Nano Ledger via Polkadot JS wallet?

### ISSUE THREAD

**Issue by Ruudh1978** [polkadot-js/extension#1297]
I created a polkadot wallet with my nano ledger s. I connected the bittensor wallet to my Polkadot JS nano wallet, but now it tells me when I want to send or stake TAO...There is no known Ledger app available for this chain. The TAO seems to be locked in the wallet now. Which options do I have? 
Thanks

**Comment by Kl1nt1nMOd** [comment]
@Ruudh1978 Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID 67KO17A by clicking the link below

You can reach our support team via [Live Support](https://exploreonsite.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by Ruudh1978** [comment]
Can someone tell me if this is a fishing link or not?
