### ISSUE TITLE
Error Occurs When Running `Yarn test` Command

### ISSUE THREAD

**Issue by AMIRKHANEF** [polkadot-js/extension#1301]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Encountered an issue where executing the `Yarn test` command results in an error.

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
It works on CI. See the last PR merged - https://github.com/polkadot-js/extension/pull/1302
