### ISSUE TITLE
Manifest version 2 to be deprecated for chrome in sometime after June 2024

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/extension#1316]
Currently the manifest version is using v2, this is problematic since v2 will be deprecated come some time after June 2024 for the stable versions of Chrome. This can be seen here: https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline

This entails a few things:

1. We need to migrate to v3 for the manifest version.
2. Updates to the store will need to be made.

**Comment by Tbaut** [comment]
Linking https://github.com/polkadot-js/extension/issues/310 which was more or less the same. The discussions there may be of interest

**Comment by TarikGul** [comment]
> Linking #310 which was more or less the same. The discussions there may be of interest

Ahh thanks for linking that. That really helps!

**Comment by TarikGul** [comment]
Picking up this issue now that it is becoming urgent to!
