### ISSUE TITLE
Unable to hide/show visibility of accounts in bulk 

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/extension#1332]
- [ ] Bug report
  - [X] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I can't quickly hide or show ALL my multiple accounts within Polkadot.js with one click.

I want to just be able to quickly hide or show ALL the accounts that have been imported within the Polkadot.js Extension in one click.

* **What is the motivation for changing the behavior?**

At the moment, if I want to play an on-chain game and toggle between only 20 accounts, if I have say 1000 of accounts imported into the Polkadot.js Extension and they are all visible, I have to manually hide 980 accounts by manually clicking the hide icon, or write a script or similar, or export all accounts and modify the JSON file to only import those 20 accounts.

* **Please tell us about your environment:**

  - Version: macOS 14.1.1
  - Environment:
    - [X] Browser

**Comment by ltfschoen** [comment]
Oh I just discovered this issue https://github.com/polkadot-js/extension/issues/1291, which explains why I couldn't access the features that @Tbaut mentioned were already available when I asked about it at sub0 in Lisbon last year, to his surprise that I wasn't aware that the features had already been added.

I've been a long-term user since its inception and always thought the latest Github version was available in production, but I was so wrong.

I had no idea that the latest version already had an "Account connection request" page with checkboxes that allowed you to choose what accounts to connect to a dApp, I was about to add that feature myself but it's already been done, just hasn't been pushed to production.

So I've been using 0.41.1 instead of the latest 0.45.3, thinking 0.41.1 had all the latest features, but that version is over 2 years old as it was released in Nov 8, 2021, and there's a backlog of outstanding PRs in this repo.

Shouldn't this repo be archived? I'm tempted to just fork it and work on my own version of it if it's no longer being maintained and I don't have access to maintain it myself

**Comment by Tbaut** [comment]
It'll be published soon, now that another team took over. It's long overdue :)

**Comment by TarikGul** [comment]
@ltfschoen Here is the [forum post](https://forum.polkadot.network/t/polkadot-js-moving-forward/6235/25) discussing the future of PJS if you haven't seen it yet. A new release is definitely on the horizon. A few kinks just need to be worked out soon :)

**Comment by TarikGul** [comment]
Closing as the extension now has a normal release cycle and the following should all be contained in the available versions in the stores.
