### ISSUE TITLE
Wrong version in .nvmrc file

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/extension#1337]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

If I run `nvm install` it installs Node.js version 16.x since the current .nvmrc contents is still incorrectly `16` and it outputs the following error:

```
Usage Error: This tool requires a Node version compatible with >=18.12.0 (got 16.20.2). Upgrade Node, or set `YARN_IGNORE_NODE=1` in your environment.
```

The required Node.js version should be specified in the .nvmrc file. At the moment the required version in the package.json file specifies that the version required is `">=18.14"` but that's inconsistent with the .nvmrc file that says to install version 16.

If I change the value in the .nvmrc file to `lts/*` then when I run `nvm use` it installs Node.js v20.11.1 and `yarn cache clean && yarn` then run `yarn build` the build fails with the following errors:

```
 yarn build
$ polkadot-dev-build-ts
$ yarn polkadot-dev-clean-build
$ polkadot-dev-clean-build
$ yarn build:before
$ yarn polkadot-exec-tsc --build tsconfig.build.json
$ tsc --build tsconfig.build.json
packages/extension-ui/src/components/Address.spec.tsx:133:9 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: PolymorphicComponentProps<"web", Substitute<Props, Props>, void, void, {}, {}>): Element', gave the following error.
    Type 'string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | (AnyFn & ... 2 more ... & Omit<...>) | null' is not assignable to type 'ReactNode'.
      Type 'AnyFn & { mock: { calls: { arguments: unknown[]; }[]; mockImplementation: (fn: AnyFn) => void; mockImplementationOnce: (fn: AnyFn) => void; resetCalls: () => void; restore: () => void; }; } & Omit<...> & Omit<...>' is not assignable to type 'ReactNode'.
  Overload 2 of 2, '(props: Substitute<Props, Props>): ReactNode', gave the following error.
    Type 'string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | (AnyFn & ... 2 more ... & Omit<...>) | null' is not assignable to type 'ReactNode'.

133         actions={actions}
            ~~~~~~~

  packages/extension-ui/src/components/Address.tsx:31:3
    31   actions?: React.ReactNode;
         ~~~~~~~
    The expected type comes from property 'actions' which is declared here on type 'IntrinsicAttributes & FastOmit<Substitute<Substitute<Props, Props>, FastOmit<{}, never>>, keyof ExecutionProps> & FastOmit<...> & { ...; }'
  packages/extension-ui/src/components/Address.tsx:31:3
    31   actions?: React.ReactNode;
         ~~~~~~~
    The expected type comes from property 'actions' which is declared here on type 'IntrinsicAttributes & FastOmit<Props, keyof Props> & Props'


Found 1 error.
```

It seems to be due to styled-components and it may be necessary to use a previous version

* **What is the motivation for changing the behavior?**

So the community can contribute without encountering errors

* **Please tell us about your environment:**

  - Version: macOS 14.1.1
  - Environment:

    - [X] Node.js - any version necessary
    - [ ] Browser
    - [ ] Other (limited support for other environments)

**Comment by TarikGul** [comment]
PR is up to fix this. Setting it to 18.14 seems reasonable to me. I'll look into the `lts` issue serperately.

**Comment by TarikGul** [comment]
In terms of the use of `lts/*` I wasn't able to reproduce the issue. Using `20.11.1`, and clearing the cache the build successfully ran.
