### ISSUE TITLE
Target Audience and Naming Adjustment / Hint to Users

### ISSUE THREAD

**Issue by loanMaster** [polkadot-js/extension#1352]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Currently, the extension is available as the polkadot{.js} extension in the Chrome Web Store. New Polkadot users often download the extension expecting a Polkadot wallet and are surprised to find that the "wallet" does not offer the convenience they expect.

This issue was raised by a Discord moderator and was discussed in the "Polkadot Strategy" Telegram group. 

Ideally, newcomers to Polkadot should not install this extension because it is designed for developers and power users.

Therefore, it would be beneficial to adjust the name of the extension in the Chrome Web Store to "polkadot{.js} developer extension".

Alternatively, it would be helpful to display a message in the user interface when starting the extension: "This wallet is specifically intended for developers building on Polkadot. For a non-developer wallet, consider using Talisman or Subwallet."

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
Rel: https://github.com/polkadot-js/extension/issues/1413

Going to close in favor of the linked issue.
