### ISSUE TITLE
Forget Site is missing in Firefox extension but visible in chrome

### ISSUE THREAD

**Issue by niklasp** [polkadot-js/extension#1361]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Forget Site (trash icon ) is missing in Firefox extension but visible in chrome, see screenshots

<img width="538" alt="Bildschirmfoto 2024-05-22 um 12 56 49" src="https://github.com/polkadot-js/extension/assets/1685139/38e3a226-dd6a-4b0e-b54d-68ed194cedcb"> (Chrome)
<img width="555" alt="Bildschirmfoto 2024-05-22 um 12 56 36" src="https://github.com/polkadot-js/extension/assets/1685139/5778a62a-e4c3-4583-9467-f7f17687ec8f"> (Firefox)

* **What is the motivation for changing the behavior?**

I expect it to be visible

* **Please tell us about your environment:**

  - Version: 0.41.1
  - Environment: MacOs 13.3.1 (a) (22E772610a), FireFox Developer Edition 127.0b4 (64-Bit)

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
Thanks for bringing this up, I'll see if it's a simple fix today

**Comment by Tbaut** [comment]
I'm using Firefox, and it's definitely there. What version are you using?

**Comment by Tbaut** [comment]
Sorry, I saw you're using a developer version. I don't see why this would suddenly break in a dev version, but all I can say is that it works in the currently latest Firefox version, and has always worked so far.. so that may be fixed in the release.

**Comment by niklasp** [comment]
I installed fresh FF and it's the same issue for me:

<img width="1624" alt="Bildschirmfoto 2024-05-23 um 12 46 21" src="https://github.com/polkadot-js/extension/assets/1685139/199caec2-db0b-4434-a7c9-4626f9de3c47">

<img width="842" alt="Bildschirmfoto 2024-05-23 um 12 46 30" src="https://github.com/polkadot-js/extension/assets/1685139/db48d072-ef5b-4ffe-9426-def04304cd0c">

**Comment by Tbaut** [comment]
Thanks for the report, this sounds like it could be specific to mac. I'm on linux using 126.0
I really wonder why this is happening. This is where it's defined, and it looks like how others are defined: https://github.com/polkadot-js/extension/blob/80169c3cda0a96009d11f47d805a5e609a72dddb/packages/extension-ui/src/components/RemoveAuth.tsx#L4

Can one of you please try the following:
- click in the Settings > Open extension in a new windows
- from there open the console Option + ⌘ + J 
- navigate to Settings> Manage website access 

show a screenshot of the console.

**Comment by niklasp** [comment]
> Thanks for the report, this sounds like it could be specific to mac. I'm on linux using 126.0 I really wonder why this is happening. This is where it's defined, and it looks like how others are defined:
> 
> https://github.com/polkadot-js/extension/blob/80169c3cda0a96009d11f47d805a5e609a72dddb/packages/extension-ui/src/components/RemoveAuth.tsx#L4
> 
> Can one of you please try the following:
> 
>     * click in the Settings > Open extension in a new windows
> 
>     * from there open the console Option + ⌘ + J
> 
>     * navigate to Settings> Manage website access
> 
> 
> show a screenshot of the console.

<img width="1624" alt="Bildschirmfoto 2024-05-23 um 22 00 51" src="https://github.com/polkadot-js/extension/assets/1685139/0436933e-209b-4a81-8951-7393691c52b1">

nothing there

**Comment by niklasp** [comment]
Well i think it is probably related to the extension version I got from the Firefox store which is:     0.41.1 from 2021

https://addons.mozilla.org/de/firefox/addon/polkadot-js-extension/

maybe that is the bug?

**Comment by Tbaut** [comment]
> So the question is why is it that old?

This is another topic, TL;DR is that the current maintainers of the extension don't have access to the store, yet. cf https://github.com/polkadot-js/extension/issues/1268#issuecomment-2040752839

if you could try with the released version @TarikGul that'd be great.

No error in the console, and other icons working don't help giving me a clue unfortunately :|

**Comment by TarikGul** [comment]
<img width="551" alt="Screenshot 2024-07-08 at 11 24 35 AM" src="https://github.com/polkadot-js/extension/assets/47201679/dbd08bee-c956-416d-8e8f-74964d1391a5">

We finally got the latest version released to the firefox store 🎆 , closing as this is now resolved.
