### ISSUE TITLE
Transaction not broadcasting on bli0ckchain

### ISSUE THREAD

**Issue by shariquearshad** [polkadot-js/extension#1365]
Currently, we are integrating the Polkadot.js extension (https://polkadot.js.org/extension/) for swaps related to Polkadot. However, when sending a transaction, it doesn't seem to be getting broadcasted as I'm receiving status.isInBlock as false.

here is the code snippet

 const wsProvider = new WsProvider('wss://rpc.polkadot.io');
        const api = await ApiPromise.create({ provider: wsProvider });
        const allInjected = await web3Enable('my cool dapp');
        const allAccounts = await web3Accounts();
        // api.setSigner(allInjected[0].signer)
        let 
        const SENDER = '15iXHTv3akcJDNAc4HddWUuWxBLK55vSQiN98m6xcUemqfWg';
        const reciever='15iBCDWRVBmqpVGh4JekqSekFyegpV2EXFXUoS6S4d73BVN6'
        // const transferExtrinsic = api.tx.balances.forceTransfer(reciever,1)
        const injector = await web3FromSource(allAccounts[0].meta.source);
        const unsub = await api.tx.balances
        .transferAllowDeath(reciever,bnToBn(1) )
        .signAndSend(SENDER,{ signer: injector.signer }, (result: any) => {
          (result)
          const isInBlock = result?.status?.isInBlock
          if (!isInBlock) return
          const errorEvent = result?.events.find(
            ({ event: { method } }: any) => method === 'ExtrinsicFailed',
          )
          if (isInBlock && errorEvent) {
            // Reject if ExtrinsicFailed event was found
            console.log("rejected")
          } else if (isInBlock) {
            // Otherwise resolve succesfully if transaction is in block
           return result

          }
        })

**Comment by Tbaut** [comment]
The broadcasting is not related to the extension, since its role is only to sign, not to broadcast. please check the polkadot/api examples: https://polkadot.js.org/docs/api/examples/promise/transfer-events
