### ISSUE TITLE
Automation Requires version to  be included in manifest

### ISSUE THREAD

**Issue by aanandan1987** [polkadot-js/extension#1375]
In order to automate the plokadot site (https://orderbook.polkadex.trade/) , we need plokadot dot source code and manifest file to be included in our source code. got the manifest file from the below location (packages\extension\manifiest). but while running the code it shows below error. can some one take a look and help us here

![image](https://github.com/polkadot-js/extension/assets/158262955/4eb356fa-3224-4194-a2ac-e77563c1638e)

Ran the same on firefox browser with play wright and type script. code block is as below
  const extensionPath = path.join(__dirname, 'extension-master');
  global.browser = await chromium.launchPersistentContext('', {
    //devtools: true,
    headless: false,
    channel: 'chrome',
    args: [
      `--disable-extensions-except=${extensionPath}`,
      `--load-extension=${extensionPath}`,
    ],
    viewport: {
      width: 1920,
      height: 1080,
    },
  });
  // for manifest v2:
  let [background] = global.browser.backgroundPages();
  if (!background)
    background = await global.browser.waitForEvent('backgroundpage');
  // let [background] = global.browser.serviceWorkers();
  // if (!background)
  //   background = await global.browser.waitForEvent('serviceworker');
  const pages = global.browser.pages();
  global.page = pages[0];

**Comment by TarikGul** [comment]
The version is included in the `build`.

You should be grabbing the manifest from the build - so if you run `yarn build` against the repo then go to `packages/extension/build/manifest.json` you will see the version attached.

**Comment by TarikGul** [comment]
Closing this as answered above
