### ISSUE TITLE
Regression. Cannot forget account. v0.47.5

### ISSUE THREAD

**Issue by Juanma0x** [polkadot-js/extension#1376]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When the user tries to forget an account, clicking the button does not trigger any response, and the account is not removed from the extension.

![image](https://github.com/polkadot-js/extension/assets/120041850/d7af9b82-6d2a-4cf7-a892-472b221b94cc)

  - Version:
Chrome  126.0.6478.115
Polkadot extension 0.47.5

The functionality does work on version 0.41.1.

**Comment by TarikGul** [comment]
I was able to reproduce the issue. Thanks for filing it

**Comment by TarikGul** [comment]
Definitely an annoying little bug. It totally works in dev mode, but not in the live version...

**Comment by wangminqi** [comment]
me too, can not forget account in Chrome extension.
