### ISSUE TITLE
Manifest v3 sometime doesn't init extension

### ISSUE THREAD

**Issue by poka-IT** [polkadot-js/extension#1409]
On latest builds with manifest v3, extension is working fine, but sometime, on random opening, when didn't open it for a while, I got `...loading...` state with this JS errors:

![image](https://github.com/user-attachments/assets/616dd111-b5a0-4853-95a0-f05fef3a9736)

When close and open again, the extension is working fine again.
Tested on chrome (Brave)

**Comment by TarikGul** [comment]
Very weird, I haven't seen this in Chrome itself, or have been able to reproduce it. That being said the `Could not establish connection. Receiving end does not exist` seems to be related to one other issue I have just recently heard of so I will look into this.

**Comment by poka-IT** [comment]
This bug was also detected on Firefox by several users.

**Comment by TarikGul** [comment]
This is all resolved with the latest releases, 0.52.2 is active in chrome, and firefox should be up this week.
