### ISSUE TITLE
`Unknown status code: 28160` when connecting ledger

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/extension#1410]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When I connect my ledger to polkadot.js extension, it reported following error.
![img_v3_02d3_cdc2219a-c791-498f-aacc-952e4bd9c4dg](https://github.com/user-attachments/assets/242dbac3-aebe-4db9-b1f8-adb3e90e9bc4)

* **What is the motivation for changing the behavior?**

Make polkadot.js extension works with my ledger.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
Yes this is a known issue and is being fixed here: https://github.com/polkadot-js/extension/pull/1408
