### ISSUE TITLE
Subscribed Accounts don't update when authorizations are added/removed

### ISSUE THREAD

**Issue by F-OBrien** [polkadot-js/extension#1411]
* **I'm submitting a ...**

  - [x] Bug report - (maybe)
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

**Current behavior** - Modifying the authorizations for a connected site does not update the subscribed accounts until either a new key is added/removed from the wallet or the connected page is reloaded.

**Expected behavior** - Modifying connected key authorizations updates the subscribed accounts.

I'll be submitting a PR for consideration.

* **What is the motivation for changing the behavior?**

Subscribed keys not updating immediately can be confusing for users.

* **Please tell us about your environment:**

  - Version: 0.49.3
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript
    - [ ] Other

**Comment by Mazaltov888** [comment]
Good afternoon. Help me, please. I can't log in to my account. Haven't used the account in a year. Now I downloaded the app in Chrome. Entered the keys, password. I click on the activate button, but it won't click. You can see from the screenshots. Thank you very much in advance for your respect

![WhatsApp Image 2024-07-25 at 15 28 35](https://github.com/user-attachments/assets/447afd32-1a16-4460-9c5d-4a559a521320)

![WhatsApp Image 2024-07-25 at 15 28 50](https://github.com/user-attachments/assets/a3b4cc0d-89b6-4bca-ae9a-b98ed1456d52)

![WhatsApp Image 2024-07-25 at 15 29 15](https://github.com/user-attachments/assets/8b8f20a4-f442-430b-8719-b1ca68525a62)

![WhatsApp Image 2024-07-25 at 15 29 30](https://github.com/user-attachments/assets/7caa1221-2735-4809-beb5-c0092c7d5581)
