### ISSUE TITLE
can not connect to `polkadot.js` extension

### ISSUE THREAD

**Issue by 2nthony** [polkadot-js/extension#1416]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: 0.49.1
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

---

## bug

since the extension upgraded to 0.49.1 this issue occurred

[Subsquare(web)](https://polkadot.subsquare.io) browser console
<img width="407" alt="image" src="https://github.com/user-attachments/assets/cb7ae9a9-a56f-4d69-a81e-2b088d4f47f7">
[polkassembly(web)](https://polkadot.polkassembly.io/opengov) console
<img width="614" alt="image" src="https://github.com/user-attachments/assets/e3919c0b-310d-43eb-92ce-1f68266bbae1">

## repro

- open one of the webs above
- and wait for a while, basically 10 minutes
- wait until the error log appear, and then connect to `polkadot.js`

## code

in subsquare code is using `injectedWeb3['polkadot-js']`

```js
// https://github.com/opensquare-network/subsquare/blob/main/packages/next-common/hooks/connect/useSubstrateAccounts.js#L42-L46

const walletExtension = await injectedWeb3['polkadot-js'].enable("subsquare");
```

**Comment by F-OBrien** [comment]
I've replicated this also. Seems to be the same as the issue described here
https://stackoverflow.com/questions/78165826/chrome-extension-attempting-to-use-a-disconnected-port-object-manifest-v3
and here
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/BD6Tb_AEXfM

**Comment by 2nthony** [comment]
seems normal now
