### ISSUE TITLE
Deriving Account Doesn't Work

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/extension#1417]
I tried deriving a new account from an existing one. The extension asked for the password of the root account and the derivation path, and when I clicked "Create a derived account", it just hangs

<img width="574" alt="image" src="https://github.com/user-attachments/assets/a85b2f4d-7efe-4bc3-8b5d-96f2f2475f63">

**Comment by F-OBrien** [comment]
It works for me but I'm suspecting this (and other similar issues) are related to ports timing out and disconnecting following the Manifest V3 update as mentioned in #1416. You could try restarting the extension to see if it fixes it.

**Comment by joepetrowski** [comment]
Actually it ended up working when it was just the extension pulled down, but when I made it full screen it doesn't work.

**Comment by bee344** [comment]
@joepetrowski is this on Chrome or FF or both?

**Comment by joepetrowski** [comment]
Have only tried on Chrome.

**Comment by TarikGul** [comment]
This should now be fixed on chrome. Do you mind confirming it works for you?

**Comment by joepetrowski** [comment]
All good, yes. Thanks!
