### ISSUE TITLE
Polkadot account creation button does not work!

### ISSUE THREAD

**Issue by Sunshine-pol** [polkadot-js/extension#1420]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by Sunshine-pol** [comment]
I use google translate.  Trying to create a polkadot account, when the window opens, I click on create an account, new window to put my name and password twice. then I click the button at the bottom and nothing happens. I use Chrome as my browser.

**Comment by Sunshine-pol** [comment]
dont have yet!

**Comment by bee344** [comment]
@Sunshine-pol 
- Are there any errors or warnings, either in the console or in the popup itself?
- Could you try with the extension in a full window instead of the popup?
- What's your Chrome version?

**Comment by Sunshine-pol** [comment]
Bonjour Hello Alerto Nicolas,

Voici :

   - Are there any errors or warnings, either in the console or in the
   popup itself? no
   - Could you try with the extension in a full window instead of the
   popup? i join one picture
   - What's your Chrome version? the last one. I use of Google Translate:
   And i installed FIREFOX and reproduced the steps: installed the Polkadot
   connection in the toolbar at the top, click on it and start creating a new
   account. To see the photo.

when I click on the orange button at the bottom, nothing happens...as
if the button was not connected!



Merci
Best Regards

Daniel

@Sunshine-pol




*Lavage de vitres - Entretien résidentiel" La qualité attire la qualité"*



*André Daniel St-Arnault*
*Tél: +1-514-952-8688*

***@***.***

<http://goog_1619236767>
www.entretiensunshine.ca



Avis de confidentialité: Ce message électronique, y compris toute pièce
jointe, est privilégié et confidentiel. Toute utilisation ou communication
non autorisée est interdite. Si ce message vous est parvenu par erreur,
veuillez en aviser l'expéditeur par téléphone ou par courriel, supprimer ce
message et toute pièce jointe, et détruire toute copie immédiatement. Merci.

Notice of Confidentiality: This email communication and any attachments are
confidential and legally privileged. Any unauthorized use or disclosure is
prohibited. If received in error, please notify the sender by telephone or
by return email, delete this communication and any attachments, and destroy
any copy immediately. Thank you.

**Comment by TarikGul** [comment]
@Sunshine-pol The newest release has been pushed to the chrome store with fixes. Can you confirm it now works for you?

**Comment by Sunshine-pol** [comment]
Yes, it works!


Maintenant je vieux le lier a vtbdex.com
Mais là aussi ça ne fonctionne pas!

Et comment puis-je utiliser de nouveaux wallet Polkadot? Ou dois-je me
connecter pour l’utiliser et qu’elles Cryptos puis-je y mettre?

Il n’y a pas de portail d’accès sur le site polkadot.js.org/extension/

Now I link it to vtbdex.com But here too it doesn't work! And how can I use
new Polkadot wallets? Where do I have to log in to use it and what cryptos
can I put in it? I know I can put VTBs there, but nothing more. There is no
access portal on the site polkadot.js.org/extension/


Thanks
Best regards
