### ISSUE TITLE
Can't create an account using google chrome extention

### ISSUE THREAD

**Issue by AdiBourne** [polkadot-js/extension#1440]
I have just tried 4 times to set up a chrome extension. 
1/2 ok ... got and copied seed phrase
2/2: filled in required fields then the "create account" button at the end doesn't do anything. All looks correct but pressing "return" or clicking "create account" has no effect.

Any thoughts?

For general support, howto, coding and bundling questions, please
use the Substrate & Polkadot StackExchange at

  https://substrate.stackexchange.com/

and get other ecosystem developers involved. This issues in this
repository are meant for the tracking of feature requests and bug
reports.

While all issues are looked at non-bug and non-features would take
quite a bit longer to get to and may yield less than satisfactory
responses in this format.

Additionally, please ensure you have done a search on the existing
and closed issues before logging a new request. This saves time on
all sides.

-->

* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by AdiBourne** [comment]
I have just tried 4 times to set up a chrome extension.
1/2 ok ... got and copied seed phrase
2/2: filled in required fields then the "create account" button at the end doesn't do anything. All looks correct but pressing "return" or clicking "create account" has no effect.

Any thoughts?

**Comment by AdiBourne** [comment]
Just tried a 5th time.
1st I updated Google Chrome.
then I opened the extension as a webpage.

Same as before but the last stage that doesn't work is when I try clicking the button that says:
"Add the account with the generated seed"

**Comment by TarikGul** [comment]
Closing in favor of https://github.com/polkadot-js/extension/issues/1415. This issue will be fixed with the latest release pushed to the store - it should be active relatively quickly on chrome (day or 2), and within a week for firefox.
