### ISSUE TITLE
polkadot-js extension stopped working with non-polkadot ledger apps 

### ISSUE THREAD

**Issue by lrcnz** [polkadot-js/extension#1443]
Ledger apps such as Acala and Karura were working with polkdot-js extension until recently, with current version extension is returning error messages such as "Ledger Generic App", "Ledger error: 28160: CLA Not Supported" - the same Apps and accounts work connecting to Talisman wallet.

Setting in the extension only has the Generic App and the Migration App listed, and neither of these options work with Acala and Karura Apps I have tested. Errors and setting screenshots attached.

![image](https://github.com/user-attachments/assets/ab8f6150-d2c7-4276-9d0b-902796e8d1a0)
![image](https://github.com/user-attachments/assets/54eea73b-24a4-45fa-aca7-bc19cf8306cb)

**Comment by F-OBrien** [comment]
I've verified this issue also. looks like PR #1408 completely removed support for all older ledger apps. This means the extension will not work with chains that have not been upgraded to be compatible with the latest ledger app (which is still a lot).

**Comment by TarikGul** [comment]
From what I understood the migration app has all the derivation paths hardcoded so that there is support for those legacy ledger apps. Atleast that was the purpose for it - for example apps uses the same functionality and it works with all the chains.

**Comment by TarikGul** [comment]
That being said - let me double check with Acala, and Karura.

**Comment by F-OBrien** [comment]
@TarikGul To my knowledge the only difference between the Generic and Migration ledger app is that the migration app supports keys derived from chain specific SLIP44/BIP44 derivation paths while the Generic one only supports the Polkadot path.

For a chain to be compatible with either of these new ledger apps it must be on manifest v15 or later I believe and also have a specific signed extension added to the runtime to allow the generation of the metadata tree/hash required for clear signing of transactions with those apps. 

Dedicated chain ledger apps still need to use the original `Ledger` class from `@polkadot/hw-ledger` (which is now marked as depricated).

**Comment by F-OBrien** [comment]
Reference for information on what chains are required to do prior to being compatible with new Ledger Apps
https://forum.polkadot.network/t/new-polkadot-ledger-app/8817#adding-support-to-your-parachain-runtime-8

**Comment by TarikGul** [comment]
> To my knowledge the only difference between the Generic and Migration ledger app is that the migration app supports keys derived from chain specific SLIP44/BIP44 derivation paths while the Generic one only supports the Polkadot path.

Yup exactly, and what differentiates chains on the generic app is just the ss58 prefix.

> For a chain to be compatible with either of these new ledger apps it must be on manifest v15 

Yup `CheckMetadataHash` requires it to be minimum v15 metadata.

> Dedicated chain ledger apps still need to use the original Ledger class from @polkadot/hw-ledger (which is now marked as depricated).

If this is the case, then I definitely missed this caveat, and can add the old `Ledger` class support back in the extension. Generally I think we would just add an option to the list being `Legacy Ledger` or something of the like.

**Comment by F-OBrien** [comment]
I prefer calling them something like "Chain Specific Ledger app" as for the users of those chains they are not "legacy" they are all they currently have and likely will be all they have until those chains can catch up to newer version of the Polkadot SDK which could be anywhere from months to never.

**Comment by TarikGul** [comment]
> I prefer calling them something like "Chain Specific Ledger app" as for the users of those chains they are not "legacy" they are all they currently have and likely will be all they have until those chains can catch up to newer version of the Polkadot SDK which could be anywhere from months to never.

Good point!

**Comment by TarikGul** [comment]
I'll have something up tonight, or tomorrow that should have this resolved, in the extension then I will add the same thing to apps.

**Comment by lrcnz** [comment]
> I prefer calling them something like "Chain Specific Ledger app" as for the users of those chains they are not "legacy" they are all they currently have and likely will be all they have until those chains can catch up to newer version of the Polkadot SDK which could be anywhere from months to never.

Agree!

> I'll have something up tonight, or tomorrow that should have this resolved in the extension then I will add the same thing to apps.

Thanks for the prompt action, look forward seeings PRs merged.

**Comment by lrcnz** [comment]
Hi @TarikGul, I don't see the option of `Chain Specific Ledger App` shows up in the Ledger App drop down, am I missing any step?

Tried remove and added back the extension to ensure it is the latest, it shows the same `Ledger error: 28160: CLA Not Supported` when import ledger account

![image](https://github.com/user-attachments/assets/2a32c4f9-1942-4581-8c31-cbd93c0145ca)
![image](https://github.com/user-attachments/assets/4c895927-8840-4549-91b8-9990fa486777)
![image](https://github.com/user-attachments/assets/fbb1640d-0ddd-4330-9586-9f8785275517)

**Comment by F-OBrien** [comment]
@lrcnz the fix was merged to the master branch yesterday but a new release hasn't yet been published to the chrome store.

**Comment by TarikGul** [comment]
@lrcnz as @F-OBrien said there has not been a release to npm or github, as well as the store. I'll be cutting a release for the extension tomorrow for NPM and github. Then come either Friday or Monday they will be pushed to the store for review.
