### ISSUE TITLE
Injection happen after page load

### ISSUE THREAD

**Issue by tien** [polkadot-js/extension#1475]
Since injection happen [asynchronously](https://github.com/polkadot-js/extension/blob/master/packages/extension/src/page.ts) after the page have loaded, if you try to detect whether PJS is installed too early, it might appeared that the extension is not installed.

**Comment by Tbaut** [comment]
I noticed it too, and actually had a really nasty piece of code waiting for a sec or 2 before checking again. I've had a user tell me the same on Multix while using dot-connect. I believe it's safer for pjs extension to do so, and I guess dot-connect could probably poll for a couple seconds.

**Comment by tien** [comment]
Yeah, polling or waiting is an easy fix. But ideally this should be fixed on PJS extension side, since this is an unexpected behaviour that is unique to PJS extension.

**Comment by Tbaut** [comment]
I guess it comes from there: https://github.com/polkadot-js/extension/blob/0d48a30874d91006628fb115142a339e85a2183c/packages/extension-dapp/src/util.ts#L6
it waits for the document to be in "complete" state. I wonder if we should have `document.readyState === "loading"`. 
Here we we injecting in either state `complete` or `interactive`: https://github.com/polkadot-js/extension/pull/324/files which means earlier than `complete`. Now I do recall we had issues, and I found the comment: https://github.com/polkadot-js/extension/pull/507#discussion_r507037730

Sooo we went for this back then, bc it was safer.
