### ISSUE TITLE
Import account with private key format

### ISSUE THREAD

**Issue by xlc** [polkadot-js/extension#185]
I have hex format private key and can't import it to extension. The import screen should be similar to the polkadot apps new account screen that allow me to enter hex format seed.

**Comment by jacogr** [comment]
We are not going to do this - https://github.com/polkadot-js/extension#why-cant-i-import-an-account-with-a-seed

**Comment by xlc** [comment]
Ok. I guess I just need to write a script to do the conversion.

**Comment by jacogr** [comment]
Thought through this, still really don't want explicit support, but... can adjust the mnemonic input to also allow hex input (this will continue to be undocumented on the UI itself). It won't really cost anything to do this. (It already supports the full suri inputs)
