### ISSUE TITLE
what to do without Secret phrase ?

### ISSUE THREAD

**Issue by drandreaskrueger** [polkadot-js/extension#210]
> FAQ: Why can't I import an account with a seed

I understand your reasoning. 

However, after 

```
subkey --network kusama vanity "ksma"
Generating key containing pattern 'ksma'
100000 keys searched; best is 189/237 complete
...
6000000 keys searched; best is 236/237 complete
best: 237 == top: 237
Secret Key URI `0x................................................` is account:
...
```

I end up with ONLY a "Secret Key URI" - but without  `Secret phrase`

**Comment by jacogr** [comment]
There is a hidden feature that a hex-denoted seed can be imported. 0x followed by 64 hex chars. (It is in the 0.14.1 release, already available on FF, Chrome will be available as soon as the release is approved there - 3 days waiting, probably a couple more to go)

**Comment by drandreaskrueger** [comment]
Cool. 

Why not make it an unhidden option?   Like in the https://polkadot.js.org/apps/#/accounts --> add acount --> **seed** field dropdown

But anyways, I guess that solves it for me then. 

Thanks. A lot !

CanClose.
