### ISSUE TITLE
Selected Display Address Format should be reflected in API

### ISSUE THREAD

**Issue by Swader** [polkadot-js/extension#250]
`web3Accounts()` in extension-dapp fetches accounts in Substrate format, no matter what's selected as the display format option in the extension's settings. The API should either be updated to include address type as a param, or it should fetch whatever is selected in the settings.

**Comment by Tbaut** [comment]
I've actually had the "surprise" as an api user, so 100% agree with this issue. I would tend to go the route of the `api` enhancement by adding an option to choose the `addressEncodingPrefix` since it's a none breaking change. Does that sound good to you @jacogr ?

**Comment by jacogr** [comment]
The ss58Format is display-only and it is certainly not up to the extension to dictate how any app displays it. Will look at anything non-breaking.
