### ISSUE TITLE
Pull out `extension/background` and `extension/page` for re-use

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/extension#262]
I want to use `@extension/background` and `@extension/page` from https://github.com/polkadot-js/extension/tree/master/packages/extension/src, in substrate-light-ui, so that 1/ we don't rewrite stuff and 2/ stay as close as polkadot/extension. Since they export classes, those are easily extendable.

But `@polkadot/extension` builds via webpack, and the bundled js are published to npm.

Right now solutions I can think of are copy-pasting files or git submodules. Both are not optimal.

So proposed solution:
- create a new `packages/extension-{base|shared}` folder (naming to be chosen), put those 2 folders above inside
- `packages/extension` will import from this new folder
- build this new folder with babel, publish those files to npm

if green light then i'll create a PR

**Comment by jacogr** [comment]
Actually the extension webpack output should not be published to npm. It is useless in that form, have however not added the appropriate `.npm-skip`'s in this repo, so everything is published by default, however there are actually only 2 packages that should be as it stands at this point in time.

I supposed we can publish these, however it was never really intended as external and do bear in mind that these are certainly not managed in a "these interfaces should be kept stable" fashion. Although the interfaces are stable... atm, but there are some horrors elsewhere that may have an impact.

`@polkadot/extension-base` does fit best.
