### ISSUE TITLE
Remove persistent background pages (basically eol in Chrome)

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#310]
Specifically https://github.com/polkadot-js/extension/blob/master/packages/extension/manifest.json#L11

This puts the extension down the road to get ready for a move to V3 manifests (persistent not supported, background pages are service workers)

There is an impact on initialization, so will see what the overhead turns out to be. (Specifically wasm-crypto)

This also means that the in-memory state needs to be moved to actual storage as applicable.

The checklist -

https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/

**Comment by jak-pan** [comment]
Ah so this is why in chrome canary the extension breaks after using it for a while. Stable is now at version 89 where it works. Canary is at 91 so there's probably still some time.

**Comment by jacogr** [comment]
Umpf. There is a still a lot of work to do on this front... not ready for v3 as of yet :(

**Comment by jak-pan** [comment]
It looks like almost all of the extension is working even without the wasm and with the error present. It's just the popup window account screen that doesn't work. Even account creation from the popup is ok. Isn't there just some easy fix for now, that would at least partly make it seem not broken? I mean it's usable...

**Comment by jacogr** [comment]
I saw the UI issue on canary, it is the css calc here that is broken -

![image](https://user-images.githubusercontent.com/1424473/112051877-baa6ba00-8b52-11eb-99c2-3119c0cd7bc2.png)

It really looks like a Canary bug. Setting it to `height: 100vh` works - but you cannot quite do it each and every time you open it...

**Comment by jak-pan** [comment]
Ah sorry. I thought that it has to do something with the error in the console. 

Maybe OT but:
I rememeber exactly this problem happening several years back, when working on an extension. It had to do with the window starting as zero size and resizing to content, but it didn't always fire repaints correctly, so we needed to hack it, by introducing resize after load. I thought I'm crazy by telling this but I still found this is an issue from time to time until today! https://stackoverflow.com/questions/8840580/force-dom-redraw-refresh-on-chrome-mac

**Comment by jacogr** [comment]
:) Just spend some time reading a number of interesting workarounds - and then got to stuff like „October 2020 - the above hacks stopped working, here are some new ones“

**Comment by zeedgold** [comment]
This is very interesting

**Comment by zeedgold** [comment]
This is very interesting

**Comment by Nick-1979** [comment]
Are there any plans to work on this serious issue in the near future?

**Comment by jacogr** [comment]
The extension won't be removed from the stores, but will comply with the requirements.

**Comment by Nick-1979** [comment]
When do you estimate it will be available?

**Comment by poka-IT** [comment]
I implement manifest v3 changes with service_worker on this commit of our fork: https://git.duniter.org/clients/duniter-connect/-/commit/6a2278eac0ea5e779270ff09d6742ef7360a75e9

Inspired by [this commit](https://github.com/Cardinal-Cryptography/aleph-zero-signer/commit/d2f9e92d096021a70e0713e82316235f0b91136e), many thanks to @Kocik.

It works very good on Chrome and have been accepted on chrome store. Just a little issue with popup width and popup which doesn't close after extrinsic signature confirmation (stay open on extension home).

On firefox, I still have an issue with permission: We have to manually accept the extension to communicate with web page, for each ones, I don't know why yet.
