### ISSUE TITLE
allow importing ed25519 key type

### ISSUE THREAD

**Issue by ilhanu** [polkadot-js/extension#339]
The value of Polkadot.js with other web-apps is getting more useful. e.g. using it for idenitification or signing. 

I have started of with an `ed25519` signature when kusama was still in POA mode. Since then this stuck with me, it is usable in the polkadot.js apps, here there are not limitations on using ed25519, this is different for the polkadot.js extension. The issue is to address this. 

I have tried by importing the hex seed phrase[ed25519] of the account, no luck it get a different addresses. It would be great if we could add `ed25519` support into the polkadot.js extension. This would save me time in re-transferring everything to a `sr25519` account and probably support for more users.

**Comment by jacogr** [comment]
Thanks for logging, will prioritize this.

**Comment by jacogr** [comment]
After https://github.com/polkadot-js/extension/pull/336 we can import via JSON (another way of solving this, does not remove the need for the selector though, just an alternative)

**Comment by mariopino** [comment]
Hi, same problem here using ed25519 hex address, I imported the account via JSON and got the correct address, but stilll get an error when signing a message in Polkassembly.

**Comment by jacogr** [comment]
@mariopino That is an Polkassembly issue, they didn't support anything by sr from extensions before - https://github.com/paritytech/polkassembly/pull/1034

**Comment by jacogr** [comment]
I'm going to close this one. We have compatibility with other types now via the JSON import and at this point not fully-open to make creation more confusing than it already is with more options. This may change in the future, but we are really aiming for consistency.
