### ISSUE TITLE
Expose import from hex seed in the UI

### ISSUE THREAD

**Issue by dvdplm** [polkadot-js/extension#359]
Currently the user has no way of knowing that the extension can handle hex seeds as well as mnemonic seeds. It'd be good to expose this option in the UI.

**Comment by jacogr** [comment]
Closing as a "wont-fix". It is there for advanced user, as per the FAQ we are not advocating this approach so won't make it explicit. Wortst-case, Shawn added a JSON import which they can use (and is explicit) in the next release.
