### ISSUE TITLE
Can avoid asking for permission at each startup?

### ISSUE THREAD

**Issue by dvdplm** [polkadot-js/extension#360]
Currently the extension shows an "Authorize"-dialog every time the browser starts. Is there a way to avoid this?

![image](https://user-images.githubusercontent.com/18515/83624163-91e91000-a592-11ea-9c5c-f6dae437c48f.png)

**Comment by jacogr** [comment]
Thanks for logging. No, however it has been outstanding for 1 year in #85. Simple enough to do from a back-end perspective (aka just persist the response), but it adds a whole bunch of complexity with config and new settings to manage all the sites. 

So it is also (sadly) unlikely to bubble up the list soon.

**Comment by jacogr** [comment]
Closing as tacked in #85
