### ISSUE TITLE
Accounts are not available from file:// URL

### ISSUE THREAD

**Issue by DemiMarie-parity** [polkadot-js/extension#361]
This is a minor annoyance during development.

**Comment by jacogr** [comment]
Not sure I understand? So in extension development t should be added to the browser as per https://github.com/polkadot-js/extension#development-version (Permanently running the development version myself)

When trying to inject into an account served as a file... We cannot inject to the `file://*` location, that will never be accepted on the chrome store. Each update all of the manifests permissions are checked again and needs to be justified, despite any prior approvals.

**Comment by DemiMarie-parity** [comment]
Is `file://` considered different for store approval purposes?

**Comment by DemiMarie-parity** [comment]
I thought that we already needed permission for all sites.

**Comment by DemiMarie-parity** [comment]
NoScript does inject into `file://*`, from what I can tell.

**Comment by jacogr** [comment]
Yes, it is different and needs to be explicitly provided - https://github.com/polkadot-js/extension/blob/master/packages/extension/manifest.json#L19

So sadly, this is a wontfix here - the `<scheme>://*` permissions are an absolutely nightmare to justify, with queries each approval round.

**Comment by DemiMarie-parity** [comment]
@jacogr Ideally there would be a way for an extension to prompt users interactively for permission.  Sadly, it isn’t possible.
