### ISSUE TITLE
Allow filtering by chain in accounts view

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#365]
Top button to apply filter

**Comment by Tbaut** [comment]
Do we still want this now that it's sorted by network? I'm worried this menu will take quite some space at a critical position (very top or header) to benefit few users.

**Comment by jacogr** [comment]
Agreed, I think with the new sorting we killed this one. So I have 56+ accounts (according to apps) and it works ok for me now. Happy to close it.
