### ISSUE TITLE
Unable to connect to a provider or filter accounts for a specific provider

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/extension#370]
In the Polkadot.js Extension, if I click the menu of an account and choose it to be only visible for "Kusama (canary)", and then I run my Dapp, when it runs `const allAccounts = await web3Accounts();` it returns:

```
allAccounts 
 [{
address: "5DSZQGKKSAVyrkVZgQoGVzu512bxQdf2u3rivCA4fLYDxRAf"
meta: {genesisHash: "0xb0a8d493185c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe", name: "Luke", source: "polkadot-js"}
},
{…}]
```

But all the `source` properties returned are "polkadot-js" (i.e. none of them start with "kusama ..."
How do I only get the list of the accounts that I chose to be visible for "Kusama (canary)"?

Then when I run 
```
const allProviders = await web3ListRpcProviders('polkadot-js');
```
it returns an empty object `{}`

How can I connect to a provider using the extension? Or do I need to separately connect to a specific provider using the @polkadot/api library?
```
import { WsProvider } from '@polkadot/api';
const provider = new WsProvider('wss://cc3-5.kusama.network/');
```

It looks like the substrate-node-template has done what i've mentioned above here: https://github.com/substrate-developer-hub/substrate-front-end-template/blob/master/src/substrate-lib/useSubstrate.js#L18

**Comment by jacogr** [comment]
1. `source` is always the name of the extension. 
2. When tied to a chain, the only thing that happens is that the chain-specific genesisHash is set on the account
3. The polkadot-js extension does not support the provides or the management, it manages accounts only, not connections. (Other extensions may support this, hence the general interface)

**Comment by ltfschoen** [comment]
In my game I ended up just using `WsProvider` https://github.com/ltfschoen/flappytips/blob/master/src/Game.js#L80 in the interim
