### ISSUE TITLE
Is there a best practice for injecting from webview?

### ISSUE THREAD

**Issue by xwartz** [polkadot-js/extension#371]
If I have a mobile app and I want to access the Polkadot DApp using webview, I Need to inject JS code to intercept account requests and signatures from DApp. 
Do you have a list of best practices?

**Comment by xwartz** [comment]
@jacogr  Can you offer some advice?

**Comment by jacogr** [comment]
It would be cool having this in mobile. So any injector would just implement/use https://github.com/polkadot-js/extension/blob/master/packages/extension-inject/src/index.ts#L10 - all the dapp module does is look for items on the window object to interact with.

So the above package, given an `enable` function, just attaches it to the window.
