### ISSUE TITLE
How do I check if this extension is installed?

### ISSUE THREAD

**Issue by aniiantt** [polkadot-js/extension#375]
I know I can use `window.Injectedweb3` to check if the extension is installed.

But there are some problems with this method. It's going to be executed in a very low order, so when I just enter the page or refresh the page, `window.Injectedweb3` is undefined. I hope to be like Metamask, `window.Injectedweb3` will never be undefined. Or can provide me with other global variables, such as ` isPolkadotExtensionInstalled `, let me can detect whether extension installation

**Comment by jacogr** [comment]
Use `web3Enable` which has the correct ordering and init. Checking the window object is error-prone (although it does run on document start, so actually should be set by the time user-code runs). However, `web3Enable` ensures order.

**Comment by Frenkiee** [comment]
I'm working on a remix plugin, which uses polkadot extension, where I've noticed that `window.injectedWeb3` is empty (when logged from code), even tho Polkadot extension is installed in browser. Interestingly when checking for the object in browser console, we can detect that `injectedWeb3` object has `polkadot-js`. Also the extension is detected when running the app outside the remix plugin. Any ideas on how to debug or solve that kind of problem?
