### ISSUE TITLE
Restoring account - not intuitive

### ISSUE THREAD

**Issue by ninabreznik** [polkadot-js/extension#387]
When you try to restore an account, you can overwrite the newly generated seed phrase. But it's impossible to know this. Just thank to a friend we were able to do it.

It would be very nice to make this clear, maybe to change the title to Create new or restore existing account

And in the seed phrase section to write - if you are restoring your existing accoutn, delete this newly created phrase and replace it with your existing one.

That would be a quick fix, still not the best UX solution.

**Comment by fionataeyang** [comment]
I wonder where to find ```restore account``` button on the first page when all accounts were removed. It only shows me to create new account but not restore account after I created few accounts, and removed them all.
![image](https://user-images.githubusercontent.com/9526525/87170694-426dd080-c304-11ea-8c4e-680888e0eaf2.png)

I try to restore account back to use the previous link to save my account back.
```chrome-extension://mopnmbcafieddcagagdcbnhejhlodfdd/index.html#/account/restore-json```
![image](https://user-images.githubusercontent.com/9526525/87170714-48fc4800-c304-11ea-8b36-dd9144f3ac89.png)

And restore account is using a JSON file, I wonder it is possible to use seed phrase as well? Cuz if someone forgot their password, then account won't be able to restore and gone forever.

**Comment by jacogr** [comment]
Thanks for mentioning the unintended bug of being able to get to JSON restore without an account - that hole will be closed in the next release.

You can import via seed as per the normal create process.

![image](https://user-images.githubusercontent.com/1424473/87176839-f6f2fc80-c2da-11ea-9083-c9e7590d12c4.png)

**Comment by fionataeyang** [comment]
I know it can import account from pre-existing seed. 
So there is impossible to restore account from first page?
I've tried to add account from [Polkadot.js.org](https://polkadot.js.org/). My friend told me I can paste seed phrase into it, and it will get back account.
But I cannot use the same way via your extension, cuz it blocked.

**Comment by jacogr** [comment]
Yes, you need at least an account before adding anything else via seed or JSON import.
