### ISSUE TITLE
Password length

### ISSUE THREAD

**Issue by Geordie-R** [polkadot-js/extension#394]
Its not allowing me to import json when setting up an account if the password is say 40 characters.  the password length allowed should be upped.

**Comment by jacogr** [comment]
This is actually something that is already fixed for v3 JSON keyfiles, that is going live with the next release. However for v2, only the first 32 characters is ever used (across apps & extension) - so even if you entered 40 in the apps UI, only the first 32 would have been used. (This is a limitation of the encryption, as mentioned lifted in the generation that is now being rolled out)
