### ISSUE TITLE
doc/help: bundle setup

### ISSUE THREAD

**Issue by thelostone-mc** [polkadot-js/extension#409]
#### Description 

I'm trying to use browserify to generate a bundle using browserify that I can add to my django app (for Gitcoin)

When I try to generate the bundle 
https://github.com/thelostone-mc/polkadot-bundle/blob/master/ext-dependencies.js

I get this 
![image](https://user-images.githubusercontent.com/5358146/90806843-36315600-e33b-11ea-82ad-0f1af81f5792.png)

I'm assuming I'd need both `extension` / `extension-ui` to be able to trigger a transfer transaction from the extension right ?
Not sure if I'm missing anything obvi

The bundle gets created when I use only `extension-dapp`
but then since the underlying connections / UI packages aren't there -> I end up with empty array

![image](https://user-images.githubusercontent.com/5358146/90807583-4f86d200-e33c-11ea-98ad-e889e15d0748.png)

**Comment by thelostone-mc** [comment]
The goal is to be able to send KSM tokens from A (signed in via extension) -> B  
and the same for DOT token

**Comment by jacogr** [comment]
You should only need extension-dapp to allow the extension to work in your app.

**Comment by thelostone-mc** [comment]
@jacogr Ah okay then bundle generation works but I end up with this
Would I have to add enable else ?

https://user-images.githubusercontent.com/5358146/90807583-4f86d200-e33c-11ea-98ad-e889e15d0748.png

**Comment by jacogr** [comment]
I believe you probably need to pass a name for your app to web3Enable as per https://github.com/polkadot-js/extension/tree/master/packages/extension-dapp#usage

That should popup a dialog asking you to approve.

**Comment by thelostone-mc** [comment]
Oh perfect ! That works 
Btw this extension is pretty dope <3

**Comment by thelostone-mc** [comment]
Oh perfect ! That works 
Btw this extension is pretty dope <3

**Comment by thelostone-mc** [comment]
Oh perfect ! That works 
Btw this extension is pretty dope <3

**Comment by jacogr** [comment]
Phew! That was a shot in the dark... I'm really happy my guess helped.

**Comment by jacogr** [comment]
... it really should do _something_ if you pass `undefined` there though, even a helpful error would help.

So re-opening this to just track that as an enhancement so nobody else steps in the same hole.

**Comment by thelostone-mc** [comment]
@jacogr I'll keep iterating on this meanwhile so in case if anyone wants to use it -> they could port over the bundle and roll with it 
https://github.com/thelostone-mc/polkadot-bundle

**Comment by Tbaut** [comment]
I'll get a peak at this one.

**Comment by Tbaut** [comment]
I can't reproduce unfortunately. The name is simply an empty string when passing `undefined`.
I still have a PR for an eventual error in case this happens, not sure that makes sense, not sure how JS handle this when TS doesn't allow it. I doubt the name was the original problem.

Using the following test app: https://github.com/Tbaut/basic-substrate-ui-template/blob/undefined-name/src/App.tsx#L49

![image](https://user-images.githubusercontent.com/33178835/92243141-44e24600-eec1-11ea-99b9-1e8c848de9ea.png)

**Comment by Tbaut** [comment]
closing as done in #430
