### ISSUE TITLE
feature/doc: decode address in wallet to substrate address

### ISSUE THREAD

**Issue by thelostone-mc** [polkadot-js/extension#411]
Usecase:

User would input their Kusama / Polkadot address (by copying the address from the extension)
and when stage on in the app -> they can choose to pay with that 
Exampple: `GZoo68t6icqNENrd7CTC9RCwVLszGuubKo5oGp7WSFxRnv2`

During the payment -> I'd have to inject the from address 
`const allAccounts = await web3Accounts();` return I believe the substrate address AKA
`5G4C8mo1UMbucaZQrQPQJC4Cnu4eBc6j8wxLQcYA2e3TgoZ8`

<img width="1680" alt="Screenshot 2020-08-25 at 4 42 31 PM" src="https://user-images.githubusercontent.com/5358146/91168345-1f03b700-e6f3-11ea-91fd-510535823ee4.png">

Is there a way within the extension where I could decode the address without expecting the user having to enter it ?

Looking at that docs I think I could probably do something like this -> but I'm not sure 
https://wiki.polkadot.network/docs/en/build-transaction-construction#tx-wrapper

AKA something like

```node
> let txwrapper  =require("@substrate/txwrapper");
> let y = "publicKey = “0x2ca17d26ca376087dc30ed52deb74bf0f64aca96fe78b05ec3e720a72adb1235”;

> let publicKey = 'GZoo68t6icqNENrd7CTC9RCwVLszGuubKo5oGp7WSFxRnv2' // 'GZoo68t6icqNENrd7CTC9RCwVLszGuubKo5oGp7WSFxRnv2'
> txwrapper.deriveAddress(publicKey) // 5G4C8mo1UMbucaZQrQPQJC4Cnu4eBc6j8wxLQcYA2e3TgoZ8
```

**Comment by jacogr** [comment]
txwrapper is not used here, that is external libraries, not familiar with it at all (it just builds on top of `@polkadot/api`). 

As soon as you send a tx, the extension will have the information, it doesn't connect to the chain at all, it only signs transactions and manages accounts.

**Comment by thelostone-mc** [comment]
Ah gotcha ! I had this scenario where I'd collect the public address and use that while signing the transaction !

The issue being I had to make sure the transaction was being signed by the address entered by the user in step 1
and to invoke the function -> I'd need to convert to it's substrate form and check if it was available in `web3Accounts()`

Another variation would have been where I'd list all the public addresses in the extension and the user would select which one to make a payment and go with it! 

I'll bundle in substrate and do a conversion of public address -> substrate address and roll with it ! 
Thanks ^_^
