### ISSUE TITLE
creating a new account with polkadot-js --> copying & saving seed phrase poor user experience

### ISSUE THREAD

**Issue by BabesPapes** [polkadot-js/extension#413]
I figured when creating a new account with the polkadot-js extension, that when I copy the seed phrase and switch to another window/app/document/... to paste the seed phrase and then go back to the browser where I had the polkadot-js extension open, the extension is suddenly not open anymore and I can't continue the "account creation process" anymore.
I will try to explain in a step by step guide:

1. open polkadot-js extension
2. click the plus icon to create new account
3. copy seed phrase
4. switch to another window with "alt-tab" 
5. paste the copied seed phrase
6. switch back to browser with polkadot-js extension with "alt-tab"
7. suddenly extension is closed and the process of creating new account is not available anymore

The same problem occurs in the 2nd step of the "account creating process" when you get asked for the password

kind regards, BsPs

P.S.: by the way, I was recommended by the Element (Riot) Polkadot Watercooler group to publish this problem here in Github

**Comment by jacogr** [comment]
The browser controls the popup, so nothing that can be done to "try and keep it open". However, you can open the extension in a new window/tab which makes the view persistent.

![image](https://user-images.githubusercontent.com/1424473/91220495-87b35980-e71c-11ea-991a-a42b779c00ad.png)

**Comment by jacogr** [comment]
Possible alternative under consideration https://github.com/polkadot-js/extension/issues/400

**Comment by BabesPapes** [comment]
ok, i see, maybe it would be better to have the "open extension in new window" as default to avoid confusion?
Because during the process of creating a new account and when switching between windows, I was also not able to tell if the "account creation process" was terminated or only interrupted, which worsened the experience unfortunately...

**Comment by jacogr** [comment]
It won't be the default, however as per issue I linked above (exactly the same as this one), that can be a solution, i.e. "remember your place".

**Comment by jacogr** [comment]
Closing this -

(a) there is a work-around to not make it happen
(b) there is an issue/enhancement open to keep the seeds persistent in #400
