### ISSUE TITLE
suggestions (non-critical, improvements)

### ISSUE THREAD

**Issue by drandreaskrueger** [polkadot-js/extension#414]
Thank you very much for the extension. It is [this one](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd) - right? 

Some small suggestions that came up when I tried out to _**reimport the 24 words mnemonic**_ from "parity signer" into your extension. It actually took me quite some time to re-create **the same addresses** in polkadot.js-extension that I had been given or derived in parity signer. (And as I had already sent money onto those addresses, it was essential to get them right)

I think by now and after investing all that time ... I have mostly understood what to do - but perhaps there is something for you to learn here? And thus make it easier for newbs.

**The general wish is to make cross-export-import easy and self-explaining, across several/all key tools.**

**Suggestion 1:**
Please you use both - parity signer, and polkadot.js-extension. 

Pen and paper. Write down all possible misunderstandings. And differencens between the two tools.
--> Create a mnemonic and addresses on one side, derive addresses; import it into the other, and vice versa. <--

Then you can find out by yourself, where the possible misunderstandings are. 

I have also done transfers. From and to reimported addresses, signing with different methods, etc.

**Suggestions 2:**
(you'll see these yourself, when you follow ^ suggestion 1)

* allow for a "path" right from the start. e.g. ParitySigner creates a "kusama address" as //kusama.   
But in polkadot.js-extension I can only get THAT address in 2 or 3 steps:  
First import the "import account from preexisting seed" mnemonic (but that address has 0 KSM because it was never used), then derive from that another key with path //kusama, 
and finally get to _the same address_ that was created on ParitySignerIdentity-->kusama   
(and then possibly delete the first imported one? But then no other derivation is possible, is it ??).

* in the derivation "derive new account" ... already show the RESULTING ADDRESS (that is my most important suggestion);
either once the lock is closed again on page "Add new account: 1/2";  
or when I have pressed "Create a derived account" and get to page "Add new account: 2/2", show it there.  
Because if you _show the address to me,_ I can compare that to the address I know, and I would immediately notice if I have made a mistake with the derivation path  //kusama//1/2    
Otherwise it's a lot of trial and error, deleting derived keys again, try anew etc.  

* random behaviour:  
if the SAME address exists via polkadot.js-extension=injected AND via "Add via Qr"=ParitySigner ...  
... then the latter is NOT AT ALL shown in https://polkadot.js.org/apps/#/accounts   
Only when then that address is deleted from the polkadot.js-extension ... then it reappears as ParitySigner address.   
Very possibly something that _not you_ but polkadot.js.org/apps has to think about.  
But perhaps you can talk to them how it could be done. Show both, and let the user choose? I don't know.   

* only design issues, but lead to reduced usability too: to narrow, too little space.
If the "given name" of a key is 2 lines long, the layout is a bit broken. Especially bad if derived key, and both name are long.   
Plus: None of the addresses are shown fully but are cut at approx 80% of their length. Just make the box a quarter wider.
Plus: Especially in the "open extension in new window" view ... just allow for any width?  

Are these suggestions useful?

I guess for the first two bullet points, I could have avoided all that, if I had created a "Parity Signer - Create Custom Path" address, and then choose an EMPTY PATH ?  Instead I went for for "add identity --> add network account --> kusama address" because that sounded intuitive.
I really don't know what is the best way to sync the approaches of all the key creating apps.  
Just be aware that (even if slightly) differing approaches will lead to newb confusion.  
And then possibly ... lost funds.   

Myself, I am simply happy to have tried it all out, and just with throwaway addresses, and only tiny amounts of KSM.   
I would recommend these 2-3 hours to anyone. First play, export, import, derive, send, be puzzled, understand - and only then send larger amounts of money. But I know that many many users are not like that.

Anyways, well done - kudos to all three teams: polkadot{.js} extension, polkadot.js.org/apps, and ParitySigner work together really well !
 

:+1:

**Comment by jacogr** [comment]
Thanks for all the suggestions, they are useful.

Just a small comment that can make your life easier on the seed add you can go `<mnemonic seed>//<derivation path>` in the input box, e.g. `<mnemonic>//kusama//01`. Yes, it needs to align with the rest of the UI and needs to be explicit/visible.

**Comment by drandreaskrueger** [comment]
:+1:

**Comment by Tbaut** [comment]
Closing as I think all suggestions have been implemented, or logged in dedicated issues.
Thanks again for this super valuable feedback.

- > allow for a "path" right from the start. e.g. ParitySigner creates a "kusama address" as //kusama.

Mentioned in https://github.com/polkadot-js/extension/issues/414#issuecomment-681633200 there's a hidden way to do this, it's an advanced feature and I just logged https://github.com/polkadot-js/extension/issues/579
We will not add the `//kusama` derivation per default. I think this would be too confusing at this point (Signer is for advanced users more than the extension is.)

- > in the derivation "derive new account" ... already show the RESULTING ADDRESS

Done

- > random behaviour, Very possibly something that not you but polkadot.js.org/apps has to think about.

This is indeed not related to the extension. Please log this to the apps repo if you think it's a problem.

- >  None of the addresses are shown fully but are cut at approx 80% of their length

Done

- > If the "given name" of a key is 2 lines long, the layout is a bit broken

logged in a dedicated issue https://github.com/polkadot-js/extension/issues/578
