### ISSUE TITLE
Accidentally rejected an app request for permission to access plugin. How to retrigger?

### ISSUE THREAD

**Issue by davidkohcw** [polkadot-js/extension#449]
Hi!

I went to "https://polkadot.js.org/apps/#/accounts" but accidentally clicked "Reject" when the app asked for permission to access the plugin.

I know see this error whenever I'm at the page even though I'm sure I have an account. What can I do to approve permission? 

![Screenshot 2020-09-10 at 1 39 36 AM](https://user-images.githubusercontent.com/15072849/92634234-9007b900-f306-11ea-85b9-bc051affa25f.png)

**Comment by jacogr** [comment]
It is not persisted, only kept in menu. So on chrome, just got to chrome://extensions and toggle the extension on/off to reload. (Same on Brave/Firefox via addons)

The hammer approach is restarting the browser.

We will have a "permissions management" settings to make this simpler, but don't have it yet.

**Comment by davidkohcw** [comment]
Thanks so much @jacogr . I've managed to get it approved.
