### ISSUE TITLE
Account export JSON contains address in Substrate format, regardless of what network (Kusama, Polkadot) was selected

### ISSUE THREAD

**Issue by antonkhvorov** [polkadot-js/extension#455]
**GIVEN:**
Account is created in extension, user wants to export the account via JSON
**EXPECTED**
Account is exported, Restore JSON contains all fields, including address in network format (Kusama prefix 02, Polkadot prefix 00)
**ACTUAL**
Account is exported, Restore JSON contains all fields, including address in substrate format (prefix 42)

Following issue: Other software, which is determining for which network account should be imported by the address in Restore JSON, failed to identify the network and importing account for wrong network.

**Comment by jacogr** [comment]
The metadata has the genesisHash for network (If set)

**Comment by antonkhvorov** [comment]
> The metadata has the genesisHash for network (If set). The address is certainly not a network indicator, it is an encoding of the AccountId.

I have similar question in different issue:
https://github.com/polkadot-js/common/issues/688#issuecomment-697982243

But as sum up -- maybe it is reasonable to name this field publicKey and store public key there to avoid confusion?

**Comment by jacogr** [comment]
Yes, the rename is going to happen with JSON format v4 along with stronger metadata typing information.

**Comment by antonkhvorov** [comment]
> Yes, the rename is going to happen with JSON format v4 along with stronger metadata typing information.

Awesome. Could you please take a look in my comment in another issue please?
https://github.com/polkadot-js/common/issues/688

**Comment by jacogr** [comment]
Closing.
