### ISSUE TITLE
Request: Increase the nonce for unconfirmed transactions to allow for signing multiple transactions in the same block

### ISSUE THREAD

**Issue by carumusan** [polkadot-js/extension#456]
This is more relevant for blockchains with long confirmation times such as Kulupu (60s). Not increasing the nonce causes transactions other than the first to error.

**Comment by carumusan** [comment]
Created an issue in polkadot-js/apps as well in case that is the more relevant location to fix: https://github.com/polkadot-js/apps/issues/3698

**Comment by jacogr** [comment]
The extension has no network connectivity. It only signs the payload as received. Will look at the different issue logged.
