### ISSUE TITLE
Allow network selection when importing an account from mnemonic seed

### ISSUE THREAD

**Issue by vjasterix** [polkadot-js/extension#457]
Caused quite a bit of confusion when trying to transfer DOT to my wallet. Until I realised the default was a substrate address. I think if its a polkadot extension, it should default to the polkadot address.

**Comment by Tbaut** [comment]
I think it would make sense in this case to add a dropdown menu when importing an account with mnemonic to select the network. Note that this can be changed later on when clicking the 3 dots right from an account.
