### ISSUE TITLE
Trying to sign arbitrary code leads to account is locked

### ISSUE THREAD

**Issue by FahdW** [polkadot-js/extension#460]
I tried using my account from the extension to sign arbitrary info. Every time i tried to execute a signing i would get an error saying the account is locked and i am unable to sign. Is there a prescribed way to sign arbitrary data?

**Comment by jacogr** [comment]
Could you take me through the steps your are using?

**Comment by FahdW** [comment]
const accounts = await web3Accounts();
    const userAccount = keyring.addExternal(accounts[0].address);
    const message = stringToU8a('this is our message');
    const signature = userAccount.pair.sign(message);
    const isValid = userAccount.pair.verify(message, signature);

I assumed keyring is not allowed to use an external account to sign messages. I am also assuming `api.sign` is the way to go but i am unsure how to go about it via api.sign.

**Comment by jacogr** [comment]
When you "addExternal" it is treated as a address book entry. So if really has no idea that it comes from an extension. To sign on an extension, you need to explicitly use the relevant method on the extension. (The extension itself keeps the keys)

Just looked at the README and it really doesn't document this, however -

```js
// retrieve the injector
const injector = await web3FromAddress('5DTestUPts3kjeXSTMyerHihn1uwMfLj8vU8sqF7qYrFabHE');

// sign via the injector
injector.signer
          .signRaw({
            address: currentPair.address,
            data: isHexData
              ? data
              : stringToHex(data),
            type: 'bytes'
          })
          .then(({ signature }) => console.log(signature))
          .catch(console.error);
```

**Comment by FahdW** [comment]
> When you "addExternal" it is treated as a address book entry. So if really has no idea that it comes from an extension. To sign on an extension, you need to explicitly use the relevant method on the extension. (The extension itself keeps the keys)
> 
> Just looked at the README and it really doesn't document this, however -
> 
> ```js
> // retrieve the injector
> const injector = await web3FromAddress('5DTestUPts3kjeXSTMyerHihn1uwMfLj8vU8sqF7qYrFabHE');
> 
> // sign via the injector
> injector.signer
>           .signRaw({
>             address: '5DTestUPts3kjeXSTMyerHihn1uwMfLj8vU8sqF7qYrFabHE',
>             data: isHexData
>               ? data
>               : stringToHex(data),
>             type: 'bytes'
>           })
>           .then(({ signature }) => console.log(signature))
>           .catch(console.error);
> ```

Thank you so much will try this shortly. Thanks for replying so quickly!

**Comment by jacogr** [comment]
Since you already retrieved the extensions, you can just use the entry retrieved via `web3Enable('...')` as the injector (the lookup is in the case of multiples)

**Comment by jacogr** [comment]
Closing.

**Comment by FahdW** [comment]
Thanks this works perfectly. Is there anyway to verify the signature or is the promise resolution sufficient?

**Comment by Tbaut** [comment]
If you want to verify the signature later (or on the back-end) you can do it using `signatureVerify` like so:
```js
import { signatureVerify } from '@polkadot/util-crypto';

signatureVerify(message, signature, publicKey).isValid
```

**Comment by FahdW** [comment]
Thanks @Tbaut that works great. Has a weird bug in lambdas but i am trying to sort that flow out

**Comment by Tbaut** [comment]
FWIW there's now an entry about that in the docs' cookbook https://polkadot.js.org/docs/extension/cookbook#sign-a-message
