### ISSUE TITLE
Add ErrorBoundary (as applicable)

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#469]
Wile https://github.com/polkadot-js/extension/issues/468 (based on description) seems like a background crash (???), the UI itself should never go "white page" or drop out. ErrorBoundary (as used in the apps UI) protects against that.

Need at least one for the authorization/signing where things may go wrong due to bad parsing.

**Comment by chevdor** [comment]
@Tbaut we can test quickly if you think you got a fix. Let me know once you are ready and I can confirm the fix... or not :)

**Comment by Tbaut** [comment]
Despite trying hard, I've not been able to reproduce #468 (testing heavily on chrome), and used subsocial in the past days on FF.
I sent to @chevdor the build with `ErrorBoundaries`.
