### ISSUE TITLE
Better sorting, not only by created

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#474]
Sorting in the extension also affects the exports, i.e. it is exported in the order displayed. However the current sorting inside the app is done on parent and then on creation only. My suggestion (open for adaptation) would be -

- top-level based on name - when same use creation timestamp
- derived accounts, based on actual name - when same, use path

Certainly would make my own life much easier.

**Comment by Tbaut** [comment]
I'll take a look at this. Should there be an option (in the dropdown?) or do we want to apply this first and then add an option if this wish is expressed by a user?

**Comment by jacogr** [comment]
I believe it should just be applied by default. Happy with some sorting options, cannot think of all combos off-hand, but generally try to keep things simple(r) here. AFAIK was the first person to complain...
