### ISSUE TITLE
chrome web store instance of polkadot{.js} extension is not returned in search on chrome web store.

### ISSUE THREAD

**Issue by ampersandi** [polkadot-js/extension#479]
there is a new offering displayed instead which emulates the extension with purported additional functionality that enables clearance of cookies and a fraudulent site blacklist.

**Comment by ampersandi** [comment]
![image](https://user-images.githubusercontent.com/68250498/95065722-28019280-074d-11eb-9f05-05f6bdca5b50.jpeg)

**Comment by ampersandi** [comment]
![Uploading 95065756...]

**Comment by ampersandi** [comment]
![Uploading 95065776...]

**Comment by Tbaut** [comment]
You are right, I couldn't find it by searching for "polkadot extension" or even only "polkadot". Although it's still listed: https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd?hl=en-GB&authuser=0

Should we change the name @jacogr and remove the curly braces?

**Comment by jacogr** [comment]
It is unlisted.

**Comment by Tbaut** [comment]
Understood, so what you experience @ampersandi is expected. The extension is only available when you directly link to it.
This is expected. The reason for this is that a listed extension is extremely slow to get updates, while an unlisted one can propagate updates within a couple days maximum. It is very unfortunate but this is something inherent to the chrome store.

**Comment by ampersandi** [comment]
i understand the situation, having experience in regression testing at enterprise level. 

i am mindful of those consumers that do not have the appropriate technological savvy to make informed choices when navigating into app libraries. 

i hope i have not wasted too much of your time.

**Comment by ampersandi** [comment]
> You are right, I couldn't find it by searching for "polkadot extension" or even only "polkadot". Although it's still available: https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd
> 
> Should we change the name @jacogr and remove the curly braces?

this incongruence was the red flag for me to bring the matter up. 

that my search returned nothing (other than the DOT wallet) wasn't concern quite enough, but the availability of the resource on the link you referenced made me consider that some third party may have been attempting to obfuscate the "official" developer extension.
