### ISSUE TITLE
The visibility icon seems actionnable (like the copy button) but it isn't

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#485]
2 possibilities:
- keep the current way of setting an account visible/invisible in the menu, the icon would only appear when not visible, clicking on it would make the account visible again.

- remove the visibility toggle from the menu setting, and show the eye icon on all accounts. Clicking on it would toggle the visibility. The obvious drawback of this solution is that it'll be a little heavier visually since we add another indicator.

![image](https://user-images.githubusercontent.com/33178835/95457916-cb32f180-0971-11eb-849d-81921c00018e.png)

What do you think @jacogr

**Comment by jacogr** [comment]
Was actually thinking along the same lines, i.e. click-to-toggle. The only reason why it was kept as-is was that it would be too easy to make it invisible via a misclick and then end up with support... have actually had a couple of those already. As it stands it is an explicit action.

**Comment by Tbaut** [comment]
> The only reason why it was kept as-is was that it would be too easy to make it invisible via a misclick and then end up with support...

good to know, maybe make the "non visible" a little more like red or something. Do I read correctly that you'd prefer the 2nd solution then?

**Comment by jacogr** [comment]
Yes, 100% - slightly heavier as suggested (we could just make visible very light so it doesn't detract), but consistent and not easily done by mistake.
