### ISSUE TITLE
Show an explicit error message upon signing reuqest with wrong password

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#494]
Right now the only pointer is that the password field is reset and the ticker is red.
This is a wrong password now:
![image](https://user-images.githubusercontent.com/33178835/95982509-7afbd980-0e20-11eb-8997-fa32b77a16bd.png)

**Comment by tomusdrw** [comment]
Is this already deployed? I recently run into this and only had an indication in the console (extension downloaded today from Chrome WebStore).

**Comment by Tbaut** [comment]
You guessed it, it's part of v0.35 that isn't out yet.
