### ISSUE TITLE
Move developer documentation polkadot.js.org/docs

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#498]
It is the one-place shop for all library docs

**Comment by Tbaut** [comment]
I'll familiarize myself with the doc and make the move and enhance if needed in the next days.

**Comment by jacogr** [comment]
Not much there... specifically looking at extension-dapp and you are actually a good candidate since you did actually use is as-is. So a getting started, this is how to use it, this is how to sign messages and this is how to make txs are what I'm after.

But Rome was not built in a day, so even if just the current (crappy) bare-bones is moved, it is a start. Can build from there.

**Comment by jacogr** [comment]
Closing, thank you!

**Comment by Tbaut** [comment]
Ah I thought I'd move things about `extension-inject`, or you don't think it's necessary?

**Comment by jacogr** [comment]
Happy to keep as-is for the time being - the community around that is tiny.

**Comment by Tbaut** [comment]
Alles klar. I'll add some more cookbook examples with the account sub in the next days.
