### ISSUE TITLE
Support ChainX Display Address Format

### ISSUE THREAD

**Issue by qinghuan-chain** [polkadot-js/extension#537]
I noticed that chrome extension has not released a new version for a long time.The latest code already supports the network configuration of ChainX.
When will the official version of the google chrome store be released? ChainX 2.0 will be launched at the end of this month.We hope to release a new version for support.
![image](https://user-images.githubusercontent.com/7252280/99040943-fe961b00-25c4-11eb-8e0b-ea6949982004.png)

**Comment by jacogr** [comment]
It is being tested and some PRs are still open. when ready, it will be published.

**Comment by qinghuan-chain** [comment]
> It is being tested and some PRs are still open. when ready, it will be published. No ETA.

ok，thanks. We will keep paying attention.

**Comment by Tbaut** [comment]
Closing. Please watch the releases, it'll be published on GitHub (you can do so by clicking on "watch" at the top right, then select custom > releases.)
