### ISSUE TITLE
Download the latest code to run an error

### ISSUE THREAD

**Issue by hero008** [polkadot-js/extension#567]
![image](https://user-images.githubusercontent.com/35803375/101617201-4fc1ef00-3a4b-11eb-8576-7bd137f9a9a7.png)
![image](https://user-images.githubusercontent.com/35803375/101617360-7f70f700-3a4b-11eb-946c-a6297d16a721.png)
![image](https://user-images.githubusercontent.com/35803375/101617806-0faf3c00-3a4c-11eb-92d2-7ed834e981ea.png)

**Comment by Tbaut** [comment]
It looks like you are missing the external dependencies.
To run the latest code, please clone this repository, and follow the instructions available https://github.com/polkadot-js/extension#development-version

**Comment by jacogr** [comment]
There has been some changes in `polkadot-js/ui`, specifically this - https://github.com/polkadot-js/ui/pull/414

So if the dependencies are updated by yarn automatically, there may be breakages. (I'm in the process of rolling the above out to the dependent repos. You can ensure yarn installs the versions as per lockfile with `yarn --immutable`, ensuring it doesn't try to helpfully upgrade)
