### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by RudarDaman** [polkadot-js/extension#571]
Please refer to the image attached for more details
![Screenshot from 2020-12-10 14-16-05](https://user-images.githubusercontent.com/15893684/101748776-fca37700-3af2-11eb-8739-f6c4acecb4f1.png)

**Comment by Tbaut** [comment]
Would you mind giving a bit of context to your issue. What did you do to end up in this situation?

**Comment by RudarDaman** [comment]
I have installed **@polkadot/extension-dapp** dependency. Now I am using **import { web3Enable } from "@polkadot/extension-dapp";** in react application. This import statement generates the above error.

**Comment by jacogr** [comment]
The problematic line is this - https://github.com/polkadot-js/extension/blob/master/packages/extension-dapp/src/index.ts#L11 which compiles down to `const win = window;`

So in your case, it seems Webpack doesn't known about `window`, which should always be there for a browser application.

Google has a lot of info how to configure Webpack properly to ensure browser apps always have a "window", the first result that pops up for me was this one - https://stackoverflow.com/questions/55849240/window-is-not-defined-after-a-build-with-webpack

**Comment by RudarDaman** [comment]
@jacogr window is already defined in my react application. When I am writing **console.log(window)**, the whole window object is going to log in the browser's console properly.

**Comment by jacogr** [comment]
As per the above message, the window object is not available in the bundle itself to that package. There is nothing code-wise that can be done here, it is meant to be used in a browser that has the `window` object. So it is a configuration issue on Webpack. 

YMMV, this is what the apps UI uses (there is a combo of various requirements that goes in) - https://github.com/polkadot-js/apps/blob/master/packages/apps/webpack.base.config.js#L178

**Comment by RudarDaman** [comment]
@jacogr I am using Next.js with react. No webpack is used in my application.
To access `window` object in Next.js project we need to define window in `useEffect` hook. I am already using `web3Enable` of Polkadot extension inside useEffect react hook.

**Comment by jacogr** [comment]
Ok, that makes sense - `@polkadot/extension-dapp` is not  server-side module, it assumes it is executed client-side only. 

So your only option would be to do the `import` inside the effect to ensure it doesn't get run on the server-side. something like -

```js
useEffect(() => {
  const ed = await import('@polkadot/extension-dapp');
  ...
}, []);
```

**Comment by RudarDaman** [comment]
Yes, this works fine for me.
Thanks a lot for the resolution @jacogr.
