### ISSUE TITLE
Implement Provider for extension injection

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#58]

**Comment by axelchalon** [comment]
What is the benefit of injecting a PostMessage provider, that sends the requests to the extension, which forwards them to the node (using WsProvider); over injecting the WsProvider directly?

**Comment by jacogr** [comment]
You don't want to run anything `@polkadot/api` related in the UI or injection threads. Actually, if we had to do that atm, you would end up with the dreaded "multiple packages detected" message.

Additionally, you want to be able to have max flexibility on the provider, if you need to -

- provide access for only some time
- kill it immediately at any point at the user's discression
- provide control over methods that are available (i.e. allow queries, no submission)
- share the provider (not applicable for extension, maybe for metadata, but certainly for others)

These are all things that can be done (certainly not suggesting it for a minimal-initial version)

**Comment by jacogr** [comment]
Done.
