### ISSUE TITLE
Error initializing polkadot-js: The source http://localhost:3000/ is not allowed to interact with this extension

### ISSUE THREAD

**Issue by spaceforce-dev** [polkadot-js/extension#584]
When i run await web3Enable('...'); for the first time a popup appears that permits user to connect their extension to the dapp, i accept and i connect and everything is ok. That part works fine.

But my issue is if you reject that first request to connect, i cant find a way to give the user another chance to connect. I need it to popup again but it just says it's not allowed. On Metamask if you reject it can popup again but here it seems to be blocked, how can i reinitialise the enable popup to appear?

Thanks for the help!

**Comment by jacogr** [comment]
See #85 - it will in a release relatively soon since it has bubbled to the top lately. 

Atm, the only way is to close/re-open the browser since the access is only kept in memory (or disable/enable the extension is e.g. chrome://extensions - which generally is the faster route)

**Comment by spaceforce-dev** [comment]
Ok, Thanks for the info. 

We will be on the look out for that update.  👍

**Comment by Tbaut** [comment]
closing as it's a duplicate, and the fix will land soon(TM)
