### ISSUE TITLE
Name display on creating new account

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#585]
On creating a new account, after entering the name and tab-ing to the password, the name doesn't show in the actual top account bar. It really should upon changing (maybe not while typing, but that it first-prize)

![image](https://user-images.githubusercontent.com/1424473/102028599-5afa7f00-3dab-11eb-9e35-97a6df744c7e.png)

Additionally, some small funny - when forgetting, the name immediate goes to "<unknown>", but it takes a second or 2 before the actual account is removed. Should maybe just check and not let it disappear immediately and ensure we have a spinner-status on the button. (Actually testing again seems to be fine, spinner would still be good...)

**Comment by Tbaut** [comment]
I saw that the forget/export also don't have nice error when the password is wrong, I'll handle that all in a separate PR.
