### ISSUE TITLE
web3Enable: Enabled 0 extensions

### ISSUE THREAD

**Issue by usetech-llc** [polkadot-js/extension#590]
The library does not see Polkadot{.js} injected intermittently (once every 2-3 page reloads).

Version: "@polkadot/extension-dapp": "0.34.1"

The issue can be seen on this SubstraPunks page, for example:
https://ipfs-gateway.usetech.com/ipns/QmaMtDqE9nhMX9RQLTpaCboqg7bqkb6Gi67iCKMe8NDpCE/details.html?id=1972

**Comment by jacogr** [comment]
Ensue that you only call web3Enable after the page is loaded. Then extension itself does as much as it can, waiting for page load  after injection.

However if in your entry you call `web3Enable` top-level (i.e. the above example doesn't help, you need to show actual code), it will fail intermittently since it operates before the extension code is injected and runs.

**Comment by usetech-llc** [comment]
Here is the code: https://github.com/usetech-llc/substrapunks/blob/da6587575da45dafbe7d05ae4d62087ce7efa516/public/js/details.js#L620

`nft.checkExtension` that calls `web3Enable` is called in window.onload.

Implementation of checkExtension:
https://github.com/usetech-llc/substrapunks/blob/da6587575da45dafbe7d05ae4d62087ce7efa516/scripts/nft.js#L121

**Comment by jacogr** [comment]
So the extension does a couple of things to ensure it goes in as early as possible -

- It runs at the earlier allowed time, document start, here https://github.com/polkadot-js/extension/blob/master/packages/extension/manifest.json#L20
- it will only resolve on either the completed or load event - https://github.com/polkadot-js/extension/blob/master/packages/extension-dapp/src/util.ts#L4 (ensuring both sides get ready)

So in the above it depends on when either side gets their load events. Intermittent means the ordering is different as the browser executes.

**Comment by Tbaut** [comment]
closing as it's been answered.
