### ISSUE TITLE
Importing an external account doesn't show the address or name

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#607]
How to reproduce:
Import from a Qr code > scan Qr code --> no address or name displayed

**Comment by jacogr** [comment]
Weird. This has not changed in >6 months. And when it did, pretty sure that the libs here were updated. Hopefully it is something small and not a 6 months old bug.

**Comment by Tbaut** [comment]
it's actually not a bug, rather something that was never really implemented.
