### ISSUE TITLE
Can't add password-derived account 

### ISSUE THREAD

**Issue by kirushik** [polkadot-js/extension#613]
I'm using PolkadotJS extension `0.36.1` in Firefox.
I want to add an account there which uses a password-based derivation from seed.

To do that I first add a "bare" account with my seed phrase (since there's no option to add the password-derived account right away, unlike PolkadotJS webapp or Parity Signer) — and then try to add `///password` as a derivation path from the "Derive new account" menu on my bare account.

Instead of adding my address, extension complains about "Incorrect derivation path" and doesn't let me to add the subaccount (while both `subkey` and PolkadotJS are deriving the same address for this case.)

**Comment by kirushik** [comment]
For example, seed phrase `april leaf kit orphan galaxy stumble lamp speed erode edit salmon amazing` with a password `pa$$word` should lead to an address `5F4wU5oAokHBQPadLwZWeu7DwoRbNEMZHWfvWZajGQcSmtqX`.

**Comment by jacogr** [comment]
Why don't you just add the password when creation the account? i.e. use `april leaf kit orphan galaxy stumble lamp speed erode edit salmon amazing///password` as the seed.

**Comment by Tbaut** [comment]
This is linked to https://github.com/polkadot-js/extension/issues/579

The feature mentioned by Jaco is hidden, but you can add the derivation directly at the end of the mnemonic as a workaround. I'll come to this feature soon though, prob in the next days :)

**Comment by kirushik** [comment]
> that is actually a "full suri" input as opposed to seed-only

That's awesome to know (and is by far not obvious), thanks for the hint!

@Tbaut would really appreciate if this would can improved.

**Comment by Tbaut** [comment]
will get to #579 soon. closing.
