### ISSUE TITLE
Polymath wallet interfering with extension?

### ISSUE THREAD

**Issue by anjaw3f** [polkadot-js/extension#618]
A user reported that his polkadot.js extension only worked once he removed the Polymath Polymesh extension:

He had received the following error when trying to stake: 
_utility.batchAll
The source https://polkadot.js.org/apps/#/explorer has not been enabled yet_

I asked him to refresh the page to get the confirmation pop-up and allow the extension access, and this is what happened:

"Yes I was getting this pop-up and allowed the app to connect but it didn't work. That being said, another app was also giving me a pop-up. It's the Polymesh wallet (chrome extension) for Polymath token.
[..]
I went and deleted the polymesh wallet and it seems to have solved the issue. I was finaly able to stake my DOTs."

**Comment by jacogr** [comment]
If he had the same address in both extensions, it could happen - i.e. the apps UI will pick the first one. The first error is since the page has not been enabled yet.

**Comment by jacogr** [comment]
Closed in linked PR.
