### ISSUE TITLE
web3FromAddress should accept ss58Format as optional parameter

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/extension#643]
I have list of addresses

```js
this.importedAccounts = await web3Accounts({ ss58Format: this.ss58Format || 42 });
```

then when I want to use address from `this.importedAccounts`
I got following error.

```js
index.js?077d:199 Uncaught (in promise) Error: web3FromAddress: Unable to find injected Fksmad33PFxhrQXNYPPJozgWrv82zuFLvXK7Rh8m1xQhe98
    at web3FromAddress
```

however when I pass the same address in `42` ss58Format I got correct result.

**Comment by jacogr** [comment]
It does a U8a compare to return, see https://github.com/polkadot-js/extension/blob/master/packages/extension-dapp/src/index.ts#L193
