### ISSUE TITLE
Question: Why ledger accounts must be associated with a chain?

### ISSUE THREAD

**Issue by remon-nashid** [polkadot-js/extension#645]
First of all, thanks for adding the current simple and effective integration with Ledger nano! It works flawlessly.

But unlike accounts created from seed, or restored from JSON, accounts imported from a Ledger device must have a network. I wonder why is that necessary, and whether there's a way to use a ledger account across multiple chains. Perhaps the most prevalent use case is to use an account with both mainnet and testnet(s).

**Comment by jacogr** [comment]
The Ledger app itself comes in 4 variants that support Substrate chains - Kusama, Polkadot, Polymesh & Dock.

On each of these the root derivation path is formed with the actual chainId, e.g. it is `m/<chainId>'/<accountIndex>'/0'/<addressIndex>'`

While you can choose the account/address indexes, the chainId is fixed to the specific app. If you transfer on another network, the Ledger won't be able to transfer funds out of it.

**Comment by remon-nashid** [comment]
Makes sense. Thanks @jacogr !
