### ISSUE TITLE
Could you release the latest @polkadot/extension-dapp

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/extension#651]
Current @polkadot/extension-dapp version in npm is `0.36.1` which depend on `"@polkadot/util-crypto": "^5.2.3"`. It's now conflict with @polkadot/api's dependent `"@polkadot/util-crypto": "^5.6.1",`.

My react app will report a warning for multiple instances. Appreciated if you can release @polkadot/extension-dapp.

**Comment by jacogr** [comment]
A release of the extension was planned for today. So if everything goes will well the final checks it should go out.

**Comment by jacogr** [comment]
https://github.com/polkadot-js/extension/releases/tag/v0.37.1

The util/util-crypto is now peer dependencies as well, so it _should_ also yield a better experience. 

(In the apps UI always use the package.json resolutions fields to just pin everything to latest - but in that case we always run betas of the libs as well, so it is really needed to ensure everything gets tested)

**Comment by wliyongfeng** [comment]
See it, thanks.
