### ISSUE TITLE
Ledger Extension With Two Accounts - Can't Select

### ISSUE THREAD

**Issue by molinamos** [polkadot-js/extension#654]
Can't select two different accounts made from ledger. 

There is on drop down to link which one to my extension, only shows one, the one I already have added.

**Comment by Tbaut** [comment]
Can you tell
- what ledger device you have
- how you create 2 accounts on the ledger

Thanks

**Comment by molinamos** [comment]
I have the ledger x.

By two accounts on ledger, I mean two accounts made on the polkadot js website via ledger if that makes sense. 

But I can only link one of them to my polkadotjs extension.

**Comment by Tbaut** [comment]
Thanks. I'm not sure how much the X differs with the S (which is the one I have).
Polkadot-js apps does not work any differently than the extension from what I can tell. You can select the "Account index" and "Address offset" and therefore have several different accounts displayed in the extension, all linked to the same device.

**Comment by molinamos** [comment]
@Tbaut I see what you mean now. I never typed in a name so it never showed any options for account type or index. Maybe it would be best to show that by default or change it so its greyed out until you type a name in. At least I think that would have helped me in the confusion.

**Comment by Tbaut** [comment]
Ah, interesting, thanks for the feedback. I would think that this is part of the flow, you enter what you are asked for (a name), and then you can proceed to the next step. We should keep this experience in mind and log an issue if other users stumble into this problem.
