### ISSUE TITLE
[FEATURE REQUEST] Include a "isHardware" tag in metadata for DApps to use

### ISSUE THREAD

**Issue by saumyakaran** [polkadot-js/extension#655]
I'm looking for a way to automagically alter UX for users if their account is imported from a hardware device.

Is there any way to do this currently? I can't find anything in the metadata when using the extension for authorization.

If this doesn't exist yet, is there any possible workaround until this is built?

**Comment by jacogr** [comment]
This is unlikely to be added - the metadata from the extension is limited on purpose to try and not leak any information. (It already provides too much, i.e. the `genesisHash` filtering is not done extension-side)

**Comment by saumyakaran** [comment]
Ah I see. Thanks for the reply @jacogr -- just curious, what problem/vulnerability might the "isHardware" tag cause?

**Comment by jacogr** [comment]
There is no vulnerability - however, in all honesty we already leak too much information about the user and his accounts -

- which chains it is available on
- the actual address (this is where Ethereum does a better job with the default address, it never actually need to get to the dapp)
- the metadata information (well, some - what the user calls it, when it was created)

This is more about privacy/tracking as opposed to the flipside of the coin which is security. In a perfect world, nothing about the user should be known.

**Comment by saumyakaran** [comment]
Ah, got it! Thank you very much for the response. 🙏🏻
