### ISSUE TITLE
Wallet ordering changes after network switch

### ISSUE THREAD

**Issue by chrisli30** [polkadot-js/extension#657]
Found this behavior when switching networks. Is it considered a bug or by design?

1. Initally I have 2 accounts on Kusama and Polkadot. I named them "1st account" and "2nd account" for display purpose.
![image](https://user-images.githubusercontent.com/2616844/108582229-ac147b00-72e6-11eb-8805-5434f306d718.png)

2. After switching the network of the "2nd account" to Acala, the list order changed. The "2nd account" goes to the first place.
![image](https://user-images.githubusercontent.com/2616844/108582231-afa80200-72e6-11eb-8acd-50a6fa43d965.png)

3. After switching the network of the "2nd account" back to Polkadot, the wallet came back into place(2nd).
![image](https://user-images.githubusercontent.com/2616844/108582235-b33b8900-72e6-11eb-89c7-5482bd4d7749.png)

4. I found that the order changes only between groups. Switching network within a group will not change the order. 
    - Group 1: Polkadot and Kusama
    - Group 2: all other networks

It seems to be a small change to fix the ordering. If it's a bug I can try to address it.

**Comment by jacogr** [comment]
It orders by network, then creation date. However on the creation date derived accounts would also be kept with their parents.

**Comment by chrisli30** [comment]
> It orders by network, then creation date. However on the creation date derived accounts would also be kept with their parents.

Hmm, I see. Creation timestamp of an account can't be changed, but network can. That's why the ordering is different after the network switch.

My suggestion is to order using the creation time of the account(but not their parent's), so the order doesn't change. Current behavior felt a little strange because I couldn't find the account for a few seconds after network switch.

If this is be design, we can close this issue.

**Comment by jacogr** [comment]
With 2-3 accounts, it makes sense. When you have 10's across multiple networks, the current behavior is the correct one since it is properly categorized and ordered based on actual links.

It was done by design - the old functionality jut ordered by timestamp and made it impossible to use with a large number of accounts.

**Comment by chrisli30** [comment]
Okay, got it. That's true.
