### ISSUE TITLE
How to detect if Polkadot  Extension is enabled?

### ISSUE THREAD

**Issue by ntduan** [polkadot-js/extension#658]
I don't want the polkadot extension to pop up an authorization box when the user enters the page. 

I would like to be able to get the status of the authorization. That way, when there is no authorization, I can click the button to get authorization, and when there is authorization, it will automatically connect to polkadot extension.

In metamask, I can use the global variable `ethereum.selectedAddress` to check if the user is authorized.

**Comment by ntduan** [comment]
If there is no way to know via polkadot extension, I would like to record a value in localstorage to indicate whether the user is authorized or not.

But the user's authorization doesn't seem to be permanent. I would like to know the rules for authorization expiration.

**Comment by jacogr** [comment]
The auth is in the user's control, he can enable/disable sites via the "Manage Websites" option. (There used to be an expiry, but now it is fully user-controlled)
