### ISSUE TITLE
No way to catch Polkadot extension initialization errors

### ISSUE THREAD

**Issue by ntduan** [polkadot-js/extension#659]
An error is thrown when the user refuses to deny authorization to the site. However, if you use web3Enable for authorization, there is no way to catch the error at the upper level. This is because the error is not continued to be thrown here.

https://github.com/polkadot-js/extension/blob/master/packages/extension-dapp/src/index.ts#L53

**Comment by jacogr** [comment]
There can be multiple extensions - it does not make sense rejecting on all when one of them is not available. So if denied, it does not appear in the list. 

Additionally there is no reason the dapp should be able to peek in on the User preferences - all it needs to know is what is available.
