### ISSUE TITLE
Rich method display

### ISSUE THREAD

**Issue by Swader** [polkadot-js/extension#671]
Related to #417 

I notice that when I send a TX on a live Kusama, I get nice descriptions of what I'm calling:

![image](https://user-images.githubusercontent.com/1430603/110122428-e8080f80-7dbf-11eb-8122-3f36941da448.png)

When doing the same on a local version of Kusama in dev mode, I get:

![image](https://user-images.githubusercontent.com/1430603/110122468-f5bd9500-7dbf-11eb-925f-3edfa481bd77.png)

What's the difference?

**Comment by jacogr** [comment]
Metadata is unknown on the dev version. It maps per genesis through to the metadata.

**Comment by Swader** [comment]
Indeed - is there a best way to inject metadata along with a TX to render it properly?

**Comment by jacogr** [comment]
Metadata cannot be injected alongside, the extension only gets the actual payload data and is itself responsible for the decoding against the metadata it does have. (If it did get both at the same time it would be trivial to fake transactions)

**Comment by Swader** [comment]
I understand. We'll work with it as is then.

**Comment by jacogr** [comment]
You can potentially with a small apps UI hack (running it locally), inject. So just remove the `isDevelopment` check here -

https://github.com/polkadot-js/apps/blob/master/packages/page-settings/src/useExtensions.ts#L164

```js
  return useMemo(
    () => !isApiReady || !all
      ? EMPTY_STATE
      : filterAll(api, all),
    [all, api, isApiReady]
  );
```

**Comment by Swader** [comment]
Not using apps, just implementing extension on a separate site, but thanks

**Comment by jacogr** [comment]
Well, apps is the thing that does the metadata update - so if you want to have the metadata in the extension... that is how you update it.
