### ISSUE TITLE
Catch cancelled transactions in dapp

### ISSUE THREAD

**Issue by jodator** [polkadot-js/extension#674]
I've noticed that there's no way of handling transaction cancellation. For instance, if the user selects "cancel" instead of "sign the transaction" the extension sends a "Canceled" error which [is not handled](https://github.com/polkadot-js/extension/blob/297b2af14c68574b24bb8fdeda2208c473eccf43/packages/extension/src/page.ts#L10-L22):

![Screenshot 2021-03-08 at 14 04 01](https://user-images.githubusercontent.com/247363/110325225-5d215200-8017-11eb-9292-36433d235f83.png)

This error is not propagated by the API and thus we can't detect that this happened.

Is there any way to tell if the transaction was canceled by the user in the extension.

**Comment by jacogr** [comment]
Not sure what you mean, e.g. in the apps UI, the error is correctly passed up as "Cancelled" -

![image](https://user-images.githubusercontent.com/1424473/110326474-fef56e80-8018-11eb-9050-76f2e4265732.png)

**Comment by jodator** [comment]
OH, I see that. Looks like this is only logged to the console (the same happens with apps). I'm also using a bit older API so maybe it is the case that I'm not able to catch this error when using `tx.signAndSend()`.  
  
So I'm closing this as invalid. Thanks!
