### ISSUE TITLE
Kusama Configured Account Displays Address in Polkadot Format

### ISSUE THREAD

**Issue by adamsteeber** [polkadot-js/extension#677]
If you configure an account via the extension to be on the Kusama relay chain, the address will appear everywhere (in the extension, on the portal, etc.) in polkadot format.

**Comment by jacogr** [comment]
In the apps UI, the address shows up based on your apps UI settings -

- apps UI, under settings, ensure it is set to "display for connected node"
- in the extension, if you attached it to a chain, it will show in the chain's format, e.g 

![image](https://user-images.githubusercontent.com/1424473/110916026-a4aa2580-8318-11eb-82d8-3101824abd8b.png)

If not attached to a chain, it will display in the format under settings
