### ISSUE TITLE
Chrome extension 0.37.1 error message

### ISSUE THREAD

**Issue by repsorp** [polkadot-js/extension#678]
Ubuntu 20.10
Chromium 91.0.4442.4
polkadot{.js} extension 0.37.1

```
Errors:
FATAL: Unable to initialize @polkadot/wasm-crypto
Error: WebAssembly is not available in your environment

```

The extension no longer displays the account ; it must be opened in a new window to display it.

![polka](https://user-images.githubusercontent.com/6297032/111334239-ac006480-8673-11eb-88e5-403bc6171344.png)

**Comment by jacogr** [comment]
In chrome & FF it is fine. In Chromium (last version as of 45 mins ago) it does the same for me - I'm on a Mac.
