### ISSUE TITLE
polkadot.js doesn't see accounts in extension

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/extension#679]
A couple of users have reported that Chrome doesn't see the accounts in the extension. I suggested updating Chrome but that didn't fix it. 

They get the message that the extension is there but it has no accounts to inject, while the accounts exist in the extension as usual.

I've recommended as a troubleshooting step to reinstall the extension and restore the accounts. We'll see if that fixes it.

**Comment by jacogr** [comment]
Which browsers? Which OS?

**Comment by michalisFr** [comment]
Hey Jaco.

It's Chrome in both cases and from what I can tell from their screenshots, Windows 7.

Let me know if you need more information and I can get back to them and request them.

**Comment by repsorp** [comment]
Did you try "Open extension in new window", "Manage website access" then make sure that "polkadot.js.org" or any other desired website is checked as allowed.

**Comment by michalisFr** [comment]
I did not. I will ask about it, although I find it hard that they disabled this since both are not technical. This is enabled by default, right? Good tip though! Thanks!

**Comment by michalisFr** [comment]
An update on this:
- For both users polkadot.js.org was not allowed to connect to the extension. This was the case from the beginning. Probably the users didn't allow access when they first installed the extension.
- However, after enabling it they still couldn't see the account in polkadot.js and one user reported the UI got stuck in "Retrieving data"
- For this user a metadata update was needed but it didn't solve the issue.
- Both users had another account on polkadot.js. One reported it was missing after, but not sure if it's relevant.

I suggested to both to reinstall the extension, but haven't heard back so perhaps that worked.

Chrome version: Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by jacogr** [comment]
Same exact chrome version as me (which is latest).

**Comment by michalisFr** [comment]
I have confirmation from one of the users that reinstalling the extension fixed the issue. Perhaps if you reject access the first time then this creates an issue afterwards?

I tried to reproduce in Firefox (install extension, create account, go to polkadot.js and reject access, then allow access) but I couldn't. It worked as expected. I have too many accounts in Chrome to reinstall the extension. 😁

**Comment by jacogr** [comment]
The next version will have an import all and export all function :)

**Comment by michalisFr** [comment]
Yeah, I mentioned in my responses that they need to refresh the page and I believe they confirmed they did.

Anyway, when the mass export/import functionality is ready I'll give it a go and see if I can reproduce, but since we haven't seen this issue again I say we can close it for now.

Btw @jacogr I've sent you a DM in Element. I want your input about an idea for the extension. If you have some spare time, I'd love to tell you about it and see if it's feasible.
