### ISSUE TITLE
Re-genesis chain - account matching

### ISSUE THREAD

**Issue by jak-pan** [polkadot-js/extension#687]
We're currently in the process of re-genesis due to choosing 10minute epoch time in the begining of our testnet which is probably going to be a problem. 

https://github.com/galacticcouncil/HydraDX-node/issues/191

We know that currently chains are identified by the genesis hash. We'd like to avoid confusion of having multiple chains show up in polkadot.js extension for basically the same chain. Is there any way we could amend this similar to Kusama when it went from cc1 to the last iteration? 

We currently have more than 2600 unique addresses on-chain from the LBP so this would require significant coordination effort at this stage.

**Comment by jacogr** [comment]
Look here, where Kusama did the same - https://github.com/polkadot-js/common/blob/master/packages/networks/src/index.ts#L47-L63

Entry 0 is the latest (CC3 in the case of Kusma), Entry 2 (last, CC1) is the earliest.

**Comment by jak-pan** [comment]
> Look here, where Kusama did the same - https://github.com/polkadot-js/common/blob/master/packages/networks/src/index.ts#L47-L63
> 
> Entry 0 is the latest (CC3 in the case of Kusma), Entry 2 (last one, indicates CC1) is the earliest. So the keyring will try against all of these and when setting, will always grab the latest (index 0).
> 
> So only thing that would be required (after an update there) is a bump of the extension in-store.

Perfect! Thank you! We're on it then as I know the process with the store can be a little bit lengthy.

**Comment by jak-pan** [comment]
@jacogr We're dealing with one chicken-egg problem. 

If we want to do re-genesis, we'll need genesis hash of the new chain to be a part of polkadot-js/common but at the same time, we need the latest state from the old node to be able to create it. So that either means:
1. Stopping the old chain, generating new state, publishing the new genesis hash to polkadot-js/common, waiting for extension update, then starting chain. We'll end up with quite a long blackout. Do you have any idea about how long it could take? I have experience that it takes days to get updated and to propagate new extension (people also probably need to restart browsers)
2. Starting immediately after stopping, some people would import metadata with same name of the chain (or we could name it differently like Snakenet gen2) if they do something with the chain in the meantime until it gets merged, they'll have 2 chain types. My question is what happens after that with these? Will they need to switch back to the original? Will it work with both Snakenet 2 and original one?
3. Going in with the new chain id/name and new hash - this means coordinating and explaining 2500+people that they need to switch chains again to be able to use it.
4. ??? any better ideas?

**Comment by gww-parity** [comment]
maybe crazy, but, what about next block after regenesis block to contain new genesis hash?

Therefore in case of regenesis on `n`th block, someone following old chain, and on `n+1` block would get new genesis, and could switch?

**Comment by jak-pan** [comment]
> maybe crazy, but, what about next block after regenesis block to contain new genesis hash?
> 
> Therefore in case of regenesis on `n`th block, someone following old chain, and on `n+1` block would get new genesis, and could switch?

AFAIK this is not possible currently. But that would be cool. See https://github.com/paritytech/substrate/issues/7458 for more info?

**Comment by jacogr** [comment]
The swap is not that bad. 

- if you have old and new genesis in the networks the apps UI will match both
- the Extension publish (since it is unlisted) doesn’t take weeks (rather days/hours)

**Comment by jak-pan** [comment]
@jacogr when do you think we can expect this to land in the chrome store? We'd like to plan an announcement to start staking 🚀🔥

**Comment by jacogr** [comment]
There should be no stopping you. Having both the old/new genesis available in the apps UI (which actually determines which accounts are used), is all that is needed -

- the extension can bump the metadata via the apps UI
- apps UI will always both both genesis accounts to the same chain (hence the range)

**Comment by jak-pan** [comment]
Ah... I would have promised this didn't work. We just updated runtime from version 7 -> 8 and now the metadata update is showing 7 -> 8 before it was confused. And also I was confused because my extension looks like this because of development effort. (Would be cool to see part of genesisHash in the UI or remove chains?)
<img width="244" alt="Screenshot 2021-04-18 at 11 48 23" src="https://user-images.githubusercontent.com/3409250/115141361-1d994d00-a03c-11eb-96c4-1aa18f57c0b8.png">

And it asked me to update metadata for Snakenet Gen2 so I thought it didn't work but it indeed works in the UI.

I also have second extension where it's better

<img width="246" alt="Screenshot 2021-04-18 at 11 50 39" src="https://user-images.githubusercontent.com/3409250/115141408-5507f980-a03c-11eb-87b0-092cb1536e2a.png">

So I guess after the update of extension the gen1 and gen2 will be merged or do they stay as separate?

**Comment by jacogr** [comment]
They stay as separate... I believe...

The issue you have highlighted here is that (atm) there is no way of clearing chains you have added. 

I‘ll ponder to see if there is a (quick, harmless) way of merging the 2 - it should be painless since we just need an extra check against the known genesis.

**Comment by jak-pan** [comment]
We're up and running. Do we want to keep this for merging the accounts in extension or do we close this? :)

**Comment by jacogr** [comment]
We can close this one. I will log the other one.
