### ISSUE TITLE
Populate account source for dApps

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/extension#688]
I would like to add support for [Ledger on KodaDot](https://github.com/kodadot/nft-gallery/issues/218), however, `batch` transactions don't work on this HW wallet. 
Therefore I would like to make special changes on the UI side witch splits batch into `n` separated transactions.

The problem is face is that attribute `source` of `meta` object is always equal to `polkadot-js`.
I would like to propose a new field that could tell us the account root source. 

Image below shows three accounts I would expect the following response `['qr', 'extension', 'ledger']`
<img width="101" alt="Screenshot 2021-04-02 at 15 14 00" src="https://user-images.githubusercontent.com/22471030/113418619-26481d00-93c6-11eb-9717-aee117c82ca2.png">

**Comment by jacogr** [comment]
This has been raised before, as mentioned in a previous issue (recently closed), we already leak too much account info (compared to other known environments) and would certainly not like to expand it.

**Comment by vikiival** [comment]
>  we already leak too much account info

I agree that's why I would like to have an opt-in toggle button (with a warning text)

**Comment by gre** [comment]
Hi @vikiival , Hi @jacogr, I'm @gre, tech lead on Ledger Live / maintainer on ledgerjs stack too.

My understanding of @vikiival 's usecase is to have more information regarding final wallet's capabilities, and specifically **if the wallet is supporting batch transactions**. As of today, Ledger Polkadot/Kodadot apps do not support "batch" transactions. This might change in future but for now it's the current state.

Would it be possible for dapps to access this capability information?

I imagine dapps could access a few limited information (address for instance) and what is the "environment" the account is on. To be determined what is "environment" but it could be just "it's a ledger device" but actually I think it makes more sense to get to the "raw" information that is the idea of "capabilities" so the dapps can feature detect things and in future, the extension just need to manage what each 'signer' supports as feature and expose it.

Does it make sense?

Thanks a lot and have a good sunday.

**Comment by gre** [comment]
@jacogr any thoughts about this? Thanks

**Comment by jacogr** [comment]
The reality is that the Ledger apps should really support this. It is a slippery slope trying to work around incomplete implementations, which may change. 

As for batch support, the ZondaX team is working on it.

**Comment by vikiival** [comment]
Hey @jacogr, 
do you know about any progress ?

**Comment by jacogr** [comment]
Please follow-up with the ZondaX team as for full support (proxy was another issue that was mentioned today in the same line for Ledger), I don't follow their repos at all.
