### ISSUE TITLE
Closing extension popup doesn't fire a callback

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/extension#690]
When I click `Cancel` on the extension popup folloowing `signAndSend` I get correct error callback, but if I close the popup by clicking small close (`x`) button on the popup, no callback is fired.

Is it possible to fire a callback on closing popup by any means?

**Comment by jacogr** [comment]
Closing doesn’t mean it is done and will not be signed. The transaction is still available in the extension. So clicking on the extension will show the transaction for signing. 

Cancel however does remove it.

**Comment by Yuripetusko** [comment]
Thanks!
