### ISSUE TITLE
Feature Request:  add custom chain configuration from the extension.

### ISSUE THREAD

**Issue by hbulgarini** [polkadot-js/extension#692]
It would be nice to have the chance to add custom chain configuration from the extension so we can create specific accounts for that custom chain loaded.

**Comment by jacogr** [comment]
Use the apps UI to inject the chain - 

- go to Settings
- select the Metadata tab
- update the extension

Once done, the chain is available. (Does not operate on dev chains, only live + test)

A example of Rococo added (metadata, name, colors & types) -

![image](https://user-images.githubusercontent.com/1424473/113972886-b5788900-983b-11eb-9412-ea71f1451a2e.png)

**Comment by jacogr** [comment]
Use the apps UI to inject the chain - 

- go to Settings
- select the Metadata tab
- update the extension

Once done, the chain is available. (Does not operate on dev chains, only live + test)

A example of Rococo added (metadata, name, colors & types) -

![image](https://user-images.githubusercontent.com/1424473/113972886-b5788900-983b-11eb-9412-ea71f1451a2e.png)

**Comment by jacogr** [comment]
Use the apps UI to inject the chain - 

- go to Settings
- select the Metadata tab
- update the extension

Once done, the chain is available. (Does not operate on dev chains, only live + test)

A example of Rococo added (metadata, name, colors & types) -

![image](https://user-images.githubusercontent.com/1424473/113972886-b5788900-983b-11eb-9412-ea71f1451a2e.png)

**Comment by jacogr** [comment]
Use the apps UI to inject the chain - 

- go to Settings
- select the Metadata tab
- update the extension

Once done, the chain is available. (Does not operate on dev chains, only live + test)

A example of Rococo added (metadata, name, colors & types) -

![image](https://user-images.githubusercontent.com/1424473/113972886-b5788900-983b-11eb-9412-ea71f1451a2e.png)

**Comment by jacogr** [comment]
Use the apps UI to inject the chain - 

- go to Settings
- select the Metadata tab
- update the extension

Once done, the chain is available. (Does not operate on dev chains, only live + test)

A example of Rococo added (metadata, name, colors & types) -

![image](https://user-images.githubusercontent.com/1424473/113972886-b5788900-983b-11eb-9412-ea71f1451a2e.png)

**Comment by jacogr** [comment]
Use the apps UI to inject the chain - 

- go to Settings
- select the Metadata tab
- update the extension

Once done, the chain is available. (Does not operate on dev chains, only live + test)

A example of Rococo added (metadata, name, colors & types) -

![image](https://user-images.githubusercontent.com/1424473/113972886-b5788900-983b-11eb-9412-ea71f1451a2e.png)

**Comment by hbulgarini** [comment]
Awesome jaco, thanks for the head up. Is there anyway to replicate or execute locally  the upgradable feature of the extension so i can add my dev chain ?

**Comment by jacogr** [comment]
Dev chains are explicitly excluded in the apps UI - since each time you restart, the genesis changes.

You can obviously bypass that with a locally running apps UI, removing the check - https://github.com/polkadot-js/apps/blob/master/packages/page-settings/src/useExtensions.ts#L164

(Not a great idea since you will quickly fill up the allowed 5MB localStorage for the extension, but workable in a pinch)

**Comment by hbulgarini** [comment]
Perfect! thanks for the info Jaco ... i will close this issue since i don't have nothing else to ask.
