### ISSUE TITLE
Error "Something went wrong with the query and rendering of this component"

### ISSUE THREAD

**Issue by SurPaul** [polkadot-js/extension#694]
1. I selected the Polkadot network and connected the Ledger Nano X to the extension.
2. I open https://apps.acala.network/wallet, https://app.subsocial.network/, https://testnet.joystream.org/ or any other site.
3. The hardware wallet is connected and the Polkadot app is open. I am trying to perform some action (sending coins, for example).

Result:
`Something went wrong with the query and rendering of this component. Unable to find supported chain for 0x...`
![photo_2021-04-08_01-23-39](https://user-images.githubusercontent.com/1708881/114016603-13c55c00-987c-11eb-9774-0383c65b0c3c.jpg)

Video: https://youtu.be/G4eHaujhOS8

**Comment by jacogr** [comment]
None of the chains listed has support for Ledger. Only Polkadot, Kusama, Dock and Polymath has built apps with the ZondaX team for support.

**Comment by SurPaul** [comment]
Then why can't I add Dock and Polymesh?

![Снимок экрана от 2021-04-08 23-00-27](https://user-images.githubusercontent.com/1708881/114082512-e352e180-98be-11eb-8197-ef54ca97dca6.png)
![Снимок экрана от 2021-04-08 23-00-37](https://user-images.githubusercontent.com/1708881/114082515-e3eb7800-98be-11eb-82e0-24fd5b68faa2.png)
![Снимок экрана от 2021-04-08 23-05-04](https://user-images.githubusercontent.com/1708881/114082523-e6e66880-98be-11eb-8d39-83760483efec.png)

**Comment by SurPaul** [comment]
> For Polymesh - you need the Polymesh Ledger app installed on the Ledger.

I found this: https://github.com/Zondax/ledger-polymesh . Thanks!

> For Dock - you need the Dock Ledger app, installed on the Ledger.

I have not found an app for this network either on the internet or on Ledger Live. Although I do not use this network.

Please make it so that the "Something went wrong" window can be closed. Now I click "Back to home" but nothing happens. This can be seen in the video. Now I have to disable and enable the extension.

**Comment by Jc199630** [comment]
Hello, sorry I have the same problem, how could I solve it?
![image](https://user-images.githubusercontent.com/84208690/118337948-8ad4bc80-b4da-11eb-8924-9f490b99cba3.png)
![image](https://user-images.githubusercontent.com/84208690/118337963-97591500-b4da-11eb-83f7-a2162e54591f.png)
