### ISSUE TITLE
JSON encoding for account export broken when there's a # in the name

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#699]
Saw this bug in the wild: https://www.reddit.com/r/dot/comments/mtmpjc/cant_connect_my_wallet_extension_account_to_the/

How to replicate:
- create an account with a # in the name
- export the account as JSON
- see the broken JSON (at the end) e.g :
```
{"address":"5Cc..dw","encoded":"Dc8...xgS","encoding":{"content":["pkcs8","sr25519"],"type":["scrypt","xsalsa20-poly1305"],"version":"3"},"meta":{"genesisHash":"0x1611e1dbf0405379b861e2e27daa90f480b2e6d3682414a80835a52e8cb8a215","name":"rococo
```

**Comment by jacogr** [comment]
Note sure if this belongs here or in the common or UI repos - will have to see where exactly.

**Comment by jacogr** [comment]
Here is where it goes off the rails - https://github.com/polkadot-js/extension/blob/master/packages/extension-ui/src/Popup/Export.tsx#L49-L51

**Comment by Tbaut** [comment]
Ah so it's breaking because it's a href and # is a special char. I'm happy to make a PR for that. Should I use "file-saver" like in apps? I could research a bit to find some other way if we don't want to add this dependancy.

**Comment by jacogr** [comment]
I read all the code for that module in 2 mins - it is tiny. Happy to have it in.

**Comment by Tbaut** [comment]
Nice, I'll get to this most prob. this evening.
