### ISSUE TITLE
Dai transaction not coming into sora

### ISSUE THREAD

**Issue by rajbeardo** [polkadot-js/extension#707]
Tranx hash 0xc9ab6f3c85778759241cbc72ef2bec7dcee2a143614c33560b40217f3d406ce1. activity performed more than 20 H ago and dai is yet to be in and all my transaction history are gone on polkaswap account

**Comment by jacogr** [comment]
Please log this with the Sora team, I have no insights into their network. The balance not being reflected is not an extension issue, the extension merely signs the transaction, what the network does after that is up to it.

**Comment by pgolovkin** [comment]
@rajbeardo please, proceed with SORA support channels https://t.me/sora_xor
@jacogr feel free to close this issue.
