### ISSUE TITLE
Allow use on any chain for nano ledger users

### ISSUE THREAD

**Issue by shanevip** [polkadot-js/extension#710]
Hi guys, 

I am trying to use your extension for Polkaswap and there is a problem for ledger users. I cannot make any transactions because when I sign in via my hardware wallet, it doesnt allow me to use my ledger on any chain and by default it is only on polkadot network. Are you guys able to add that feature plz???

**Comment by jacogr** [comment]
There are only limited number of Substrate-based apps available. The UIs know of these - https://github.com/polkadot-js/common/blob/master/packages/networks/src/defaults.ts#L50-L55

Until the team organised a Ledger app and made the required PRs to add them into the config, there is nothing that can be done.
