### ISSUE TITLE
polkaswap signing issue

### ISSUE THREAD

**Issue by HappyMask93** [polkadot-js/extension#711]
on polkaswap.io , when using my ledger to sign a transaction with polkadot js it fails and create this error. 

An error occured
Something went wrong with the query and rendering of this component. Unable to find supported chain for 0x7e4e32d0feafd4f9c9414b0be86373f9a1efa904809b683453a9af6856d38ad5

works fine without the ledger from other peoples reports

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/extension/issues/710

There is no Ledger app.
