### ISSUE TITLE
Ledger Polkadot App V7.30 & Chrome Polkadot-js extension producing FATAL ERRORS and crashing. Stack trace included

### ISSUE THREAD

**Issue by Arfanmi** [polkadot-js/extension#712]
Hello, 

I have updated the ledger app to latest version deployed on ledger live, and have tried to sign a transaction via the extension app on Chrome but get the following Fatal errors:

1. Unable to initialize @polkadot/wasm-crypto
2. WebAssembly is not available in your environment
3. Failed to load resource: net::ERR_FILE_NOT_FOUND
4. Unable to find supported chain for xyz

Please can you advise, I have uninstalled and re-installed the ledger app and the chrome extension during past hour of this post. 

The output just prints the very last error and hangs, the back to home button is not responding, but in the console looks like it does go back and then loops back to the error again. The dialogue doesn't dismiss.

**Comment by jacogr** [comment]
Which chain?

**Comment by Arfanmi** [comment]
Thanks for getting back promptly, the chain it's trying reference is 0x7e4e32d0feafd4f9c9414b0be86373f9a1efa904809b683453a9af6856d38ad5. After re-installation, i have not changed the default setting.

**Comment by jacogr** [comment]
That one is unknown. The only chains supported are Kusama/Polkadot/Dock/Polymath on Ledger - as per the known apps from the teams that have been contributing their details. We also don't have even the genesis for hash for that chain.
