### ISSUE TITLE
Ledger Plugin Breaks with Firefox 

### ISSUE THREAD

**Issue by Ethycs** [polkadot-js/extension#713]
![image](https://user-images.githubusercontent.com/11140224/117175930-33b94400-ad84-11eb-89ed-d104ab8f7512.png)
![image](https://user-images.githubusercontent.com/11140224/117176026-4d5a8b80-ad84-11eb-8575-0513173b17df.png)

Ledger plugin breaks when attempting to add an account on Firefox. Seems to be related to Webassembly. My setup is working with the Chrome plugin.

**Comment by jacogr** [comment]
WebUSB is only supported on Chrome. There is no Ledger support on non-Chrome browsers.
