### ISSUE TITLE
Issue on display of account and website access in the polkadot.js extension

### ISSUE THREAD

**Issue by steven363** [polkadot-js/extension#720]
Hi, 

Just like to highlight a problem about the polkadot.js in Chrome. 

When I clicked extension icon, the interface will appear, but without my account inside. (Note: I already created the account.) 
The same issue happen when I clicked Manage website access, it is also empty. (Note: I had also given access to polkaswap.io.) 

However, inside the apps, when I clicked settings --> open extension in new window, I am able to see my account and also the polkaswap.io in the new window.  

Please assist to advise. 

Thanks. 

![image](https://user-images.githubusercontent.com/84849135/119654481-16473980-be5b-11eb-9cfe-58c3b07d95bc.png)
![image](https://user-images.githubusercontent.com/84849135/119655161-d7fe4a00-be5b-11eb-89af-840fd1dbb54c.png)

**Comment by AxelHamburch** [comment]
I can confirm that. Even if I delete the extension and try to create a new account, the window always remains empty.

**Comment by brendonrr** [comment]
I'm having the same problem!

**Comment by tobbelobb** [comment]
I'm in the Brave browser an have the same problem.

I found that I can place my mouse pointer just below the horizontal line under "Accounts", and scroll with my scrollwheel to see my account.

https://user-images.githubusercontent.com/5753253/120079605-f0b56c80-c0b4-11eb-9b91-7c541bdf50db.mp4

CSS related problem?

**Comment by Shoki46** [comment]
I'm also have the same issue. I do not know how to code
