### ISSUE TITLE
Issue with claiming xHDX on the claim.hydradx.io

### ISSUE THREAD

**Issue by label73** [polkadot-js/extension#724]
Hello,

Just want to highlight the issue on the claiming website.
All the time there is RECONNECT button.

There are some errors in the browser console. I attached it as log to the issue.

Please assist to advise.

I have use only MetaMask and polkadot.js on the website, the rest applications are disabled.
I updated network to "HydraDX Snakenet Gen3" in polkadot.js app.

[claim.hydradx.io-1622092871451.log](https://github.com/polkadot-js/extension/files/6551291/claim.hydradx.io-1622092871451.log)
![Screenshot_20210527_082604](https://user-images.githubusercontent.com/50731483/119770696-3875a180-bec5-11eb-8222-865526f4bdee.png)

**Comment by label73** [comment]
Please let me know

**Comment by jacogr** [comment]
Please direct this to the HydraDX team. It seems like some types are missing for their network. There is nothing I can do about it here.

**Comment by label73** [comment]
MetaMask 9.5.4
polkadot{.js} extension 0.38.1

**Comment by jacogr** [comment]
Yes, but the errors that are shows is in the HydraDX code, not the extension. So this is the wrong place to log it, the Hydra team needs to have a look.

**Comment by label73** [comment]
> Yes, but the errors that are shows is in the HydraDX code, not the extension. So this is the wrong place to log it, the Hydra team needs to have a look.

Thanks for quick response.
I submitted extension versions for developers, might be some methods were deprecated in the new versions.

**Comment by SimonKraus** [comment]
Invalid here,
fixed there => https://github.com/galacticcouncil/HydraDX-claims/pull/15

**Comment by SimonKraus** [comment]
Thanks for the lights speed response as always, @jacogr

**Comment by label73** [comment]
The fix was deployed to prod. Checked, all works fine as expected.
Thank you @SimonKraus and @jacogr!
