### ISSUE TITLE
Documentation Request: How to inject accounts for only one type of chain

### ISSUE THREAD

**Issue by tjwelde** [polkadot-js/extension#725]
Hi, we are building our own wallet as a browser extension and want it to be injectable into the polkadot/apps.
We are able to inject our accounts, but they are available on all the chains, translated to the corresponding address prefix.
We couldn't find out how to restrict it to only our own chain. 

We saw, that the polkadot/extension can restrict accounts to specific chains. How is this achieved?

**Comment by jacogr** [comment]
You need to add the relevant chain genesisHash to the meta of each account.

**Comment by tjwelde** [comment]
Thanks a lot

**Comment by jacogr** [comment]
When available, would love to add it to the Apps UI interface for newbies. (There are links when they have none to the different stores)
