### ISSUE TITLE
[BUG] Unable to import ledger account to extension

### ISSUE THREAD

**Issue by saumyakaran** [polkadot-js/extension#735]
I keep getting the following error when I try to connect my ledger device through the polkadot{.js} extension:

<img width="250" alt="Screen Shot 2021-06-03 at 10 20 13 AM" src="https://user-images.githubusercontent.com/40575379/120589102-f95fc700-c455-11eb-98b4-c6a0059b4d36.png"> <img width="250" alt="Screen Shot 2021-06-03 at 10 20 06 AM" src="https://user-images.githubusercontent.com/40575379/120589090-f49b1300-c455-11eb-8594-b0e2e976abe2.png">

This issue persists even after re-installing the extension and re-connecting and repairing the ledger device.

Issue seems to be network independent.

Browser: Brave Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (x86_64)

**Comment by jacogr** [comment]
This is a Ledger issue, see https://github.com/polkadot-js/apps/issues/5406

**Comment by saumyakaran** [comment]
Ah! Thank you for the prompt response. I suppose I shall downgrade for now.
