### ISSUE TITLE
Adding ledger to Polkadot extension

### ISSUE THREAD

**Issue by olivero09** [polkadot-js/extension#737]
I am using Chrome on a Mac and have the polkadot extension installed. 
When I try to add my ledger nano x I get the error. Ledger error: The device was disconnected.
The ledger however, is connected and I am logged in. I have no problems with the ledger on https://polkadot.js.org/apps

Is the extension currently working with Chrome at all what am I doing wrong? 
Thx,

**Comment by jacogr** [comment]
You cannot have the Ledger enabled on both apps and the extension - only one at a time.

(The extension only uses WebUSB, on chrome 91.x upwards there are issues with the Ledger interface, see https://github.com/polkadot-js/apps/issues/5406)

**Comment by olivero09** [comment]
Hi thank you for this. I tried what you referred to and I disabled the ledger use on polkadot.js. It didn't make a difference. The extension can not see the ledger. thank you anyway.

**Comment by Chralt98** [comment]
Same for me here...

**Comment by Chralt98** [comment]
Unfortunately the Karura Crowdloans benefits end in 2 days.

**Comment by Chralt98** [comment]
Downloading the newest nightly build chrome canary version fixed the issue. https://www.google.com/intl/de/chrome/canary/
