### ISSUE TITLE
Add polish language

### ISSUE THREAD

**Issue by ccris02** [polkadot-js/extension#738]
I would like to add Polish language to https://github.com/polkadot-js/extension/tree/master/packages/extension/public/locales

Is _translation.json_ the only thing that needs to be translated?

**Comment by jacogr** [comment]
Yes. Just the translation.json file.

Contributions very welcome.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/extension/pull/744 (will be in the next release)
