### ISSUE TITLE
Failed to sign transaction when using external account

### ISSUE THREAD

**Issue by 0x7CFE** [polkadot-js/extension#739]
Acala/Karura website uses account message signing as a way to agree with terms and conditions. It works well for accounts that are managed by the extension. However airgapped accounts fail to sign the message.

Currently it looks like this:
![image](https://user-images.githubusercontent.com/3784017/121328406-7f8c7980-c93e-11eb-8fd4-36468094136b.png)

**Comment by jacogr** [comment]
There has been a number of issues logged around this in the past, which has more info than I should re-hash. This is an issue with the QR signer supports.
