### ISSUE TITLE
Transfers from Kraken to extension not possible

### ISSUE THREAD

**Issue by Karischm** [polkadot-js/extension#740]
Hi, 

I transferred KSM 2 times from Kraken to the Polkadot extension, but it never goes through.

Anybody else experienced similar issues ?

Thanks! Kari

**Comment by jacogr** [comment]
The extension itself doesn't hold funds - it doesn't connect to the network. It only provides a Polkadot/Kusama/etc. standard address to which funds can be transferred. The funds are put in the state on the network itself. (So when the address is made visible to eg the apps UI, it knows which addresses to query)

If you have transfer issues from the exchange, check their status and/or log support with them. It could be that they have some delay.

**Comment by Karischm** [comment]
Thank you for the quick reply! So I cannot send the funds to the generated address on the extension?

**Comment by jacogr** [comment]
You can. My point is just -

- the extension only stores the private keys and allows you to sign transactions for an account
- all funds are stored on the network

So when funds are transferred it is stored on-chain. If it doesn't appear there, it means the sender has an issue.

**Comment by dineshpinto** [comment]
> 
> 
> Hi,
> 
> I transferred KSM 2 times from Kraken to the Polkadot extension, but it never goes through.
> 
> Anybody else experienced similar issues ?
> 
> Thanks! Kari

I had a similar issue. What I found is that for transferring KSM the account address format needs to be switched to the Kusama Relay Chain. This can be done by clicking the three dots and selecting Kusama Relay Chain in the dropdown menu. This will generate a KSM address which can be used in Kraken.

As for viewing account balances, you can look at https://polkadot.js.org/apps/, switch to the Kusama network (top left button, select Kusama and click Switch) and the account balances should be visible under Accounts.

Hope this helps.

**Comment by Karischm** [comment]
Ok great! Thank you. That does make sense..
