### ISSUE TITLE
Message signing doesn't work with released Parity Signer

### ISSUE THREAD

**Issue by FartFeatures** [polkadot-js/extension#741]
I downloaded and built the latest version of the code in order to gain support for message signing via external QR code wallet (Parity Signer from the Apple App Store) which was added in a recent pull request. 

To test I used Polkadot.js developer tools to sign a message. When I scan the generated QR code with Parity Signer it displays a message complaining the QR code should contain a message or a transaction with a button that says try again.

Is this something borked with the implementation of this feature or is it because this feature is only in some kind of pre-release version of Parity Signer? I note that the version on the app store is 9 months old despite several commits occurring since.

**Comment by jacogr** [comment]
I cannot comment on Parity Signer, you would need to refer queries on the app to the repo itself. As far as i could gather from the PR made to add the stuff, Stylo has support and the signer has an open PR for it. More than that, I don't know.

**Comment by FartFeatures** [comment]
What is Stylo?
