### ISSUE TITLE
Is it possible to whitelist an app for the extension

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/extension#746]
While onboarding people on our attestation/contribution apps for the crowdloan, we (Moonbeam) have had a lot of problems with users not understanding why the app won't connect to their extension, only to realize it's because the attestation app is not authorized in the extension.
Is it possible to whitelist an app for the extension? In our case `attestation.moonbeam.foundation` for example

**Comment by jacogr** [comment]
The only issue is the fact that the name may be used elsewhere, i.e. it is totally in control of a less-than-honest person to use the same name in his app and then bypassing the auth.

**Comment by joelamouche** [comment]
But isn't it using the https secured url?
