### ISSUE TITLE
Support for signed ethereum messages

### ISSUE THREAD

**Issue by ntduan** [polkadot-js/extension#747]
The signed messages are now wrapped in `<Bytes>`.So there is no way to sign messages for ethereum.

But actually, Ethereum messages have a prefix, "\x19Ethereum Signed Message:\n", so I think it can be handled specially, but when there is this prefix, it doesn't need to be wrapped in `<Bytes>`.

https://github.com/ethers-io/ethers.js/blob/master/packages/hash/src.ts/message.ts#L5

**Comment by jacogr** [comment]
Indeed. It should be a simple addition, can just change this `isWrapped` to also detect the Ethereum form - https://github.com/polkadot-js/extension/blob/master/packages/extension-dapp/src/wrapBytes.ts#L11-L15

As always, PRs welcome.
