### ISSUE TITLE
I'm not getting my nodle account injected.

### ISSUE THREAD

**Issue by SmoothieB** [polkadot-js/extension#750]
Hi, I have a new laptop and want tot restore the extension with JSON file and connect with my account. 

I manage to recover both my account and the extension with JSON. I am unable to link my account to my Nodle wallet and get the wallet injected.

Nodle referred me here. It is suspected that the extension seems bugged on my side. Can someone please help me?

Thanks!

**Comment by jacogr** [comment]
I cannot comment on "Nodle wallet", I have no idea what it is.

Check it against the apps UI on the chain in question. Also ensure that your account in the extension is set correctly - either for the Nodle chain or "allow on all" - if set to a specific chain and you connect to something that is not that chain, it won't show.

**Comment by SmoothieB** [comment]
Thanks for your comment. 

Nodle is a token/network on the nodleprotocol.io chain. I will follow your advice and see if it works.

**Comment by SmoothieB** [comment]
when i open with  polkadot.js.org/apps UI I see my injected Kusama account. When I switch to Nodle Network, I don't see a Nodle account. I can retrieve this via JSON, but I am not able to get my Nodle account "injected" like my Kusama account. After refresh my Nodle account is gone again. 
![Nodle_Print](https://user-images.githubusercontent.com/85891287/122191674-3c2c9080-ce93-11eb-8736-5251d1763879.PNG)
![print_Kusama](https://user-images.githubusercontent.com/85891287/122191728-46e72580-ce93-11eb-8aac-0d6c9a5eb50f.PNG)

**Comment by jacogr** [comment]
Ok, is your Nodle account the same account? And in the extension have you attached it to any chain?

It sounds like the genesisHash for that account is specified already, i.e. in the extension you have it showing like - 

![image](https://user-images.githubusercontent.com/1424473/122213111-e367f280-cea8-11eb-9ce0-b4449961b5a5.png)

That means it is only available on Kusama. If you want it on all chains, swap the option -

![image](https://user-images.githubusercontent.com/1424473/122213232-08f4fc00-cea9-11eb-965d-6818cc0c3f2f.png)

**Comment by SmoothieB** [comment]
They are 2 different accounts/wallets and 2 different extensions.
![Nodlev1](https://user-images.githubusercontent.com/85891287/122226793-9854dc00-ceb6-11eb-85f3-8adb278caacf.PNG)
The Nodle account states: "allow use on any chain" and the Kusama account "Kusama Relay Chain".
If instead of the polkadot.js.org URL I use the URL nodleprotocol.io and "allow use on any chain" I have the same problem. 
![Nodle_account](https://user-images.githubusercontent.com/85891287/122227957-aeaf6780-ceb7-11eb-973e-df94790627f4.PNG)
There is 1 difference when I use the Nodle URL. I see my balance (tokens). Only I still can't get my account linked to the extension.

What also strikes me is that I don't see a green check mark with the name Nodle in the extension. Previously, when the wallet was Injected you could see this. With the Kusama extension you will see this in black.

**Comment by SmoothieB** [comment]
In addition to the above. 

So I can retrieve my main wallet with my JSON file, but it always disappears after closing. Every time I access my wallet I first have to retrieve it with JSON.

I hope there is a solution for this. Thanks in advance for your reply.
