### ISSUE TITLE
[Feature Request] Inject child keypair derivation function

### ISSUE THREAD

**Issue by Kevingislason** [polkadot-js/extension#754]
### [Motivation]

Manta's dapp would like to integrate with the polkadot.js extension, but two of Manta's features are currently incompatible:

1.) Manta uses ZKSNARKs; we need private keys not only to sign extrinsics, but also as direct inputs to cryptographic proofs.
2.) Tokens on Manta are UTXO-based  (i.e. not account based), so we need to derive new addresses for every transaction to prevent privacy leaks.

### [Proposal]

polkadot.js extension could inject dapps with an api to derive child keypairs from parent accounts. This self-evidently solves 2.). We can then manually decrypt the derived child secret key [as described here](https://polkadot.js.org/docs/keyring/FAQ/), solving 1.). 

### [Security]

polkadot-js may not want to inject encrypted secret keys under any circumstances. Secret keys belonging to derived children may be as sensitive as the root secret key, for example if the child was derived by the user through the polkadot.js extension UI.

So, what if polkadot.js restricted the key derivation api to some constant key path, i.e. `m/{POLKADOT_JS_DERIVED_CHILD_IDX}'`? `POLKADOT_JS_DERIVED_CHILD_IDX` would correspond to [the BIP43 purpose field](https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki), and would be some obscure high number to prevent overlap with accounts derived through the polkadot.js extension UI, or overlap with other BIP43 purpose field constants. In this manner, the security of the wallet as a whole would not be compromised, but ZKSNARK and UTXO-based networks could be supported.

**Comment by jacogr** [comment]
The issue here is the `m/*` BIP-compatible derivation. That is not a Substrate standard, not actually exposed or used in the extension. The derivation in Substrate or the sr25519 pairs are done via `//<hard-id>` or `/<soft-id>`. 

The general idea does sound feasible, i.e. have a specific hard path for this and then derive additional indexes from it.

**Comment by Kevingislason** [comment]
>The issue here is the m/* BIP-compatible derivation

Not a problem. I'm aware that polkadot.js doesn't use BIP32 key derivation, but thought the two path syntaxes were interchangeable.

>The general idea does sound feasible

Awesome!

**Comment by stechu** [comment]
@jacogr, thanks for the clarification. 

We can use the hard path derivation, `<mnemonics>//<POLKADOT_JS_DERIVED_CHILD_IDX>`,where `<POLKADOT_JS_DERIVED_CHILD_IDX>` would correspond to the BIP43 purpose field, and would be some obscure high number to prevent overlap with accounts derived through the polkadot.js extension UI, or overlap with other BIP43 purpose field constants. More specifically, we only require polkadot.js extension to allow the exporting of the secret key derived from `<mnemonics>//<POLKADOT_JS_DERIVED_CHILD_IDX>`.   Then, the polkadot.js extension could integrate very well with the web-app we are developing now. Our web-app will use this secret to perform several additional key derivations for the purpose of UTXO management, but these will be handled by Manta and doesn't require any additional information from the extension.

What is the best way to move this forward? Currently, we are developing the web front-end for our test-net users. It would be great if using Polkadot.js extension could be part of their experience!

**Comment by stechu** [comment]
@jacogr  is there anything that we can do to help?

**Comment by burdges** [comment]
What keys are you using?  What curve are you using for the SNARK?

Some Jubjub-like curve for BLS12-377? 

ZCash style Jubjub on BLS12-381?  If so, I'd recommend you look at whatever zcaszh does.  Also, Bandersnatch might be slightly faster
https://ethresear.ch/t/introducing-bandersnatch-a-fast-elliptic-curve-built-over-the-bls12-381-scalar-field/9957 Arkworks added support https://github.com/arkworks-rs/curves/pull/64 although not sure about gadget support.  I'd still recommend you look into what ZCash does.  Ain't clear this'll make much difference really, but just fyi.  I'd doubt the SNARK needs to understand the derivation, although maybe if you've some more complex business logic there.

**Comment by stechu** [comment]
@burdges Do you have the pointers for ZCash's wallet protocol? I am actually not aware that they published that. 

We are using Jubjub on BLS12-381 (may upgrade to Bandersnatch later once it get more mature). The issue here is actually independent of the curve. We basically need a `32` secret bytes that is deterministically derived from a user's mnemonics, then use these `32` secrets bytes as the root secrets to derive the randomness in all UTXOs.  The reason for that is to allow user to recover all the UTXOs by only providing the mnemonics. Manta is going to use a BIP-32 styled wallet protocol https://github.com/Manta-Network/MIPS/pull/2 for that. The most heavy lifting work will be handled by our web DApp. Exposing a deterministically derived secret is actually the only thing we need (I can think of) from Polkadot JS browser extension.

**Comment by burdges** [comment]
zcash has pretty solid protocol documentation like https://raw.githubusercontent.com/zcash/zips/master/protocol/protocol.pdf although not sure about how well they motivate this part or where it appears.  

There are snark friendly hash functions like Posideon btw, and also arkworks has a non-native arithmetic library would could be used to do JubJub scalar arithemtic I guess, but likely you never need to prove derivation inside the SNARK?

**Comment by stechu** [comment]
@burdges  yeah, this protocol spec doesn't include wallet protocol, unfortunately.

In some way, the wallet protocol is "independent" of the protocol on chain. You could just sample the randomness of each UTXO and store them in a safe place.  We use the BIP-32 styled wallet protocol for a better user experience.

**Comment by burdges** [comment]
yeah okay so then maybe just get advise.  :)
