### ISSUE TITLE
Wrong location for Polish Translation.

### ISSUE THREAD

**Issue by ccris02** [polkadot-js/extension#763]
Hi Jaco,
I’m afraid I created polish translation in the wrong location
Current location 
https://github.com/polkadot-js/extension/tree/master/tree/master/packages/extension/public/locales
It should be 
https://github.com/polkadot-js/extension/tree/master/packages/extension/public/locales

**Comment by jacogr** [comment]
Will move, thank you. Sorry, I really should have picked this up in the PR itself, my apologies.
