### ISSUE TITLE
Multiple Karura to choose in account network selection menu

### ISSUE THREAD

**Issue by xlc** [polkadot-js/extension#764]
When choose which chain to use an account, for some reason I have multiple Karura and only one is for the Karura mainnet. Is it because I uploaded the metadata for other Karura testnet? Should have a way to list and cleanup those.

<img width="292" alt="Screen Shot 2021-06-29 at 3 25 33 PM" src="https://user-images.githubusercontent.com/1201310/123732648-4f594a80-d8ee-11eb-8a59-f3e59814fd6a.png">

**Comment by xlc** [comment]
@jacogr

**Comment by xlc** [comment]
Still an issue

**Comment by weichweich** [comment]
We have the same issue. My guess is, that the chains are identified by their genesis hash and not by name. This is a good thing, but there should be a way to distinguish chains which have the same name or delete old chains from the list.

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
maybe I need a bot to reply don’t close this to this issue every 21 days?

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
don’t close this

**Comment by nazar-pc** [comment]
I ran into this issue as well. Tried to find the underlying storage or exact code in this repo that deals with that list of chains so I can edit it manually, but failed. Really annoying.

**Comment by xlc** [comment]
don’t close this

**Comment by jacogr** [comment]
This is 100% working as expected - 

- each chain has a single genesisHash
- if hashes are changed (think Kusama CC1, CC2, CC3), you can specify additional hashes for a chain, e.g. https://github.com/polkadot-js/common/blob/master/packages/networks/src/defaults.ts#L34-L38

Not going to try and merge things by name here, it is not supposed to be the unique identifier. Live changes are all managed by the above process. If you do have the same-name-dev-chains, you will need to clear the storage manually to remove them.

**Comment by nazar-pc** [comment]
How do I clear the storage manually though?
I mean I wouldn't want to wipe all the accounts and such, just extra entries that I have added by clicking "Update Metadata" on multiple versions of dev chain?

**Comment by xlc** [comment]
@nazar-pc asked the exact question I want to ask. Also quoting my previous comment:

> Allow to add but no remove never make sense. User will also join multiple different testnets and eventually they will stop using those testnets. But now their network list already contains bunch useless networks and only way to remove is reinstall the extension?

**Comment by jacogr** [comment]
As stated, it works exactly as designed - multiple networks are managed by providing multiple genesis, as per the links provided. That is how swapping from one to another has always been managed, right from the days of Kusama CC2 replacing Kusama CC1. If one replaces another, it should be updated to reflect. 

(If that process doesn't work for some reason, aka it is a testnet, it should be looked at. Rococo is for instance an example where it is on a continuous replace cycle while the genesis is not being managed above)

For developers I always recommend https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb?hl=en to look at the actual extension storage.

Let me re-iterate, not going to spend any development effort on this, PRs are welcome if it is a crisis for you.

**Comment by nazar-pc** [comment]
Storage Area Explorer looks nice except I don't use Chrome :confused: 
How to I access and edit storage in Firefox?
