### ISSUE TITLE
При загрузке сайта https://polkadot.js.org/apps/#/explorer белый экран

### ISSUE THREAD

**Issue by borisgureev** [polkadot-js/extension#765]
Не получается загрузить сайт https://polkadot.js.org/apps/#/explorer
Несколько секунд грузится, потом становится белый экран. В чем может быть проблема?

**Comment by ccris02** [comment]
Попробуйте подключиться к другому серверу.
![image](https://user-images.githubusercontent.com/66147586/124392318-ab82ec80-dca9-11eb-91f3-6aec159d3f42.png)
