### ISSUE TITLE
How to decide whether interactive rejected

### ISSUE THREAD

**Issue by sxlwar** [polkadot-js/extension#773]
Perhaps the following error should be exposed to the caller

https://github.com/polkadot-js/extension/blob/e4ce268b1cad5e39e75a2195e3aa6d0344de7745/packages/extension-dapp/src/index.ts#L56

Or add an additional API to determine whether the current domain is rejected.

In addition, is it appropriate to return an empty array when an exception occurs in getWindowExtensions method? It is impossible to judge whether the user really does not have an account or just because of some exception.

https://github.com/polkadot-js/extension/blob/e4ce268b1cad5e39e75a2195e3aa6d0344de7745/packages/extension-dapp/src/index.ts#L89

**Comment by zeedgold** [comment]
Am back again, am sorry
