### ISSUE TITLE
but I didn’t save 12 secret words

### ISSUE THREAD

**Issue by valera1808** [polkadot-js/extension#774]
Good day! Please, help! I installed the Polkadot extension, but I didn’t save 12 secret words, I only saved the wallet number. I participated in the first Akala pre-sale and I was credited with Akala and Karura coins, but I do not have 12 secret words.
To prove that the wallet belongs to me, I will provide you with a username, password, Google 2FA from my Akala account, where all the credited coins and the saved wallet number will be displayed in the profile. For Christ's sake, help! I took out a loan of more than $ 2000, for me this is a huge amount! Please meet my grief! I am Russian and live in Russia. I do not speak English, so I did not understand that I need to save 12 words, I only later figured it out and realized my mistake. I fully trust you and am ready to provide proof of ownership of the Akala account, where the Polkadot wallet number is stored. I will give you your login, password and Google 2FA, just help me recover coins worth more than $ 2100.
My wallet: 5H6GUMCaUA1FYskuULDLU3kNtLGZuGb5F8HUMt2k2nuS5eJg

**Comment by jacogr** [comment]
Without the mnemonic seed, you cannot recover the wallet. There are no backdoors that allows access to it.
