### ISSUE TITLE
Avoid format balance type when displaying balance value

### ISSUE THREAD

**Issue by xlc** [polkadot-js/extension#778]
I want to see every single digit of the balance value to verify ti is matching. The automatic format can also be wrong and misleading for some cases. e.g. when the token decimal is not actually matching to native one.

**Comment by xlc** [comment]
don’t close this

**Comment by jacogr** [comment]
Not going to do anything about this one. 

Actually with metadata v14 it will “magically go away” since we just don’t have the info available to apply balance formats anyway. 

You win some, you lose some.
