### ISSUE TITLE
ED25519 support for PolkadotJS extension

### ISSUE THREAD

**Issue by Gauthamastro** [polkadot-js/extension#782]
We can use keyring to create an ecdsa pair as given below.
```
const keyring = new Keyring({ type: 'ed25519', ss58Format: 2 });
const mnemonic = mnemonicGenerate();
const pair = keyring.addFromUri(mnemonic, {name: 'first pair'}, 'ed25519');
```

But is there any way we can generate an ed25519 pair using the polkadotjs extension?

cc: @jacogr

**Comment by jacogr** [comment]
The extension only generates sr25519 from mnemonic and it is unlikely to change.

However, you can import an encoded JSON with ed25519 and it will work. Underlying it supports any crypto that can be imported via JSON.

**Comment by Gauthamastro** [comment]
> The extension only generates sr25519 from mnemonic, and it is unlikely to change.
> 
> However, you can import an encoded JSON with an ed25519 pair and it will work. Underlying it supports any crypto that can be imported via JSON.

Can you please share a code sample of how I can do that?
