### ISSUE TITLE
No balance

### ISSUE THREAD

**Issue by zaland123** [polkadot-js/extension#783]
Hi Admin,
I transferred a KSM token from my Binance account to my polkadot-js/extension wallet.
Both Polkascan and Binance have confirmed the transaction but I cant see my KSM token in my polkadot-js/extension wallet.
can it be sorted please.
thanks
shoukat Ali

wallet address. 15g4REyZHMeitDvNZBkL8Q2VBf4PA3415XeAvk5xTiW6JZZ1

**Comment by jacogr** [comment]
That address has no balance, see all the explorers -

https://dotscanner.com/polkadot/account/5g4REyZHMeitDvNZBkL8Q2VBf4PA3415XeAvk5xTiW6JZZ1
https://polkadot.subscan.io/account/15g4REyZHMeitDvNZBkL8Q2VBf4PA3415XeAvk5xTiW6JZZ1
https://polkascan.io/polkadot/analytics/search/15g4REyZHMeitDvNZBkL8Q2VBf4PA3415XeAvk5xTiW6JZZ1
