### ISSUE TITLE
Firefox - Unable to retrieve keypair with 2 extensions

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#79]
on https://polkadot.js.org/apps/#/accounts (+ extension in `master`), Alexander, Firefox

how to reproduce:
- make a Tx from an extension account
- the popup to sign the Tx appears while the Tx fails at the same time
>Uknown response: {"id":"1563097809584.3","error":"Unable to retrieve keypair '5G22HUM9unfvvAav61HUQUwCXrsvom1XYoT2KkXaA5vBmffm'","origin":"content"}
![image](https://user-images.githubusercontent.com/33178835/61182054-61bd1980-a62e-11e9-9e6d-9c835f2dc40d.png)

**Comment by Tbaut** [comment]
Lowering prio.
Happened because I had 2 extensions (live + debug `master`)

**Comment by jacogr** [comment]
Closing. Dupe install issue.
