### ISSUE TITLE
[Question] trusting dapps vs chain data; see balances on every chain and total

### ISSUE THREAD

**Issue by paulvi** [polkadot-js/extension#797]
Hi

I might be missing something, but as this extension Wallet has no chain selection, 
so it cannot display how much money user has in account on that chain.

The whole idea of blockchain, is that we don't need to trust anybody and check data on blockchain,
so Wallet can be one of tools.

But with workflow that this extension promotes, the balances are seen in dapps (web UI),
so if dapp developer decides to cheat, user may be not aware, that the money is not actually there in his/her control.

---

And from usability point of view, what is value of Wallet software that cannot tell how much money are inside?
I think there should list of all known chains (that user has interested and wallet has history of)
and total as sum of all balances with whatever reference exchange rate.

**Comment by jacogr** [comment]
The extension is only a signer. It is not a wallet. 

Wallet functionality it out of scope - as you mentioned for some it is ok, for other not. The ecosystem is big so hopefully there are solutions out there that serves your specific needs.

**Comment by paulvi** [comment]
Should this issue stay open as [feature request] to display balances?

**Comment by Swader** [comment]
No. If you want to see balance on all chains use something like sub.id

**Comment by paulvi** [comment]
Current README stays clear

> As it stands, it does one thing: it only manages accounts and allows the signing of transactions with those accounts. 

so closing
