### ISSUE TITLE
Extension icon not visible on chrome

### ISSUE THREAD

**Issue by GeesaySF** [polkadot-js/extension#801]
Hi, it is stupid but event if polkadot extension is installed on may chrome 92.0.4515.159 (win 10 64 bits), it do not appear on the icon list. More exactly I saw it just a second.

![image](https://user-images.githubusercontent.com/89744536/131260045-ca66b10c-145f-4c5a-b7ef-aa77766c2b67.png)

Do you have a solution to this ?

Tank you.

GeesaySF

**Comment by jacogr** [comment]
Click on the puzzle piece to list the extensions and pin those that you want to always show -

![image](https://user-images.githubusercontent.com/1424473/131262924-022f6d95-3646-4b23-a124-f6a8bf2e7024.png)

**Comment by GeesaySF** [comment]
Problem solved. Thank you !
