### ISSUE TITLE
Approving a dapp gives access to metadata about all accounts in the wallet.

### ISSUE THREAD

**Issue by dcompoze** [polkadot-js/extension#804]
I haven't had the chance to look at the code to confirm what it's doing but it seems to me that when I approve an application to access my Polkadot.js extension wallet - it immediately knows about all of my existing accounts.

For comparison, Metamask allows you to share specific accounts individually - this would be nice to have in the Polkadot.js extension as well.

**Comment by jacogr** [comment]
This is not metamask.

**Comment by dcompoze** [comment]
@jacogr What does that mean?

**Comment by jacogr** [comment]
The issue compares this directly to metamask - this is not a metamask replacement, not do we use metamask, that is a different exosystem. So what they do is up to them.

**Comment by dcompoze** [comment]
@jacogr I'm sorry but what are you talking about? 
I compared to Metamask as an example - this is a general security concern. 
It should not be possible for the website/dapp to get the metadata about all of my accounts when I want to interact with it - that's terrible design. 
That's like trying to withdraw some cash from the ATM and having to disclose all of your bank account and credit card information at the same time.

**Comment by jacogr** [comment]
To each their own. Please don't use the "terrible extension", with a "terrible design".

**Comment by jacogr** [comment]
Closing, not constructive.
