### ISSUE TITLE
Pause multi frame QR code

### ISSUE THREAD

**Issue by xlc** [polkadot-js/extension#805]
It is very hard to scan it and it is keep rotating. I need to take screenshot of each frame to get it working.
Should just have a way to pause and manually navigate between each frame.

**Comment by xlc** [comment]
don’t

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
don’t close this

**Comment by jacogr** [comment]
Are you saying that the default 2.5s (incrementing by 500ms each time it wraps) is not enough? Happy to accept PRs to change the defaults here - https://github.com/polkadot-js/ui/blob/master/packages/react-qr/src/Display.tsx#L33

**Comment by xlc** [comment]
It could be just me but most of the time 2.5s is not enough. Make it longer also means if I missed one, it will take much longer time to rotate back to the missed one.

Will really love the ability to manually navigate the frames as a fool proof solution. You can still have it automatically rotate, but with a pair of arrow buttons to go back or forward.

**Comment by Tbaut** [comment]
Just a 2 cents as I see this discussion, Signer has added a pretty mind-blowing QR reading algorithm, that let you show many frames, in a very short time, so that it's suitable for bigger blobs of data such as metadata. example of such can be found here https://metadata.parity.io

I imagine the path forward would be to generate such apng.

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
don’t close this

**Comment by xlc** [comment]
don’t close this

**Comment by jacogr** [comment]
Won't get done. As discussed above, the complexiy adding to the UI here is too much. The libraries already slows it down.
