### ISSUE TITLE
Add encodedCallHash and encodedCallData to info screen when signing

### ISSUE THREAD

**Issue by jak-pan** [polkadot-js/extension#806]
There is no way to confirm that you are signing the right message from the users perspective. 
We should be able to check easily if we're signing what we want.

**Comment by jacogr** [comment]
The extension does decode the method, the user can check all info.

(Obviously this assumes the user kept his metadata in the extension up-to-date, if not, stuff like the apps UI will prompt them to do so)

**Comment by jak-pan** [comment]
I see, but if you are power-user, it would be much faster to just look at the hashes than to click and check the inputs. I guess it wouldn't hurt to have a way to just look and confirm tx. It's more about reducing friction.
