### ISSUE TITLE
Npm has no latest packages

### ISSUE THREAD

**Issue by AndreiEres** [polkadot-js/extension#814]
Please update packages in npm to latest version.
For example `@polkadot/extension-ui ` published 2 years ago. 
https://www.npmjs.com/package/@polkadot/extension-ui

**Comment by jacogr** [comment]
The UI portion doesn't get published, it makes no sense since it is published to the browser app stores. 

Only the packages usable from actual apps, e.g. `extension-dapp` gets published, see https://www.npmjs.com/package/@polkadot/extension-dapp
