### ISSUE TITLE
Settings menu overflow is hidden, and not scrollable

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#817]
I've tested master in the past days and I have had the problem that the "open in tab" menu wasn't accessible.
The menu overflow is hidden and there's no scrollbar.

I tested this on Brave and Chrome

![image](https://user-images.githubusercontent.com/33178835/133257074-6140b725-2c2c-4929-8fc0-e835449567a7.png)

**Comment by jacogr** [comment]
I could have sworn I updated my extension _after_ merging the "Notification" setting PR.
