### ISSUE TITLE
Feat request: search bar

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#830]
Hello,
This is something I've been missing for a little while, I often find myself searching for an account visually and taking a while to find it. I'd benefit from a search bar, that would appear at the click of a "magnifying glass" button. I guess next to the + and cog wheel, and the search field would appear when the magnifying glass is clicked.

I'd be happy to take a look at it this week-end if you'd be ok with such a feature
![image](https://user-images.githubusercontent.com/33178835/133791673-3bdbbdad-eb6f-47d9-909e-1ce84d3fdb47.png)

**Comment by jacogr** [comment]
Would be great. Thank you.
