### ISSUE TITLE
Problem connecting extension to Khala and Karura apps

### ISSUE THREAD

**Issue by michaelmowry** [polkadot-js/extension#835]
Since last Thurs/Fri the polkadot.js extension has stopped working on the following sites:

- https://app.phala.network
- https://apps.karura.network/

Browser: Brave & Chrome
OS: Windows

I have tried disabling other extensions and have disabled the popup/ad blocker. I should say that before Thurs/Fri, I was able to connect and switch my polkadot.js extension accounts with no issue.  Not sure what went wrong here but it has basically made it impossible to use these sites.  I have noticed other people having this issue as well.

![2021-09-20_08-19-00](https://user-images.githubusercontent.com/7070665/134028457-aaa5bcb6-2d52-43ed-8801-a2dc4857d376.png)

![2021-09-20_08-19-05](https://user-images.githubusercontent.com/7070665/134028477-ac193ed5-daa0-4aba-819b-bd27a140a2ba.png)

**Comment by jacogr** [comment]
Not in control of those sites. I am guessing they need an update. 

On this side, nothing than can be done.

**Comment by michaelmowry** [comment]
That's funny because they are saying the same thing..."This is a polkadot.js extension issue."

**Comment by jacogr** [comment]
The extension works perfectly in the apps UI which points to a specific app issue.

**Comment by michaelmowry** [comment]
The latest here is 0.41.3 (github) and the latest on chrome store is 0.41.1 (https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd).  Could that be the issue?

**Comment by michaelmowry** [comment]
@jacogr Please try these steps to reproduce as I now think this is an issue specific to the json export/import.

1. Export your accounts using the json feature (I have 15+ on different networks, ect.)
2. Import the json to another browser/extension.
3. Try to connect to https://apps.karura.network

I was able to resolve by importing my accounts individually using the seed import option, which is painful.

**Comment by v-van** [comment]
Same problem
#825

**Comment by gregorst3** [comment]
Same problem here, the issue is not only on the khala platform but I'm having same problem on chainx and moonriver apps.

**Comment by gregorst3** [comment]
@jacogr  I manually built 0.40.3 and the problem is fixed. When this version will be available to chrome? I can not also send tokens from statemine with 0.40.1
