### ISSUE TITLE
firefox plugin pops up for one second, but closes again

### ISSUE THREAD

**Issue by drahnr** [polkadot-js/extension#838]
This is a reincarnation of the auto-closed one https://github.com/polkadot-js/extension/issues/722

`Fedora 34 x86_64`
`Mozilla Firefox 92.0`
```
Installed Packages
Name         : firefox
Version      : 92.0
Release      : 2.fc34
Architecture : x86_64
Size         : 253 M
Source       : firefox-92.0-2.fc34.src.rpm
Repository   : @System
From repo    : updates
Summary      : Mozilla Firefox Web browser
URL          : https://www.mozilla.org/firefox/
License      : MPLv1.1 or GPLv2+ or LGPLv2+
Description  : Mozilla Firefox is an open-source web browser, designed for
             : standards compliance, performance and portability.

```

![image](https://user-images.githubusercontent.com/667047/134493609-64bf6ac6-d4b5-4ae4-8b1b-3c3edd5c840e.png)

**Comment by jacogr** [comment]
It is a local issue, the extension itself doesn't really call auto-close. With the same versions it is actually in daily use, no such issues.

Some things to try -

- disable/enable the extension (that forces a reload, maybe something is weird in the state)
- disable all other extensions and see if that resolves it (if it does, enabling one by one may yield the culprit)
- with the 0.40.x version, you can configure the notifications to either not popup at all, or open in a new tab (via settings)

**Comment by drahnr** [comment]
> It is a local issue, the extension itself doesn't really call auto-close. With the same versions it is actually in daily use, no such issues.

Do you mean an issue specific to my machine, or fedora / firefox combo?

> Some things to try -
> 
>     * disable/enable the extension (that forces a reload, maybe something is weird in the state)

Unfortunately no change.

>     * disable all other extensions and see if that resolves it (if it does, enabling one by one may yield the culprit)

No change either.

>     * with the 0.40.x version, you can configure the notifications to either not popup at all, or open in a new tab (via settings)

I assume you mean the gear symbol within the popup, and yes the app does work when used from a separate tab.

Note that polkadot.js is the only extension with this issue, other apps and their popups behave as expected.

**Comment by jacogr** [comment]
On your setup. 

Sadly there is nothing I can do, since it doesn’t show the same behavior for me. (Same versions, but Mac). 

PRs welcome from somebody that can replicate.

**Comment by Tbaut** [comment]
I can't reproduce on Firefox/Linux Mint indeed.

**Comment by drahnr** [comment]
After reinstalling and rebooting, it worked for a limited time, now it's back to the 1sec.

![image](https://user-images.githubusercontent.com/667047/135808178-f8864a9c-0f0d-4f6e-a04f-34e454ee51b1.png)
