### ISSUE TITLE
Move messaging from ui to base extension

### ISSUE THREAD

**Issue by AndreiEres** [polkadot-js/extension#839]
We have messages definition in UI module: https://github.com/polkadot-js/extension/blob/master/packages/extension-ui/src/messaging.ts

But handlers for messages located in base extension, as well as some parts that looks like messaging like here https://github.com/polkadot-js/extension/blob/master/packages/extension-base/src/page/index.ts

Maybe would be better to move it to base extension?

**Comment by jacogr** [comment]
It is the UI side of the messaging. The base is for the background processing end.
