### ISSUE TITLE
Using Polkadot JS extension from another extension

### ISSUE THREAD

**Issue by LaurentTrk** [polkadot-js/extension#849]
Hi guys,

At this time, **it is not possible to use the Polkadot JS extension from another extension**, the content scripts needed from the Polkadot JS extension are not injected in the other extension.

One solution could be the use of [the Chrome Cross Extension messaging feature](https://developer.chrome.com/docs/extensions/mv3/messaging/#external), which allow one extension to exchange messages with another.

For my own needs, I started working on this. You will find the related code (_work in progresss_) in the following repositories:
- [Polkadot Extension](https://github.com/LaurentTrk/extension/tree/ExternalDecryptFeature) : the extension should be opened for [external requests](https://github.com/LaurentTrk/extension/commit/90e130db2f79f1def9d332857aaa4c63c6a3f23a).
- [DApp Extension](https://github.com/LaurentTrk/js-sdk/tree/phapass/packages/phapass-extension) : we [exchange messages](https://github.com/LaurentTrk/js-sdk/blob/phapass/packages/phapass-extension/lib/polkadotExtension.ts) with the extension instead of using the `extension-dapp` package.

Do you guys think it make sense to implement this feature in the Polkadot JS official extension ?
Please let me know if you want to discuss this further :)
Thanks for your help.

**Comment by h4x3rotab** [comment]
Sounds reasonable. Laurent is building a password manager like LastPass as a browser plugin and uses Phala's confidential smart contract as the backend. When talking to the Phala blockchain, it's necessary to invoke Polkadot.js extension to sign transactions or sign query payloads.

**Comment by jacogr** [comment]
For external requests, i.e. https://github.com/LaurentTrk/extension/commit/90e130db2f79f1def9d332857aaa4c63c6a3f23a - think it would have use-cases.
