### ISSUE TITLE
Manage access as previously granted

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/extension#85]
Goal:

The user should be able to check access on a per site basis and either approve/reject these.

Actions:

- storage permissions to storage
- page where the user to reject or approve based on sites that requested access

Similar to #10

**Comment by jacogr** [comment]
#289 May have a simpler (at least first phase, whack-all) solution

**Comment by tomusdrw** [comment]
Would be good to have at least an option to see "recently rejected" websites (even if not persisted) with an option to revert, in case user accidentally rejects the prompt.
