### ISSUE TITLE
Chrome extension UI overlapping and not rendering correctly 

### ISSUE THREAD

**Issue by rdmcolorz** [polkadot-js/extension#876]
When trying to create a account on the Polkadot JS extension on chrome, the popups don't show correctly, and clicking on buttons doesn't work sometimes. Typing is also not rendered correctly. I had to switch to window mode for it to work properly.

![image](https://user-images.githubusercontent.com/29620937/140446469-4a4e4ca6-accb-4455-a011-219918c56cab.png)

**Comment by jacogr** [comment]
Which version of Chrome?

**Comment by rdmcolorz** [comment]
> Which version of Chrome?

Version 95.0.4638.69 (Official Build) (x86_64)

**Comment by Andru2100** [comment]
у меня вообще расширения не работают, не могу запустить https://polkadot.js.org/apps/#/explorer

**Comment by Andru2100** [comment]
Можете помочь корректно настроить

**Comment by Andru2100** [comment]
Здравствуйте! Можете подсказать, как избавиться от проблемы removechild на acala
