### ISSUE TITLE
Scanned QR should contain either extrinsic or a message to sign

### ISSUE THREAD

**Issue by magianxd** [polkadot-js/extension#881]
This happens when I verify an account(for example, I was asked to sign a message to verify my ownership of the account. This message is not a transaction, and it doesn't cost any fees), the extension also generates a QR but since it is not a transaction, parity signer cannot parse the QR

**Comment by jacogr** [comment]
Please direct this to the Parity Signer product - I'm unsure about their roadmap for support of these.

**Comment by daCapricorn** [comment]
@jacogr I decoded the qr code in hex. And found that if I change the 210-212th bytes then parity signer works. So I think it is not parity signer's responsibility.

**Comment by jacogr** [comment]
According to the UOS spec https://github.com/maciejhirsz/uos#substrate-payload the sign-message indicator is 3.

1. For signing the byte is defined here - https://github.com/polkadot-js/extension/blob/master/packages/extension-ui/src/Popup/Signing/Request/index.tsx#L37
2. It is used here - https://github.com/polkadot-js/extension/blob/master/packages/extension-ui/src/Popup/Signing/Request/index.tsx#L149

The extension operates as per spec.

**Comment by daCapricorn** [comment]
sorry…it's should be the 53th byte. 

The question is if I remove polkadot.js extension and add parity signer's accout via "Add via Qr" on [https://polkadot.js.org/apps/#/accounts](https://polkadot.js.org/apps/#/accounts), parity signer works well.
<img width="1680" alt="截屏2021-11-15 13 21 29" src="https://user-images.githubusercontent.com/1331545/141726827-08a72ef5-b8df-491f-9885-faf7dce1a3d3.png">

I compared the qr codes generated by [https://polkadot.js.org/apps](https://polkadot.js.org/apps) and the one generate by the extension. The 53th byte is different.

**Comment by jacogr** [comment]
The apps UI doesn't have the capability to sign via QR (it is not implemented), see 

![image](https://user-images.githubusercontent.com/1424473/141728577-3c34a655-fd1b-42d0-83b4-cbf0f374dfbc.png)

**Comment by daCapricorn** [comment]
@jacogr try Accounts -> Transfer, Developer -> Extrinsics or Crowdloan…

**Comment by jacogr** [comment]
That also works in the extension. This issue is about signing arbitrary messages, not transactions. (2 different payloads as per spec)

**Comment by jacogr** [comment]
Anyway, closing this is not a extension functionality issue. Arbitrary message signing does work via QR, there are on-phone apps such as Stylo that does have this functionality today. It is just not something implemented in the Parity Signer it n the currently released version.
