### ISSUE TITLE
An error occured Something went wrong with the query and rendering of this component. Unable to find supported chain for 0x290a4149f09ea0e402c74c1c7e96ae423958857

### ISSUE THREAD

**Issue by aaasalimi** [polkadot-js/extension#885]
Same as below link Error in https://app.stafi.io/ 

Error  https://github.com/polkadot-js/extension/issues/694

Fix it Please

thanks

**Comment by jacogr** [comment]
There is no Stafi Ledger app so the extension correctly disallows it operation. See https://github.com/Zondax/ledger-substrate-js/blob/main/src/config.js#L18-L29 for a list of currently supported apps in the Ledger libraries

**Comment by aaasalimi** [comment]
List Stafi too please. 
I swap FIS to attach Ledger account in polkadot-js extension, and i cant do any transaction.

**Comment by jacogr** [comment]
I can’t do anything to “list Stafi “ - they need to commission a Ledger app.

**Comment by aaasalimi** [comment]
Ledger Support Reply about this issue
" I am afraid we can not do anything for you **until an app for Stafi is created by the DOT community for Ledger devices.** "

Wendy (Ledger Support)

Nov 10, 2021, 13:51 GMT+1

Hi there,

Thank you for reaching out to Ledger Support, my name is Wendy and I will gladly assist you. 

Unfortunately, we do not have any solution for this issue you are facing, I am really sorry about the position you are in right now. 

Indeed there is no Stafi app available now so if you sent your funds to an address generated on polkadot.js using the Polkadot app and your ledger device, I am afraid we can not do anything for you until an app for Stafi is created by the DOT community for Ledger devices.
