### ISSUE TITLE
PLEASE HELP - PASSWORD ISSUE

### ISSUE THREAD

**Issue by mplsPmac** [polkadot-js/extension#887]
PLEASE HELP; In an effort to create a secure  password, I wrote it down incorrectly and now, I cannot log into my Polkadot extension.  I have the 12 word seed phrase, just can't use the password, as I wrote down some character wrong.  I can't find any link or instructions on how to access my account using just the seed phrase.  Can someone please direct me on how this can be done.  

This happened on Monday and spent the last 2 days trying to find directions or assistance on this matter and finally made my way to you, via Github

Regards -
Peter Maczko
Peter.J.Maczko@gmail.com

**Comment by v-van** [comment]
If you wrote down the mnemonic in the right order, you can check the [mnemonic word list](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt) to correct each word.
So that, try to reimport the mnemonic into polkadotjs.

Good luck!

**Comment by jacogr** [comment]
"Import account from pre-existing seed" (4th from top) -

![image](https://user-images.githubusercontent.com/1424473/141080540-1b4762b1-fb62-4d93-b0c5-478eff848b2c.png)

Then add the mnemonic and next -

![image](https://user-images.githubusercontent.com/1424473/141080766-d16fbea4-476c-4ba2-b41c-39142b9100f3.png)

**Comment by mplsPmac** [comment]
> If you wrote down the mnemonic in the right order, you can check the [mnemonic word list](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt) to correct each word. So that, try to reimport the mnemonic into polkadotjs.
> 
> Good luck!

**Comment by mplsPmac** [comment]
SUCCESS!!  Thanks so much for your help!!
