### ISSUE TITLE
*solved* 'Waiting to make a connection to the remote endpoint and finishing API initialization.''  ;switched-chains but ..

### ISSUE THREAD

**Issue by Adppy** [polkadot-js/extension#889]
ok, n00b, dyslexic, and autistic, please bear with ..

polkadot [js] was functional no-prob ;contributed to crowdloan[s], 

cleared cookies [chrome] to find ''waiting for initialisation ....'' loop so to speak ..

employed google search, 'switched' over to  available-chains:
  '' via Parity
via OnFinality
via Patract Elara
via Geometry Labs''  ..and others, to be concise. ..

and, well, i find myself here, 

-hope this makes some-kind of sense, 

-happy to elaborate ..given correct question i suppose ;appear to be a 'stuck' at the time of writing ..

thank you for any help in this regards.

**Comment by Adppy** [comment]
addendum ..

endeavour to connect sites that in the past [pre cookie-clear] was no-prob connecting results w/ either:

 ''connect to wallet''  but Polkadot{.js} extension splash-screen does not appear

 [or] apparently 'no-thing'  well, anything apparent to my current level of understanding, like no apparent UI changes / notifications so to speak ..


thanks for reading ..

**Comment by Adppy** [comment]
*solved*

ok so past 2x hours or so test, re-test [am autistic, like-actually] appears to be that ''clover'' extension ?!effects prob w/ regard to polkadot js org

*n00b, but yeah, thats what appears to have effected problem one was experiencing ..

loads fine post dis-abling ''clover extension'' idky but ye xx

**Comment by Jonsson90k** [comment]
Aver si funciona

**Comment by jacogr** [comment]
Closing, resolved.
