### ISSUE TITLE
Privacy enhancing features

### ISSUE THREAD

**Issue by jonasW3F** [polkadot-js/extension#893]
As far as I understand it, websites that have access to the extension (naturally) are allowed to see all the accounts in the extension. This has serious implications for privacy because it would allow adversaries to cluster accounts around entities and in the worst case, where one or more accounts are linked to identities are possible to doxx the person or their token holdings.

A way around it currently is to hide accounts. As far as I understand, they are then invisible to a website and you could manage which site has access to which accounts. This is an important feature to protect the privacy of the users, but I think it should be made easier to use and requires some more QOL functions. Specifically, those are:
1) A simple "hide all" button. You could then selectively unhide those accounts that you want to interact with.
2) Being able to organize accounts into view-groups and being able to select those groups which automatically hide/unhide the respective accounts.
3) Privacy mode. An optional feature that auto-hides all accounts after X minutes (or potentially this feature could be enabled per account).
4) "Hide from extension". Feature to hide the accounts in your extension when making demos, being in presentation mode etc. Would require a special tab in the extension to see and manage the hidden accounts.

I understand that programming resources are scarce but I think this is an important feature, especially with the growing size of the ecosystem where you log in with your extension at an increasing number of (shady) pages. I myself do not have the time and resources to make a PR, therefore I propose to create an RFP in the name of W3F Grants and ask for somebody to implement that. Before that, it makes sense to discuss this:

1) Do you think this feature(s) make sense in general?
2) Are there additional features?
3) How much should we pay for the delivery of the results?

Cheers
Jonas

One general question: Do websites have a way to identify the extensions regardless of the accounts they see? So say, I have Account A and Account B in the extension and I access the site by hiding A and then later (with a new IP) by hiding B. Would the website have a way to identify the extension itself and thereby be able to infer that I hold Account A and Account B?

Edit: Based on feedback

**Comment by Swader** [comment]
I would say that account groups make sense here as a feature. You can "tag" addresses with something like "demo", "public", "governance", "cross-chain" and more, and then choose on the extension which group the website has access to. This way, it's easy to define a single "default" group of a single address that's the default, but also easy to switch when needed.

Hide all is definitely also needed, as well as hiding from the extension itself  (useful for live demos) - this would also be resolved by the above groups, if the interface in the extension were tabulated to support context switching like that.

**Comment by semuelle** [comment]
Can we show a list of addresses (and groups) with checkboxes in the `Authorize` popup to select what you want to reveal, so you don't have to hide or unhide addresses (and groups) _before_ connecting?

**Comment by alxs** [comment]
@jonasW3F to answer the question at the end, maybe not directly through the extension (I don't know), but even then it's very likely you'd be identifiable through your [browser fingerprint](https://amiunique.org/).
