### ISSUE TITLE
signer.signRaw signing doesn't work with Ledger Nano X

### ISSUE THREAD

**Issue by BigBadAlien** [polkadot-js/extension#897]
Steps:
- Install Polkadot application to Ledger

<img width="881" alt="Screenshot 2021-11-24 at 20 16 01" src="https://user-images.githubusercontent.com/2698505/143284982-605541b2-4680-4376-b6ef-8ec538dab317.png">

- Run it

![photo5834931295065586028](https://user-images.githubusercontent.com/2698505/143285857-ad9a3aae-000c-4ad1-b443-c78072f5aef3.jpg)

- Import Ledger Nano X account
<img width="540" alt="Screenshot 2021-11-24 at 20 06 59" src="https://user-images.githubusercontent.com/2698505/143283688-09fb677f-cb81-422a-b5d0-7c0d1e354736.png">

- Run the code:
```
    const injector = await web3FromAddress(account);
    const { signature } = await injector.signer.signRaw({
      type: 'bytes',
      address: account,
      data: hexData
    });
```

Current behaviour:
<img width="549" alt="Screenshot 2021-11-24 at 20 03 13" src="https://user-images.githubusercontent.com/2698505/143284126-a3d0bff9-a6eb-41f6-8514-69de059132dc.png">

User see modal window where only cancel operation is available.

User should confirm the operation by Ledger but there is no change on Ledger screen.

Expected behaviour:

Open confirmation window and ask user on Ledger to confirm the signing.

Btw, it works well without Ledger and looks like this:
<img width="545" alt="Screenshot 2021-11-24 at 20 04 09" src="https://user-images.githubusercontent.com/2698505/143284059-f01cda12-1a4f-49b6-987e-8077bc30a967.png">

**Comment by jacogr** [comment]
Indeed. Ledger only supports transaction signing.

**Comment by BigBadAlien** [comment]
Any plan to fix it? e.g.

- Inform that the operation is not supported
- Or give a way (public API) to detect that the operation is not supported in current environment

**Comment by BigBadAlien** [comment]
@jacogr I can provide a PR if we have a decision how to resolve it

**Comment by jacogr** [comment]
The best is to inform the user properly in this case, i.e. the above dialog can be extended.

**Comment by RodgerQ** [comment]
im having the same issue. is there a fix?

**Comment by BigBadAlien** [comment]
> 

<img width="548" alt="Screenshot 2021-12-02 at 01 16 10" src="https://user-images.githubusercontent.com/2698505/144323001-ceb065bf-ca64-4c82-802a-9afb3a314e31.png">

like this? 🤔

**Comment by BigBadAlien** [comment]
What about make an open API to detect is a feature supported or not for an address?

e.g. In some cases for sake of application UX we need to warn user as early as possible that current feature is not supported and describe steps how to resolve the situation instead of disappoint user on the last step

**Comment by RodgerQ** [comment]
I don’t even get a warning that it doesn’t work.

**Comment by RodgerQ** [comment]
Yeah I have no idea how to transfer my funds around . Do I delete the .js or remove it from browser. I have funds locked up

**Comment by BigBadAlien** [comment]
@jacogr So, what do you think regarding open API to get availability of a feature? Like `isFeatureAvailable('signRaw')`

e.g. user can sign transaction and stake funds but he can find that unstake is impossible only on last step and it can piss off him. We want show a warning that unstake is impossible by Nano Ledger but no way to detect does user use hardware wallet or signRaw support

**Comment by RodgerQ** [comment]
sorry guys im new here just trying to see what to do.. but from reading your guys thread looks like im screwed on unstaking my funds. thanks for coming back to this guys.

**Comment by BigBadAlien** [comment]
> sorry guys im new here just trying to see what to do.. but from reading your guys thread looks like im screwed on unstaking my funds. thanks for coming back to this guys.

I think you need to ask the staking service support how to unstake your funds. Likely the current thread can't help you but some future stakers can avoid such mistake if we resolve the issue

**Comment by jacogr** [comment]
Why is unstake unavailable with no `signRaw`? It is only used when signing non-transactional messages.

**Comment by RodgerQ** [comment]
i just wrote in the discord.. will try to get up to support.. i dont even get any options but cancel. when trying to unstake

**Comment by themacexpert** [comment]
@BigBadAlien @RodgerQ Have you tried installing Polkadot XL after enabling Developer mode? Due to the limited storage space on the Nano S the device by default installs a smaller footprint app. By installing Polkadot XL you gain access to a larger number of extrinsics that the device can support. https://support.polkadot.network/support/solutions/articles/65000179210-ledger-error-not-supported

**Comment by BigBadAlien** [comment]
> Why is unstake unavailable with no `signRaw`? It is only used when signing non-transactional messages.

Our product claim tokens to Ethereum Mainnet, the flow is a bit more complex than just one transaction in Polkadot

**Comment by BigBadAlien** [comment]
> @BigBadAlien @RodgerQ Have you tried installing Polkadot XL after enabling Developer mode? Due to the limited storage space on the Nano S the device by default installs a smaller footprint app. By installing Polkadot XL you gain access to a larger number of extrinsics that the device can support. https://support.polkadot.network/support/solutions/articles/65000179210-ledger-error-not-supported

I installed the version but have the same result as before

**Comment by convexman** [comment]
If I'm not mistaken and [this](https://github.com/LedgerHQ/app-polkadot) is actual repo for ledger polkadot firmware then it seems from code that device is ready to sign any bytes provided (after some hardware package handling it ultimately boils down to [this](https://github.com/LedgerHQ/app-polkadot/blob/master/app/src/common/actions.h#L29) function which just signs the bytes provided).

Though [ledger common libraries](https://github.com/LedgerHQ/ledger-live-common/tree/master/src/families/polkadot) which are used in desktop and mobile apps just don't have API for signing arbitrary payloads. The only place where signing is called seems to be [here](https://github.com/LedgerHQ/ledger-live-common/blob/master/src/families/polkadot/js-signOperation.ts#L196) and it's for transaction signing.

Anyways this has little to do with polkadotjs, I think it's logical to raise in issue in ledger repo and then return here to ensure that everything works fine in conjunction with polkadotjs.

**Comment by RodgerQ** [comment]
Does this mean there is no fix? Idk who to contact at this point.

**Comment by jacogr** [comment]
Closing. There is no Ledger signRaw functionality available - Ledger cannot sign raw data in the interface provided. Nothing that can be done on the extension.
