### ISSUE TITLE
Lack of currency

### ISSUE THREAD

**Issue by Ehsanhooooshangi** [polkadot-js/extension#902]
Hi , I transferred some polkadot to my wallet but it has not been inserted yet, please help, the transaction number to Fallow
0x7f5ed972ba52bd0fb3248f5446d101b0f36ce3ac2c7cdfbb2414a5e4823e651f

**Comment by jacogr** [comment]
The extension doesn't show balances, it is only a transaction signer.

**Comment by Ehsanhooooshangi** [comment]
I lost 12 words of recovery. How can I find it in my wallet?
