### ISSUE TITLE
Feature request: Bulk import accounts

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/extension#906]
Feature: Allow users to bulk import multiple accounts into the extension quickly. This would be useful for people that are reliant on the extension but need to changing to a different computers, or they use multiple computers.

The UI menu would include the following options:

1) Import **multiple** accounts from pre-existing seeds

Initially this feature would would have two text input fields. The first would allow them to quickly paste a comma-separated list of existing 12 or 24-word mnemonic seed phrases, and the second would allow them to paste a comma-separated list of the hex values that represent their corresponding network (or optionally not have a send input field and just allow them to be used on any network)

2) Restore **multiple** accounts from backup JSON files

This would allow the user to select multiple JSON files at once, that would appear as a list in the UI, with a password field on the right-side of each one where the user could enter the password (or optionally if the user has multiple accounts that all have the same password, allow them to show a single password input field and apply that to all the accounts being imported)

I think 1) would be the easiest to implement and satisfy those users. 

Would anyone else in the community enjoy this feature?

**Comment by jacogr** [comment]
It is available. You can import the batch exported via the import JSON option.
