### ISSUE TITLE
Extension no longer available in Chrome Webstore

### ISSUE THREAD

**Issue by phantomcrypt** [polkadot-js/extension#913]
I've received an alarming notification that the extension was no longer available in the [chrome web store](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd).

Following the link through on the [official website](https://polkadot.js.org/extension/), gives the same results.
The Firefox store was not affected, and continues to be available.

Is it safe to use the old version? what's the best course of action for users that want to install the extension for the first time?

**Comment by jacogr** [comment]
Yes, aware of it and have been dealing with the Chrome webstore support on this.

Basically the automated source analysis indicates that the permissions in the manifest is too wide, specifically asking for storage which based on the code scanning is not used. However, it is certainly used to store accounts and metadata, aka here in the source https://github.com/polkadot-js/extension/blob/master/packages/extension-base/src/stores/Base.ts#L24

(As any extension user can attest to)

Hoping to get a resolution soon and have it re-enabled, but as of now no ETA.

**Comment by jacogr** [comment]
It should be available again soon, just received the following update -

"
Hello Developer,

Thank you for sharing information. We apologize for the inconvenience caused to you in this matter.

As per our subsequent  review, we found that your item “polkadot{.js} extension” with ID: “mopnmbcafieddcagagdcbnhejhlodfdd” is in compliance with our Use of permissions policy as the item is using storage permission. Hence, your item has been reinstated and will be available in the store shortly. 

We value your contributions to the Chrome Web Store.

Thank you for your cooperation, 

Chrome Web Store Developer Support
"

**Comment by michalisFr** [comment]
Thanks for taking care of this @jacogr! The extension is live in the web store again!

Also, please check your DMs in Element. Thanks!

**Comment by jacogr** [comment]
Sadly my life is on GH - I'll get to Element when I have a gap, it is a crazy week/month, so chatting has been left by the wayside.
