### ISSUE TITLE
mnemoic

### ISSUE THREAD

**Issue by TerraLunatic** [polkadot-js/extension#915]
when i type my seed phrase in the box it says that I am not typing the seed phrase correct although its correct I am using firefox
I due to the fact that the extension will not work on chrome period

**Comment by jacogr** [comment]
Ensure you have all 12 words correct, i.e. just tested this seed (fresh creation) on FF and it outputs the correct details - 

`surge lyrics outdoor crop erode increase label milk pilot vicious kiss slender`
