### ISSUE TITLE
[Windows] Lost all accounts after reboot and browser update

### ISSUE THREAD

**Issue by Swader** [polkadot-js/extension#920]
Rebooting after an update of both OS and browser on Windows 10 / Brave, I lost all accounts in the extension - full wipe. 

Wondering if this is a known issue and there could be an option added to periodically back them all up so that I don't have to go to cold storage to dig up seeds and re-enter it all manually.

**Comment by jacogr** [comment]
You can export all accounts in a single-go via the "Export all accounts" and import it via the JSON option.

**Comment by jacogr** [comment]
It is a bug introduced here - https://github.com/polkadot-js/extension/pull/891/files#diff-cfd99513688194d3837867e587e0fc523f2de4364873561b00cecb36fbc334dbR11

**Comment by jacogr** [comment]
Updates submitted, FF update for 0.42.2 is available, Chrome is pending

**Comment by jacogr** [comment]
Published for Chrome as well.
