### ISSUE TITLE
[0.42.2] Breaks certain content

### ISSUE THREAD

**Issue by lucasvanmol** [polkadot-js/extension#930]
As of this update some content, like Latex formatting, gets broken for certain websites.

e.g. https://physics.stackexchange.com/questions/682336/killing-tensor-of-friedman-robertson-walker-metric-not-assuming-flatness

With extension enabled: 
![image](https://user-images.githubusercontent.com/16979353/146056721-5e1e6b17-beeb-498a-94e2-f751c276d556.png)

Extension disabled:
![image](https://user-images.githubusercontent.com/16979353/146056847-3b315ad4-2776-4ee0-8068-ec6d44bb0b0e.png)

Not only Latex is broken, but some other content does not show up. I first noticed in the website piazza.com where instructor's answers were not being displayed (which is harder to provide an example of, sorry), in addition to Latex content being broken. I suspect the issue might be related.

**Comment by jacogr** [comment]
Thanks for the reproduction- will take a peek. 

This is _exceptionally_ weird - it does not interact with the content (obviously has an injection script with dapp listeners, but doesn’t touch content)
