### ISSUE TITLE
How can I know the derivation path of parachains ? 

### ISSUE THREAD

**Issue by freehuoshan** [polkadot-js/extension#931]
I want import the account generated by polkadot js to Parity Signer , but need to know the  the derivation path of Pokadot or Kusama in this js extension. any where I can see that information ?

**Comment by Tbaut** [comment]
This is a Parity Signer issue. Please reach out on the appropriate repo e.g https://github.com/paritytech/parity-signer/issues/833
Signer adds a derivation by default, whereas the extension does not. You need to make sure you get the root account (without derivation) on Signer.

Note that what you are doing may not be as secure as it seem. If the account you created on the extension is compromised, storing and using it on Signer will not make it more secure. Creating a new account on the offline device is the way to go.
