### ISSUE TITLE
Release @polkadot/extension-mocks to npm

### ISSUE THREAD

**Issue by AndreiEres** [polkadot-js/extension#945]
There is an error on trying to update @polkadot/extension-base
```
Couldn't find package "@polkadot/extension-mocks@^0.42.3" required by "@polkadot/extension-base@^0.42.3" on the "npm" registry
```

**Comment by jacogr** [comment]
Erk. Sorry about that. It is actually a dev-dep, so will need to tweak sligthly.

**Comment by jacogr** [comment]
https://github.com/polkadot-js/extension/releases/tag/v0.42.4
