### ISSUE TITLE
Good practices of accessing account from extension

### ISSUE THREAD

**Issue by nazar-pc** [polkadot-js/extension#952]
I'm getting annoyed every time I access most if not all websites that can interact with Polkadot.js extension because they try to access extension immediately without ability to ignore request, I have to decide right away if I want to accept it or reject it. And I universally reject such request and get angry on top of it.

This is a pretty bad user experience and should ideally be changed and recommendations should be given to various teams on how to use it. This is somewhat similar to access to geolocation or notifications that some websites request before I even know what those websites are, so I definitely don't want to give them access to my accounts.

That is worse, just like with https://github.com/polkadot-js/extension/issues/764 there is again no way to remove those websites from the list once I accepted or rejected request, they just keep piling up.

So I think 3 things are needed:
* [ ] just like https://github.com/polkadot-js/extension/issues/764 requested, there should be a way to delete things I no longer need from extension, in this case websites
* [ ] create official recommendations for how to make user experience better with an extension (and require something like what browsers do: interaction with the page before even allowing an app to access extension's API)
* [ ] follow ^ recommendations in official apps

**Comment by nazar-pc** [comment]
Can someone label this so bot doesn't try to close it, please?

**Comment by nazar-pc** [comment]
This is still important and shouldn't be closed

**Comment by Tbaut** [comment]
I very much agree with you here. 
This extension repo only receives strictly maintenance from its owner though, any feature is added by the community. I will happily contribute to allow to remove specific websites from the "allow list". This may take some time though. 

Adding recommandation documentation is easy to do, litteraly anyone could add this in a PR. However, I believe that you should make an issue specifically for apps (in apps repo) so that the call to request the extension account is only made upon user action.

**Comment by nazar-pc** [comment]
This is still important

**Comment by nazar-pc** [comment]
Please don't close, it is important

**Comment by nazar-pc** [comment]
Please don't close, it is important

**Comment by nazar-pc** [comment]
Please don't close, it is important

**Comment by jacogr** [comment]
Closing. There is nothing to be done here. I would suggest you log it with the apps you have issues with explicitly to make this opt-in (in whichever way, if they choose to do so), the extension only provides the tools.

**Comment by nazar-pc** [comment]
I mean every single app that is using this extension has the same exact anti-pattern UX. The web has finally fought that with requests for geolocation, desktop notifications that were popping up on many websites with no user interaction.

Now I have déjà vu every time I open website that uses Polkadot.js extension with popups in my face, no ability to just ignore it, I have to decide to permanently accept or reject. It is just bad UX and it is not just about third-party websites, it is the same across the whole ecosystem, including official ones.

So from my point of view there is obviously a lot to be done both on the extension itself, and on guidelines for apps and on the official apps too.

It would be really unfortunate if the current status quo remains indefinitely.
