### ISSUE TITLE
Layout ideas

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#96]
We'll need to make some space for more settings such as 
- Manage Dapp authorization
- Select which accounts are visible
- Select Networks (to inject or to create accounts for)
- Add accounts with a JSON
- Add accounts with Parity Signer

We end up a little like in the situation of Fether, so my ideas are very much biased, however I think it worked well. Here's a bad drawing of what I thought about:

- global account selector showing accounts from the keyring associated with the network
- eyes to make an account visible or not (and make account have lower opacity)
- a + that contains all the account related menus
- a hamburger menu that contains all the general menus.
- a new page where users can manage their network name and address (would appear then in the general network menu)

![image](https://user-images.githubusercontent.com/33178835/61443729-5f1e3500-a94a-11e9-9d07-ace1c59c8aa7.png)

**Comment by jacogr** [comment]
Related to #85, #15, #10

**Comment by jacogr** [comment]
Closing. Rework ongoing.
