### ISSUE TITLE
Extension causing issues with mathjax on firefox

### ISSUE THREAD

**Issue by vividbook** [polkadot-js/extension#965]
Hello. It seems that the extension is causing some issues with mathjax (a fairly popular js engine used to render mathematics in the browser). For some reason, when the extension is installed and mathjax is loaded in a page, the following error occurs:

`Uncaught TypeError: window.chrome is undefined`

and mathjax does not render the mathematics on the page.

When the extension is uninstalled, the error disappears and the mathematics is rendered properly.

I have tested this using Firefox 95.0.2.

It seems that you can use any webpage that loads mathjax to reproduce the issue. Here is a random example: https://stacks.math.columbia.edu/tag/0748

**Comment by Tbaut** [comment]
This sounds like the same as what was reported in https://github.com/polkadot-js/extension/issues/930

**Comment by jacogr** [comment]
Sounds similar indeed. I have something untested that went in last night, that may help. (Have not run master against FF as of yet)
