### ISSUE TITLE
Wrong network title

### ISSUE THREAD

**Issue by akru** [polkadot-js/extension#979]
Hello, 
could you please rename Plasm to Astar in network list.

![867D5C7C-095A-4E84-B2C4-5D41628C24A3](https://user-images.githubusercontent.com/786394/149710740-94eb5d27-6a5f-4669-aed1-df137debdfd2.jpeg)

**Comment by jacogr** [comment]
It is updated in the `@polkadot/networks` package (aka that follows the ss58registry repo, see https://github.com/polkadot-js/common/blob/master/packages/networks/src/substrate.ts#L67) - however a release needs to be made. 

It is never a quick process dealing with the web stores and there is sometimes a lot of to-and-fro to get it approved, so it is not taken lightly and only done when there is significant functional reasons to do so, aka it doesn't move at nearly the same speed as libraries of web-only properties

**Comment by akru** [comment]
Thank you for explanation @jacogr!
