### ISSUE TITLE
Reset "Website Access" list

### ISSUE THREAD

**Issue by takahser** [polkadot-js/extension#986]
Currently there seems to be no way to reset the "Website Access" list within the polkadot.js settings.
All I can do is enabling/disabling access that any given website has to the polkadot.js extension in case I allowed/rejected it before.
![image](https://user-images.githubusercontent.com/5393704/150860655-43caf745-d07c-42d7-93d1-910c6f393aa0.png)

Imho it should be a core functionality to simply reset the whole list or even access for individual webpages, similarly to the [metamask extension](https://metamask.zendesk.com/hc/en-us/articles/360059535551-Disconnect-wallet-from-Dapp).
![image](https://user-images.githubusercontent.com/5393704/150860893-6af5b677-9a5b-4ce3-b764-a6ad924f8868.png)

**Comment by takahser** [comment]
Can somebody label this as an enhancement or at least give some feedback please?
I'd definitely rate this as an enhancement.

**Comment by takahser** [comment]
@jacogr @Tbaut @4vanruch
Any feedback would be highly appreciated 🙏

**Comment by jacogr** [comment]
The idea is not to duplicate metamask here.
