### ISSUE TITLE
Module parse failed: x-textencoder

### ISSUE THREAD

**Issue by sgurin** [polkadot-js/extension#990]
Hi, guys. Smth strange error happening when I trying to import module 
![image](https://user-images.githubusercontent.com/25930200/151407332-5c2e8b14-cf59-4455-a953-60e02de77cb4.png)
I assume that I need to add WebAssmble loader. Right?

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/usage/FAQ#on-webpack-4-i-have-a-parse-error-on-importmetaurl
