### ISSUE TITLE
Module parse failed: Unexpected character '#' 

### ISSUE THREAD

**Issue by sgurin** [polkadot-js/extension#991]
Hi, guys.

I think Polkadot SDK is not bundled correct. Best practices is use UMD for module and transpile code in ES6.

In some files I see _this that means code was transpiled but at the same time this.#chainProperties class private properties not transpiled. I assume that plugin did not transpiled via https://babeljs.io/docs/en/babel-plugin-proposal-private-methods or https://babeljs.io/docs/en/babel-preset-env

![image](https://user-images.githubusercontent.com/25930200/151586503-b3809a78-fa5e-44a7-84c7-60f4544c1d6c.png)

**Comment by jacogr** [comment]
It is valid ES6. The build process won’t change. If it is an issue for you, either stay on an earlier version or upgrade to a recent version of your bundler. (Ancient WP4 version for instance have issues with private fields, although all browsers support it)

**Comment by sgurin** [comment]
Hi, unfortunately I cannot update Typescript version. Is there any way to find already compiled bundle in ES5?
