### ISSUE TITLE
When I recovered my account using the seed phrase i generated a new different account

### ISSUE THREAD

**Issue by KeyserSoze12345** [polkadot-js/extension#993]
I tried to recover my account on polkadot.js extension using my seed phrase, but it generated a different account.  Now all of my dot and crowdloan contributions are gone.  I don't know what to do.

**Comment by esternon01** [comment]
it happened the same to me ... please anyone know what to do?

**Comment by esternon01** [comment]
Thanks for help me. But I dont know what to do... if you explain me how  I
can recover  my account I will be very happy. Dot forever!!

**Comment by Vadim0906** [comment]
#1016
