### ISSUE TITLE
Different signatures generated by KeyringPair & InjectedExtension.signer

### ISSUE THREAD

**Issue by VargSupercolony** [polkadot-js/extension#996]
## Description

Signing messages via `api.sign(account, data)` and `keyringPair.sign(data)` results in different signatures, as well as in differing public keys (when recovered from the signature). 

<img width="670" alt="img" src="https://user-images.githubusercontent.com/85491542/151965675-ff31f1cb-41fe-44cc-a473-f313cade6037.png">

The `signer` logs correspond to this code:

```typescript
	const signer = keyring.createFromUri(
		"foo foo foo foo foo foo foo foo foo foo foo bar//path"
	);
	console.log(`SIGNER PUBLIC KEY: ${signer.publicKey}`);
	console.log(`SIGNER PUBLIC KEY, HASHED: ${blake2AsU8a(signer.publicKey)}`);
```

The last log corresponds to this code:

```typescript
const signature = await api.sign(account, {data: myDataToSign, type: "bytes"}); // account here is injected from polkadot.js extension
console.log(
				`IS SIGNATURE VALID (BY POLKADOT JS)?: ${JSON.stringify(
					await signatureVerify(hexToU8a(myDataToSign), signature, u8aToHex(decodeAddress(account)))
				)}`
			);

```

So as you can see, when I sign my message with the injected account, I get hashed public key from signature, instead of my original 33-byte public key of the KeyringPair.

Can I somehow generate the signatures based on the 33-byte `ECDSA` public key of the original account, and not the hashed public key (which is decoded from the address)?

Thanks!

**Comment by jacogr** [comment]
You cannot compare a signature from the extension to that of the keypair - the extension will always wrap the data before signing, it doesn't sign the data as-is, while the keypair will sign it exactly as-is.

So basically the extension always does `pair.sign(u8aWrapBytes(message))` where wrap is from https://github.com/polkadot-js/common/blob/master/packages/util/src/u8a/wrap.ts#L42

**Comment by jacogr** [comment]
Last release extension version - https://github.com/polkadot-js/extension/releases/tag/v0.42.1
Which includes - https://github.com/polkadot-js/common/releases/tag/v8.1.1

The secp256k1 libs are different. And yes, there is a difference to what `elliptic` vs `secp256k1` produces (the latter actually aligns with this https://github.com/polkadot-js/wasm/releases/tag/v4.5.1)

**Comment by VargSupercolony** [comment]
I managed to get what I needed - just replicated the behavior on the contract that verified the signatures! Thanks, jacogr :)
